### ISSUE TITLE
v3.3 Cherry-picking

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#10000]
- [ ] 6b086368f fix: Mutex is not initialized when controller restart (#9873)
- [ ] ec5162983 fix: P/R/C reporting in argo list -o wide. Fixes #9281 (#9874)
- [ ] 6c432d2c9 fix: upgrade python openapiclient version, fixes #9770 (#9840)
- [ ] 36646ef81 fix: Support Kubernetes v1.24. Fixes #8320 (#9620)
- [ ] a752a583a fix: exit code always be '0' in windows container. Fixes #9797 (#9807)
- [ ] 102c3ec22 fix: migrated from distribution@v2.8.0 to distribution@v2.8.1. Fixes #9850 (#9851)
- [ ] d4a907411 fix: trigger startup.sh at devcontainer startup instead of create (#9831)
- [ ] f6a8b0130 fix: SDK CI workflow (#9609)
- [ ] faa0294f5 fix: fixed url encoded link template (#9792)
- [ ] d4817efff fix: fix iam permissions to retrieve logs from aws s3 (#9798)
- [ ] aa59b4374 fix: enable when expressions to use expr; add new json variables to avoid expr conflicts (#9761)
- [ ] 0fc883a41 fix: avoid nil pointer dereference. Fixes #9269 (#9787)
- [ ] cd43bba6c fix: Send workflow UID to plugins. Fixes #8573 (#9784)
- [ ] f27fe08b1 fix: default not respected in setting global configmap params. Fixes #9745 (#9758)
- [ ] dc48c8cf1 fix: Set scheduling constraints to the agent pod by the workflow. Fixes #9704 (#9771)
- [ ] f767f39d8 fix: artifactory not working. Fixes #9681 (#9782)
- [ ] 1fc6460fa fix: Log early abort. Fixes #9573 (#9575)
- [ ] f1bab8947 fix: a WorkflowTemplate doesn't need to define workflow-level input p… (#9762)
- [ ] b12b5f987 fix: SSO integration not considering HTTP_PROXY when making requests. Fixes #9259 (#9760)
- [ ] a8e37e9be fix: Concurrent map read and map write in agent. Fixes #9685 (#9689)
- [ ] d64b8d397 fix: quick-start-* manifests pointing to invalid httpbin image tag. Fixes #9659 (#9759)
- [ ] de4ea2d51 fix: `value` is required when parameter is of type `enum` (#9753)
- [ ] d9d1968de fix: node links on UI use podName instead of workflow name (#9740)
- [ ] 365b6df16 fix: Label on Artifact GC Task no longer exceeds max characters (#9686)
- [ ] 0851c36d8 fix: Workflow-controller panic when stop a wf using plugin. Fixes #9587 (#9690)
- [ ] 2f5e7534c fix: ordering of functionality for setting and evaluating label expressions (#9661)
- [ ] f0016e054 fix: Remove LIST_LIMIT in workflow informer (#9700)
- [ ] e08524d2a fix: Avoid controller crashes when running large number of workflows (#9691)
- [ ] 84c19ea90 fix: render template vars in DAGTask before releasing lock.. Fixes #9395 (#9405)
- [ ] b214161b3 fix: add authorization from cookie to metadata (#9663)
- [ ] b219d85ab fix: retry ExecutorPlugin invocation on transient network errors Fixes: #9664 (#9665)
- [ ] b96d446d6 fix: Improve semaphore concurrency performance (#9666)
- [ ] 38b55e39c fix: sh not available in scratch container but used in argoexec. Fixes #9654 (#9679)
- [ ] e6eb02fb5 fix: broken archived workflows ui. Fixes #9614, #9433 (#9634)
- [ ] e556fe3eb fix: Fixed artifact retrieval when templateRef in use. Fixes #9631, #9644. (#9648)
- [ ] 72d3599b9 fix: avoid panic when not passing AuthSupplier (#9586)
- [ ] 30bd96b4c fix: Error message if cronworkflow failed to update (#9583)
- [ ] ec7c210c9 fix: use urlencode instead of htmlencode to sanitize url (#9538)
- [ ] 3a3f15997 fix: enable workflow-aggregate-roles to treat workflowtaskresults. Fixes #9545 (#9546)
- [ ] 9d66b69f0 fix: for pod that's been GC'ed we need to get the log from the artifact (#9540)
- [ ] ef6bd5710 fix: Capture exit code of signaled containers. Fixes #9415 (#9523)
- [ ] f27475feb fix: default to 'main' container in Sensor logs. Fixes #9459 (#9438)
- [ ] 2a80a2c1a fix: revert accidental commit in UI logs viewer (#9515)
- [ ] 26ab0aed8 fix: link to "get artifacts from logs" was assuming Node ID was equal to Pod Name (#9464)
- [ ] ff4109928 fix: Descendants of suspended nodes need to be removed when retrying workflow (#9440)
- [ ] a09172afa fix: Incorrect alignment for archived workflow. Fixes #9433 (#9439)
- [ ] 04d19435c fix: Properly reset suspended and skipped nodes when retrying (#9422)
- [ ] 3ddbb5e00 fix: Only validate manifests for certain resource actions. Fixes #9418 (#9419)
- [ ] a91e0041c fix: Workflow level http template hook status update. Fixes #8529 (#8586)
- [ ] 343c29819 fix: Argo waiter: invalid memory address or nil pointer dereference (#9408)
- [ ] 6f19e50a4 fix: Invalid memory address or nil pointer dereference (#9409)
- [ ] 6e8d1629d fix: Artifact panel crashes when viewing artifacts. Fixes #9391 (#9392)
- [ ] aa23a9ec8 fix: Exit handle and Lifecycle hook to access {steps/tasks status} (#9229)
- [ ] 74cdf5d87 fix: improper selfLinks for cluster-scoped resources. Fixes #9320 (#9375)
- [ ] f53d4834a fix: Panic on nill pointer when running a workflow with restricted parallelism (#9385)
- [ ] c756291f7 fix: removed error check which prevented deleting successful artGC wfs. (#9383)
- [ ] 65670a402 fix: Fix blank workflow details page after workflow submission (#9377)
- [ ] 12466b7c9 fix: Retry for http timeout error. Fixes #9271 (#9335)
- [ ] fd08b0339 fix: ArtifactGC e2e test was looking for the wrong artifact names (#9353)
- [ ] b430180d2 fix: Deleted pods are not tracked correctly when retrying workflow (#9340)
- [ ] 61f252f1d fix: TestWorkflowStepRetry's comment accurately reflects what it does. (#9234)
- [ ] 0d77f5554 fix: Look in correct bucket when downloading artifacts (Template.ArchiveLocation configured) (#9301)
- [ ] 083f3a21a fix: pass correct error obj for azure blob failures (#9276)
- [ ] 0c24ca1ba fix: TestParallel 503 with external url (#9265)
- [ ] be6ba4f77 fix: add ServiceUnavailable to s3 transient errors list Fixes #9248 (#9249)
- [ ] 15fdf4903 fix: line return in devcontainer host file (#9204)
- [ ] d5d4628a3 fix: Set namespace to user namespace obtained from /userinfo service (#9191)
- [ ] 573fe98ff fix: remove unused argument which is triggering in lint (needed for PRs to pass CI) (#9186)
- [ ] 0f1d1d9b7 fix: support RemainingItemCount in archivedWrokflow (#9118)
- [ ] aea581e02 fix: Incorrect link to workflows list with the same author (#9173)
- [ ] 877f36f37 fix: Workflow details accessing undefined templateRef. Fixes #9167 (#9168)
- [ ] 42729ff75 fix: Workflow retry should also reset the selected nodes (#9156)
- [ ] 56d0c664a fix: Do not error when getting log artifacts from GCS. Fixes #8746 (#9155)
- [ ] 2b92b1aef fix: Fixed swagger error. Fixes #8922 (#9078)
- [ ] 61211f9db fix: Add workflow failures before hooks run. Fixes #8882 (#9009)
- [ ] f5f1a3438 fix: sync lock should be released only if we're retrying (#9063)
- [ ] 89f3433bf fix: workflow.status is now set properly in metrics. Fixes #8895 (#8939)
- [ ] 62287487a fix: Treat 'connection reset by peer' as a transient network error. Fixes #9013 (#9017)
- [ ] 416fce705 fix: Fork sub-process. Fixes #8454 (#8906)
- [ ] 750c4e1f6 fix: Only signal running containers, ignore failures. (#8909)
- [ ] ede1a39e7 fix: workflowMetadata needs to be loaded into globalParams in both ArgoServer and Controller (#8907)
- [ ] 7dacb5bca fix: Fixed Swagger error. Fixes #8830 (#8886)
- [ ] bc0100346 fix: Change to distroless. Fixes #8805 (#8806)
- [ ] 39fbdb2a5 fix: fix a command in the quick-start page (#8782)
- [ ] 178bbbc31 fix: Temporarily fix CI build. Fixes #8757. (#8758)
- [ ] aa366db34 fix: remove list and watch on secrets. Fixes #8534 (#8555)
- [ ] 342abcd6d fix: mkdocs uses 4space indent for nested list (#8740)
- [ ] b3bf327a0 fix: Fix the resursive example to call the coinflip template (#8696)
- [ ] 72d3f32e5 fix: update go-color path/version (#8707)
- [ ] 92b3ef27a fix: upgrade moment from 2.29.2 to 2.29.3 (#8679)
- [ ] 859ebe99f fix: Terminate, rather than delete, deadlined pods. Fixes #8545 (#8620)
- [ ] 3fdf30d9f fix: Enhance artifact visualization. Fixes #8619 (#8655)
- [ ] 16fef4e54 fix: enable `ARGO_REMOVE_PVC_PROTECTION_FINALIZER` by default. Fixes #8592 (#8661)
- [ ] ed351ff08 fix: ArtifactGC moved from Template to Artifact. Fixes #8556. (#8581)
- [ ] 974031570 fix: Polish artifact visualisation. Fixes #7743 (#8552)
- [ ] 98dd898be fix: Correct CSP. Fixes #8560 (#8579)
- [ ] 5b8638fcb fix: modified `SearchArtifact` to return `ArtifactSearchResults`. Fixes #8543 (#8557)
- [ ] ecd91b1c4 fix: added json tag to ArtifactGCStrategies (#8523)
- [ ] f223bb8a3 fix: ArtifactGCOnWorkflowDeletion typo quick fix (#8519)
- [ ] 8c0a957c3 fix: Fix bug in entrypoint lookup (#8453)
- [ ] d47081fb4 fix: upgrade react-moment from 1.0.0 to 1.1.1 (#8389)
- [ ] 010e359e4 fix: upgrade react-datepicker from 2.14.1 to 2.16.0 (#8388)
- [ ] 0c9d88b44 fix: upgrade prop-types from 15.7.2 to 15.8.1 (#8387)
- [ ] 2d91646aa fix: upgrade js-yaml from 3.13.1 to 3.14.1 (#8374)
- [ ] 54eaed060 fix: upgrade cron-parser from 2.16.3 to 2.18.0 (#8373)
- [ ] e9de085d6 fix: Erratum in docs. Fixes #8342 (#8359)
- [ ] a3d1d07e1 fix: upgrade react-chartjs-2 from 2.10.0 to 2.11.2 (#8357)
- [ ] b199cb947 fix: upgrade history from 4.7.2 to 4.10.1 (#8356)
- [ ] e40521556 fix: upgrade multiple dependencies with Snyk (#8355)
- [ ] 8c893bd13 fix: upgrade com.google.code.gson:gson from 2.8.9 to 2.9.0 (#8354)
- [ ] ae3881525 fix: examples/README.md: overriten => overridden (#8351)
- [ ] ab21eed52 fix: upgrade io.swagger:swagger-annotations from 1.6.2 to 1.6.5 (#8335)
- [ ] f708528fb fix: upgrade react-monaco-editor from 0.36.0 to 0.47.0 (#8339)
- [ ] 3c35bd2f5 fix: upgrade cronstrue from 1.109.0 to 1.125.0 (#8338)
- [ ] 7ee17ddb7 fix: upgrade com.squareup.okhttp3:logging-interceptor from 4.9.1 to 4.9.3 (#8336)
- [ ] aa9ff17d5 fix: Remove path traversal CWE-23 (#8331)

**Comment by JPZ13** [comment]
@sarabala1979 - can we add https://github.com/argoproj/argo-workflows/pull/9959 ?

cc @mostaphaRoudsari @AntoineDao

**Comment by alexec** [comment]
Cherry-picking too many issues to this release will risk introducing new issue. You’ll then become mired in fixes and bugs.

I’d suggest only cherry-picking a small number of issues where your confident the blast radius is limited.

**Comment by crenshaw-dev** [comment]
Very small change that I think deserves to be cherry-picked back: https://github.com/argoproj/argo-workflows/issues/9966

**Comment by terrytangyuan** [comment]
This might be worth cherry picking to address security vulnerabilities: https://github.com/argoproj/argo-workflows/commit/4eb6cb7817d3b0f2dc9eeecb5856ec8bd10e9f98

**Comment by terrytangyuan** [comment]
Regression fix worth considering cherry-picking https://github.com/argoproj/argo-workflows/pull/10047

**Comment by terrytangyuan** [comment]
> Regression fix worth considering cherry-picking #10047

Many users are impacted by this. Please cherry pick this one.

**Comment by terrytangyuan** [comment]
We can close this now.
