### ISSUE TITLE
Release v3.4.6 cherry-pick candidates

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#10747]
Hi community, here's the a list of commits that can potentially go to the v3.4.6 Argo Workflows release that we are preparing. If you have additional commits/issues/PRs that you want to bring attention to the maintainers, please comment on this issue!

## Bug fixes
- [x] 39ff41a32 fix: DB sessions are recreated whenever controller configmap updates. Fixes #10498 (#10734)
- [x] 03f129ca2 fix: Workflow stuck at running when init container failed but wait container did not. Fixes #10717 (#10740)
- [x] be5b157f3 fix: Improve templating diagnostics. Fixes #8311 (#10741)
- [x] 12003cad9 fix: ensure children containers are killed for container sets. Fixes #10491 (#10639)
- [x] 2a9bd6c83 fix: Support v1 PDB in k8s v1.25+. Fixes #10649 (#10712)
- [x] ec856835a fix: PVC in wf.status should be reset when retrying workflow (#10685)
- [x] f7922fb80 fix: ensure error returns before attrs is accessed. Fixes #10691 (#10692)
- [x] 26bad2f6e fix: get configmap data when updating controller config Fixes #10659 (#10660)
- [x] 1acc9668a fix: executor dir perm changed to 755. Fixes #9651 (#10664)
- [x] d536eec36 fix: Fix broken archive UI Fixes #10606 (#10622)
- [x] 781675ddc fix: added logs related to executing commands in the container (#10530)
- [ ] 51ed115a8 fix: panic in offline linter + handling stdin (#10576)
- [x] df5941ea8 fix: Priority don't work in workflow spec. Fixes #10374 (#10483)
- [x] 77da05038 fix: change log severity when artifact is not found (#10561)
- [ ] f918e3a4b fix: Resolve issues with offline linter + add tests (#10559)
- [x] d75e37e8b fix: Correct SIGTERM handling. Fixes #10518 #10337 #10033 #10490 (#10523)
- [ ] a862ea1b8 fix: remove kubectl binary from argoexec (#10550)
- [x] 5c3c3b3a8 fix: exit handler variables don't get resolved correctly. Fixes #10393 (#10449)
- [x] 04a84ee32 fix: evaluated debug env vars value (#10493)
- [x] 08c85000f fix: use env when pod version annotation is missing. Fixes #10237 (#10457)
- [x] de8790cf7 fix: stop writing RawClaim into authorization cookie to reduce cookie size. Fixes #9530, #10153 (#10170)
- [x] ab178bb0b fix: delete PVCs upon onExit error when OnWorkflowCompletion is enabled. Fixes #10408 (#9041 
- [x] https://github.com/argoproj/argo-workflows/pull/10735
- [x] https://github.com/argoproj/argo-workflows/pull/10489

## CI and build fixes that might fix/improve the CI during release:

- [x] f2b17207e ci: Upgrade buildx to v0.10.4 and disable provenance (#10680)
- [x] 0e4c9cbb4 ci: Temporarily disable docs link check to unblock PRs (#10678)
- [x] 1c2b15478 ci: Increase unit test timeout to 10m (#10628)
- [x] 09bb6bbef ci: Remove semantic check that's no longer maintained (#10568)
- [ ] 05e13182b build: Enhance Codespaces (#10599)
- [ ] 951056813 build: Faster repeated image builds (#10616)
- [ ] 496065fe9 build: Skip react-router-dom on dependabot (#10648)
- [x] 07b3811f1 build: Revert to Node 16 LTS (#10615)
- [x] f95e84d2a build: Upgrade to Node 19 to fix release build (#10574)

**Comment by tooptoop4** [comment]
@terrytangyuan https://github.com/argoproj/argo-workflows/pull/9058 is also important

**Comment by sarabala1979** [comment]
Thanks, @terrytangyuan for creating this release issue.  We will schedule 3.4.6 on Friday.

**Comment by terrytangyuan** [comment]
> Thanks, @terrytangyuan for creating this release issue. We will schedule 3.4.6 on Friday.

Sounds good. I can follow [the release instructions](https://github.com/argoproj/argo-workflows/blob/master/docs/releasing.md) and start cherry-picking the commits to [release-3.4 branch](https://github.com/argoproj/argo-workflows/tree/release-3.4). Is that okay? Is there anything else I should pay attention to during the process? @sarabala1979 @alexec

**Comment by caelan-io** [comment]
yeah, #9058 isn't quite ready. 1-2 hairy problems to resolve there. @rohankmr414 will post once it's ready to merge.

**Comment by terrytangyuan** [comment]
> we can take entire master(all fixes) to current v3.4.6. I think there won't be any breaking changes
I don't think we should do that. There are so many dependabot upgrades that we haven't tested thoroughly and can potentially break something. There are some new features as well, which should not be included in a patch release.

**Comment by terrytangyuan** [comment]
Yes, all fixes are listed in the issue description. I'll tag a release on Friday.

Please feel free to comment if there are any additional fixes that you'd like to bring into this release.

**Comment by terrytangyuan** [comment]
This needs to be included since we copy ssh_known_hosts in our Dockerfiles:
* https://github.com/argoproj/argo-workflows/pull/10779

**Comment by tico24** [comment]
We'd like to get #10745 in please @terrytangyuan.

**Comment by terrytangyuan** [comment]
> We'd like to get #10745 in please @terrytangyuan.

We only cherry-pick fixes, not features, into patch releases.

**Comment by terrytangyuan** [comment]
The release branch is ready (note that certain commits are not cherry-picked, either unnecessary or due to too many conflicts to resolve). It passed CI checks as well as [a dry-run for release](https://github.com/argoproj/argo-workflows/actions/runs/4565540307). 

https://github.com/argoproj/argo-workflows/tree/release-3.4

I'll create a tag tomorrow to kick off the actual release process.

**Comment by tooptoop4** [comment]
> yeah, #9058 isn't quite ready. 1-2 hairy problems to resolve there. @rohankmr414 will post once it's ready to merge.

@caelan-io any update on this?
