### ISSUE TITLE
Release v3.4.8 cherry-pick candidates

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#11118]
Bug fixes:

- [x] 1e4a376ab fix: Fixed path separator in .tgz output artifacts created on windows. Fixes #10562 (#11097)
- [x] 9a2bb5e80 fix: Disable unreliable test (#11105)
- [x] 901549f1f fix: allow azure blobs to not exist when deleting (#11070)
- [x] 019705eeb fix: Update Bitbucket SSH host key (#11091)
- [x] c1c3a5a1f fix: Parameter overwritten does not work when resubmitting archived workflow (#11086) (#11087)
- [x] e2cc77743 fix: UI crashes when retrying a containerSet workflow. Fixes #11061 (#11073)
- [x] 4225cb8bf fix: ui getPodName should use v2 format by default (fixes #11015) (#11016)
- [x] d4549b3d5 fix: handle panic from type assertion (#11040)
- [x] 5294f354e fix: change pod OwnerReference to clean workflowtaskresults in large-scale scenarios (#11048)
- [x] a5581f83a fix: Upgrade Go to v1.20. Fixes #11023 (#11027)
- [x] 1af85fd4c fix: UI crashes after submitting workflows (#11018)
- [x] f2573ed17 fix: Generate useful error message when no expression on hook (#10919)
- [x] 91f2a4548 fix: Validate label values from workflowMetadata.labels to avoid controller crash (#10995)
- [x] 8dbdc0250 fix: Replace expressions with placeholders in resource manifest template. Fixes #10924 (#10926)
- [x] 8786b46ae fix: unable to connect cluster when AutomountServiceAccountToken is disabled. Fixes #10937 (#10945)
- [x] 1617db0f3 fix: Check AlreadyExists error when creating PDB. Fixes #10942 (#10944)
- [x] b846eeb90 fix: Check file size before saving to artifact storage. Fixes #10902 (#10903)
- [x] 9d28a02ac fix: Incorrect pod name for inline templates. Fixes #10912 (#10921)
- [x] 8766e7a45 fix: Workflow operation error. Fixes #10285 (#10886)
- [x] c8e7fa8a7 fix: Validate label values from workflowMetadata to avoid controller crash. Fixes #10872 (#10892)
- [x] b90485123 fix: tableName is empty if wfc.session != nil (#10887)
- [x] 12f465912 fix: Flaky test about lifecycle hooks. Fixes #10897 (#10898)
- [x] b87bdcfcf fix: Allow script and container image to be set in templateDefault. Fixes #9633 (#10784)

Dependencies updates:

- [x] 7b2a4b1a3 chore(deps): bump github.com/sirupsen/logrus from 1.9.0 to 1.9.2 (#11107)
- [x] 110ed1f3e chore(deps): bump google.golang.org/api from 0.120.0 to 0.122.0 (#11089)
- [x] 6b604450d chore(deps): bump google.golang.org/api from 0.118.0 to 0.120.0 (#11008)
- [x] 7b3d53dbc chore(deps): bump cronstrue from 2.26.0 to 2.27.0 in /ui (#11078)
- [x] 5a81dd225 chore(deps): bump golang.org/x/crypto from 0.8.0 to 0.9.0 (#11068)
- [x] 8c6982264 chore(deps): bump golang.org/x/oauth2 from 0.7.0 to 0.8.0 (#11058)
- [x] bd89a776b chore(deps): bump golang.org/x/sync from 0.1.0 to 0.2.0 (#11041)
- [x] b0e343b2d chore(deps): bump github.com/prometheus/client_golang from 1.15.0 to 1.15.1 (#11029)
- [x] 1e22f06ca chore(deps): bump golang.org/x/term from 0.7.0 to 0.8.0 (#11044)
- [x] 9aa8903de chore(deps): bump github.com/klauspost/pgzip from 1.2.5 to 1.2.6 (#11045)
- [x] 8865d5433 chore(deps): bump dependabot/fetch-metadata from 1.3.6 to 1.4.0 (#10964)
- [x] 09d48ef20 chore(deps): bump google.golang.org/api from 0.117.0 to 0.118.0 (#10933)
- [x] c0565d62e chore(deps): bump github.com/aliyun/aliyun-oss-go-sdk from 2.2.6+incompatible to 2.2.7+incompatible (#10753)
- [x] 819cbc9b4 chore(deps): bump google.golang.org/api from 0.114.0 to 0.117.0 (#10878)
- [x] 694cec0a4 chore(deps): bump github.com/minio/minio-go/v7 from 7.0.51 to 7.0.52 (#10917)
- [x] afca5e3e5 chore(deps): bump github.com/prometheus/client_golang from 1.14.0 to 1.15.0 (#10916)
- [x] 2edf2cf17 chore(deps): bump golang.org/x/oauth2 from 0.6.0 to 0.7.0 (#10860)
- [x] d2bb05261 chore(deps): bump github.com/minio/minio-go/v7 from 7.0.50 to 7.0.51 (#10877)
- [x] 610e9a729 chore(deps): bump golang.org/x/crypto from 0.7.0 to 0.8.0 (#10856)
- [x] dcf66171c chore(deps): bump cronstrue from 2.24.0 to 2.26.0 in /ui (#10855)
- [x] e8433f40d chore(deps): bump peter-evans/create-pull-request from 4 to 5 (#10854)

**Comment by tooptoop4** [comment]
@terrytangyuan can https://github.com/argoproj/argo-workflows/pull/10474/files be included?

**Comment by terrytangyuan** [comment]
> @terrytangyuan can https://github.com/argoproj/argo-workflows/pull/10474/files be included?

Sure

**Comment by terrytangyuan** [comment]
WIP release: branch: https://github.com/argoproj/argo-workflows/tree/release-3.4.8

**Comment by terrytangyuan** [comment]
Codegen failed. Might need to cherry-pick this one as well https://github.com/argoproj/argo-workflows/pull/10984

**Comment by jmeridth** [comment]
@terrytangyuan could this (https://github.com/argoproj/argo-workflows/pull/11132) get merged and included? Might be too late

**Comment by terrytangyuan** [comment]
> @terrytangyuan could this (#11132) get merged and included? Might be too late

We only merge fixes and dependency upgrades in patch releases.

**Comment by terrytangyuan** [comment]
v3.4.8 release tag has been pushed: https://github.com/argoproj/argo-workflows/releases/tag/v3.4.8

**Comment by terrytangyuan** [comment]
See https://github.com/argoproj/argo-workflows/blob/master/docs/releases.md

**Comment by terrytangyuan** [comment]
Released
