### ISSUE TITLE
Release v3.4.9 cherry-pick candidates

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#11380]
Please check the ones we want to cherry-pick.

Bug fixes:

- [ ] 97b6fa844 fix: Modify broken ui by archived col (#11366)
- [x] bda532211 fix: Enable the workflow created by a wftmpl to retry after manually stopped (#11355)
- [x] 43d667ed2 fix: Correct limit in controller List API calls. Fixes #11134 (#11343)
- [ ] fdb3ec03f fix: Live workflow takes precedence during merge to correctly display in the UI (#11336)
- [x] a10139ad3 fix: Add ^ to semver version (#11310)
- [x] 4ca470b10 fix: Pin semver to 7.5.2. Fixes SNYK-JS-SEMVER-3247795 (#11306)
- [x] e5dd8648f fix: use unformatted templateName as args to PodName. Fixes #11250 (#11251)
- [x] 609539df4 fix: Azure input artifact support optional. Fixes #11179 (#11235)
- [x] 7f155e47c fix: Argo DB init conflict when deploy workflow-controller with multiple replicas #11177 (#11178)
- [x] 451d27509 fix: fix bugs in throttler and syncManager initialization in WorkflowController (#11210)
- [x] aa2b66a5b fix: do not delete pvc when max parallelism has been reached. Fixes #11119 (#11138)
- [x] b89c98bff fix: Upgrade windows container to ltsc2022 (#11246)
- [x] 0fd42276b fix: Update Bitbucket SSH host key (#11245)
- [x] 53111f885 fix: Support inputs for inline steps templates (#11074)
- [x] 0ad4169c2 fix: Allow hooks to be specified in workflowDefaults (#11214)
- [x] 245af38b1 fix: untar empty directories (#11240)
- [x] abc4e8fa8 fix: Treat "connection refused" error as a transient network error. (#11237)
- [ ] ac9161ce1 fix: Workflow list page crashes for workflow rows without labels (#11195)
- [x] fa95f8d02 fix: prevent memoization accessing wrong config-maps (#11225)
- [x] d91b72172 fix: Remove 401 Unauthorized when customClaimGroup retrieval fails, Fixes #11032 (#11033)
- [x] 0c5a6dd4b fix: check hooked nodes in executeWfLifeCycleHook and executeTmplLifeCycleHook (#11113, #11117) (#11176)
- [ ] 2016078c0 fix: add space to fix release action issue (#11160)
- [x] 58793a8ca fix: Make devcontainer able to pre-commit (#11153)
- [x] 04d527c7d fix: Setup /etc/hosts for running inside devcontainer (#11104)

Chores:

- [ ] 37f483d1c chore(deps): bump github.com/minio/minio-go/v7 from 7.0.59 to 7.0.60 (#11363)
- [ ] 779922a90 chore(deps): bump github.com/antonmedv/expr from 1.12.5 to 1.12.6 (#11365)
- [ ] e08db70fd chore(deps): bump react-datepicker from 4.15.0 to 4.16.0 in /ui (#11362)
- [ ] 15a83651a chore(deps): bump cronstrue from 2.27.0 to 2.28.0 in /ui (#11329)
- [ ] 526458449 chore(deps): bump golang.org/x/oauth2 from 0.9.0 to 0.10.0 (#11317)
- [ ] d0b9b03a7 chore(deps): bump google.golang.org/api from 0.129.0 to 0.130.0 (#11318)
- [ ] f4e9ae7fd chore(deps): bump github.com/stretchr/testify from 1.8.2 to 1.8.4 (#11319)
- [ ] 90fe330de chore(deps): bump google.golang.org/api from 0.128.0 to 0.129.0 (#11286)
- [ ] d815c5582 chore(deps): bump react-datepicker from 4.14.1 to 4.15.0 in /ui (#11289)
- [ ] 75e462af2 chore(deps): bump dependabot/fetch-metadata from 1.5.1 to 1.6.0 (#11287)
- [ ] 6dfe5d49e chore(deps): bump github.com/minio/minio-go/v7 from 7.0.58 to 7.0.59 (#11285)
- [ ] 476eca40f chore(deps): bump cloud.google.com/go/storage from 1.30.1 to 1.31.0 (#11284)
- [ ] f180335b3 chore(deps): bump react-datepicker from 4.14.0 to 4.14.1 in /ui (#11263)
- [x] 40f4d1d2e chore(deps): bump golang.org/x/sync from 0.2.0 to 0.3.0 (#11262)
- [ ] 8089f41bd chore(deps): bump github.com/minio/minio-go/v7 from 7.0.56 to 7.0.58 (#11261)
- [ ] d2091a710 chore(deps): bump react-datepicker from 4.12.0 to 4.14.0 in /ui (#11231)
- [x] da89c2f96 chore(deps): bump golang.org/x/oauth2 from 0.8.0 to 0.9.0 (#11228)
- [ ] 572641f9c chore(deps): bump github.com/prometheus/client_golang from 1.15.1 to 1.16.0 (#11227)
- [x] 424e2238d chore(deps): bump google.golang.org/api from 0.124.0 to 0.128.0 (#11229)
- [ ] d3a6e66a9 chore(deps): bump github.com/sirupsen/logrus from 1.9.2 to 1.9.3 (#11200)
- [ ] f3c948a04 chore(deps): bump github.com/itchyny/gojq from 0.12.12 to 0.12.13 (#11170)
- [ ] 760299ff9 chore(deps): bump github.com/minio/minio-go/v7 from 7.0.55 to 7.0.56 (#11169)
- [ ] b239c615e chore(deps): bump github.com/go-sql-driver/mysql from 1.7.0 to 1.7.1 (#11007)
- [x] 1a51e4fd1 chore(deps): bump google.golang.org/api from 0.122.0 to 0.124.0 (#11142)
- [ ] afde7ef41 chore(deps): bump react-datepicker from 4.11.0 to 4.12.0 in /ui (#11147)
- [ ] 6923cc837 chore(deps): bump github.com/minio/minio-go/v7 from 7.0.52 to 7.0.55 (#11145)
- [ ] 222540c29 chore(deps): bump dependabot/fetch-metadata from 1.4.0 to 1.5.1 (#11141)

Build and CI:

- [x] 8de568b1e build: use k8s 1.27 in devcontainer to match CI (#11352)
- [ ] ce87d74a6 build: Remove personal token for docs publishing (#11345)
- [ ] bf6ce03af build: use only relevant files in build (#11189)
- [ ] ba82fd879 build: devcontainer improvements and documentation (#11162)
- [ ] c17fb81fb ci: Grant write permission to docs workflow (#11348)
- [ ] a1fc40405 ci: Switch to use “with” in gh-pages.yaml (#11347)
- [ ] 1e0bb4218 ci: Fix broken codgen build (#11311)
- [ ] 9deb51f72 ci: Disable flaky link check (#11305)
- [ ] 539a51e9e ci: add PR title conventional commits checker (#10981)

Community requested:
- [x] https://github.com/argoproj/argo-workflows/pull/10938

**Comment by ehellmann-nydig** [comment]
any way we can get https://github.com/argoproj/argo-workflows/pull/11164 into this as well?

**Comment by toyamagu-2021** [comment]
We should NOT include #11366 because it depends on `isArchivedWorkflow` which is introduced in unified archived workflows.
FYI: blame
https://github.com/argoproj/argo-workflows/blame/15f118b8c3fcf9a9c9862f44cbf943b4f4a1ad79/ui/src/models/workflows.ts#L544

**Comment by rbushri** [comment]
can you include  #11237 ?

**Comment by tooptoop4** [comment]
pls include https://github.com/argoproj/argo-workflows/pull/10938

**Comment by terrytangyuan** [comment]
@rbushri @tooptoop4 Thanks. Added to the list.

**Comment by terrytangyuan** [comment]
More items:

- [ ] https://github.com/argoproj/argo-workflows/pull/11394

**Comment by terrytangyuan** [comment]
Working branch: https://github.com/argoproj/argo-workflows/commits/release-3.4.9

**Comment by terrytangyuan** [comment]
Released https://github.com/argoproj/argo-workflows/releases/tag/v3.4.9
