### ISSUE TITLE
Release v3.4.10 cherry-pick candidates

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#11552]
Please check the ones we want to cherry-pick.

From discussions:

- [x] https://github.com/argoproj/argo-workflows/pull/11553
- [x] https://github.com/argoproj/argo-workflows/pull/11368
- [x] https://github.com/argoproj/argo-workflows/pull/11554
- [x] https://github.com/argoproj/argo-workflows/pull/11200
- [x] https://github.com/argoproj/argo-workflows/pull/11493
- [x] https://github.com/argoproj/argo-workflows/pull/11426

Bug fixes:

- [x] 68b7ea6f7 fix: Upgrade hdfs and rpc module #10030 (#11543)
- [x] 1709f9630 fix: workflow-controller-configmap/parallelism setting not working in… (#11546)
- [x] 6e50cb06c fix: Switch to use kong/httpbin to support arm64. Fixes #10427 (#11533)
- [x] b2e2106d3 fix: Added vulnerability fixes for gorestlful gopkg & OS vulnerabilities in golang:1.20-alpine3.16 (#11538)
- [x] 4a3cb0e98 fix: Flaky test about lifecycle hooks (#11534)
- [x] 143d0f504 fix: Fixed memoization is unchecked after mutex synchronization. Fixes #11219 (#11456)
- [x] 545bf3803 fix: Ensure target Workflow hooks not nil (#11521) (#11535)
- [x] 9c7724770 fix: azure hasLocation incorporates endpoint. Fixes #11512 (#11513)
- [x] b26f5b80e fix: Support `OOMKilled` with container-set. Fixes #10063 (#11484)
- [x] cb1713d01 fix: valueFrom in template parameter should be overridable. Fixes 10182 (#10281)
- [x] 61a4ac45c fix: Ignore failed read of exit code. Fixes #11490 (#11496)
- [x] f6c6dd7c4 fix: Fixed UI workflowDrawer information link broken. Fixes #11494 (#11495)
- [x] 1f6b19f3a fix: add guard against NodeStatus. Fixes #11102 (#11451)
- [x] ce9e50cd8 fix: Datepicker Style Malfunction Issue. Fixes #11476 (#11480)
- [ ] f8a34a3b5 fix: Devcontainer resets /etc/hosts (#11439) (#11440)
- [x] 7310e9c41 fix: UI toolbar sticky (#11444)
- [ ] c6a2a4f15 fix: Apply the creator labels about the user who resubmitted a Workflow (#11415)
- [ ] f5d41f8c9 fix: make archived logs more human friendly in UI (#11420)
- [ ] 5cb75d91a fix: add query string to workflow detail page(#11371) (#11373)
- [ ] 5b31ca18b fix: persist archived workflows with `Persisted` label (#11367) (#11413)
- [ ] 97b6fa844 fix: Modify broken ui by archived col (#11366)
- [ ] fdb3ec03f fix: Live workflow takes precedence during merge to correctly display in the UI (#11336)
- [x] 137d5f8cc fix(controller): Enable dummy metrics server on non-leader workflow controller (#11295)
- [x] 6f1cb4843 fix(windows): Propagate correct numerical exitCode under Windows (Fixes #11271) (#11276)
- [ ] ac9161ce1 fix: Workflow list page crashes for workflow rows without labels (#11195)
- [ ] 2016078c0 fix: add space to fix release action issue (#11160)
- [x] 48097ea0b fix(controller): Drop Checking daemoned children without nodeID (Fixes #10960) (#10974)

Build:

- [x] d8764646e build: upgrade to use nodev20 (#11410)
- [ ] 589a4b701 build: pin versions of NPM global deps in `Makefile` (#11425)
- [ ] ce87d74a6 build: Remove personal token for docs publishing (#11345)
- [ ] bf6ce03af build: use only relevant files in build (#11189)
- [ ] ba82fd879 build: devcontainer improvements and documentation (#11162)

CI:

- [x] 2d20532a8 ci: fix `snyk.yaml` and `release.yaml` for Node v20 (#11461)
- [ ] 6905cf36e ci: Bump E2E_WAIT_TIMEOUT to avoid E2E test failures in CI (#11392)
- [ ] c17fb81fb ci: Grant write permission to docs workflow (#11348)
- [ ] a1fc40405 ci: Switch to use “with” in gh-pages.yaml (#11347)
- [ ] 1e0bb4218 ci: Fix broken codgen build (#11311)
- [ ] 9deb51f72 ci: Disable flaky link check (#11305)
- [ ] 539a51e9e ci: add PR title conventional commits checker (#10981)

**Comment by ajoskowski** [comment]
We would like to get a fix for #11330 because it breaks our production pipelines.

**Comment by terrytangyuan** [comment]
> Would want to get a fix in for #11542 (et al) to make sure that all regressions resulting from #11178 are resolved

- [ ] https://github.com/argoproj/argo-workflows/pull/11553

**Comment by terrytangyuan** [comment]
> We would like to get a fix for #11330 because it breaks our production pipelines.

Let's ping on that issue to see if anyone is interested in contributing. Not a blocker for this release though since we have more important fixes to get in.

**Comment by caelan-io** [comment]
Let's get this one in the patch release as well: https://github.com/argoproj/argo-workflows/pull/11493

**Comment by advithVashist** [comment]
Would it be possible to get this fix in? https://github.com/argoproj/argo-workflows/pull/10927

**Comment by terrytangyuan** [comment]
> Would it be possible to get this fix in? #10927

@advithVashist That's a feature so no. We want to avoid new bugs.

**Comment by advithVashist** [comment]
> > Would it be possible to get this fix in? #10927
> 
> @advithVashist That's a feature so no. We want to avoid new bugs.

Got it, thanks :)

**Comment by jaen** [comment]
Any chance of getting #11456 in? Would be nice to not have to manually patch this and I'm not sure if the check box being unchecked mean it's not getting in.

**Comment by terrytangyuan** [comment]
Sure

**Comment by terrytangyuan** [comment]
Failed to cherry-pick due to conflicts:

- [ ] 68b7ea6 fix: Upgrade hdfs and rpc module 
- [ ] 143d0f5 fix: Fixed memoization is unchecked after mutex synchronization.
- [ ] 61a4ac4 fix: Ignore failed read of exit code.
- [ ] b26f5b8 fix: Support OOMKilled with container-set.
- [ ] 1f6b19f fix: add guard against NodeStatus.


Waiting to be merged:

- [ ] fix: always fail dag when shutdown is enabled. Fixes #11452 #11493

**Comment by terrytangyuan** [comment]
> I'm not sure if the check box being unchecked mean it's not getting in.

Yes unchecked ones are not getting included in this release. They are either not cherry-pickable or are bug fixes for new features that did not exist in v3.4 yet.

**Comment by terrytangyuan** [comment]
These cannot be cherry-picked since the v3.4.10 release branch diverges from master branch too much. If you'd like to get them into this release, please submit a PR to the release branch before next Tuesday. https://github.com/argoproj/argo-workflows/tree/release-3.4.10

143d0f5 fix: Fixed memoization is unchecked after mutex synchronization. @shmruin 
61a4ac4 fix: Ignore failed read of exit code. @alexec 
b26f5b8 fix: Support OOMKilled with container-set. @alexec
1f6b19f fix: add guard against NodeStatus. @isubasinghe

**Comment by agilgur5** [comment]
#11426 might be good to get into a patch as well. I believe it's still failing on a test flake

**Comment by jaen** [comment]
@shmruin would you be willing to make a PR for this? The conflict seems rather simple to solve as far as I can tell (add `, nil` and revert the use of `Set`):
https://github.com/jaen/argo-workflows/commit/cbcb5a3e34202108d42dfa2aa8cc5398893b91c4

Sorry for asking, but I don't have a good way to test this right now.

**Comment by shmruin** [comment]
@jaen yes, I am willing to. I think I can try this on tuesday.

**Comment by terrytangyuan** [comment]
> #11426 might be good to get into a patch as well. I believe it's still failing on a test flake (unfortunately being a Member does not give CI retry permissions 😕 )

Done

**Comment by shmruin** [comment]
@terrytangyuan @jaen I made a PR to `realease-3.4.10` to apply the thing below as you mentioned. you can see in #11578. I tested in UI and with code again, but if there's any problem, please tell me. thanks.

https://github.com/argoproj/argo-workflows/commit/143d0f504c9382976b5a25a36b108b7f5e24ab37 fix: Fixed memoization is unchecked after mutex synchronization.

**Comment by terrytangyuan** [comment]
Thanks. Since no one else has responded regarding other commits, I'll trigger the release process soon.

**Comment by terrytangyuan** [comment]
Tagged https://github.com/argoproj/argo-workflows/releases/tag/v3.4.10
