### ISSUE TITLE
Release v3.5 patch releases discussion

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#11997]
This issue tracks commits for 3.5 patch releases.

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/issues/12025 needs to be fixed for this

**Comment by terrytangyuan** [comment]
I am thinking about releasing v3.5.1 next week. The most important fix would be https://github.com/argoproj/argo-workflows/pull/12068 since it blocks people from upgrading to v3.5.

**Comment by terrytangyuan** [comment]
Security fix: https://github.com/argoproj/argo-workflows/pull/12111

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/pull/12130

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/releases/tag/v3.5.1

**Comment by agilgur5** [comment]
Would be good to get my code-splitting / bundle reductions changes into the next patch release once they're all merged in (#12061, #12097, #12150). They are primarily refactors, but they do fix long wait times for the UI on slow networks or slow devices as described in #11970

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/pull/12133

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/pull/12203

**Comment by terrytangyuan** [comment]
TODO: @terrytangyuan to post a list of commits to cherry-pick here

**Comment by terrytangyuan** [comment]
The plan is to cherry-pick the following commits (unless there's conflict)

Fixes:

- [ ] 9eadf2def fix: leak stream (#12193)
- [ ] 206c901c6 fix: Fix for missing steps in the UI (#12203)
- [ ] 939ce4029 fix(server): allow passing loglevels as env vars to Server (#12145)
- [ ] 222d53cdf fix: Resource version incorrectly overridden for wfInformer list requests. Fixes #11948 (#12133)
- [ ] f95a5fc6b fix: retry S3 on RequestError. Fixes #9914 (#12191)
- [ ] 6805c9132 fix: ArtifactGC Fails for Stopped Workflows. Fixes #11879 (#11947)
- [ ] 873bacbaf fix(ui): Cost Opt should only apply to live Workflows (#12170)

Chore(deps):

- [ ] 75d7eb190 chore(deps): bump github.com/aliyun/credentials-go from 1.3.1 to 1.3.2 (#12227)
- [ ] 63f53eae9 chore(deps): bump github.com/gorilla/websocket from 1.5.0 to 1.5.1 (#12226)
- [ ] b6590027a chore(deps): bump golang.org/x/term from 0.13.0 to 0.14.0 (#12225)
- [ ] bce96ab6d chore(deps): bump cronstrue from 2.41.0 to 2.44.0 in /ui (#12224)
- [ ] c95d9a1ba chore(deps): bump golang.org/x/sync from 0.4.0 to 0.5.0 (#12185)
- [ ] 877a2e737 chore(deps): bump github.com/go-jose/go-jose/v3 from 3.0.0 to 3.0.1 (#12184)
- [ ] 460b30a5c chore(deps): bump golang.org/x/time from 0.3.0 to 0.4.0 (#12186)
- [ ] a47e46208 chore(deps): bump github.com/aliyun/aliyun-oss-go-sdk from 2.2.9+incompatible to 3.0.1+incompatible (#12140)
- [ ] 69b47b957 chore(deps): bump monaco-editor from 0.43.0 to 0.44.0 in /ui (#12142)
- [ ] 664569bb1 chore(deps): bump cronstrue from 2.32.0 to 2.41.0 in /ui (#12144)
- [ ] 77173a57f chore(deps): bump github.com/creack/pty from 1.1.18 to 1.1.20 (#12139)
- [ ] 789c60888 chore(deps): bump cloud.google.com/go/storage from 1.33.0 to 1.34.1 (#12138)
- [ ] 2f0094c56 chore(deps): bump react-datepicker and @types/react-datepicker in /ui (#12096)
- [ ] 8f0910842 chore(deps): upgrade `swagger-ui-react` to latest 4.x.x (#12058)
- [ ] 5cc8484a5 chore(deps): bump google.golang.org/api from 0.147.0 to 0.148.0 (#12051)
- [ ] 7a25c05dc chore(deps): bump github.com/coreos/go-oidc/v3 from 3.5.0 to 3.7.0 (#12050)
- [ ] 35f7208ec chore(deps): automatically `audit fix` UI deps (#12036)
- [ ] 32d31ab16 chore(deps): bump google.golang.org/api from 0.143.0 to 0.147.0 (#12001)

**Comment by Joibel** [comment]
Could you add https://github.com/argoproj/argo-workflows/pull/12215 and https://github.com/argoproj/argo-workflows/pull/12214 to 3.5.2 please @terrytangyuan, just to ensure those tests are happening.

**Comment by agilgur5** [comment]
Could we add the UI code-splitting PRs as I mentioned [above](https://github.com/argoproj/argo-workflows/issues/11997#issuecomment-1793638660)? I don't think they have a big impact to that many users, so I'm fine with it going in 3.5.3 as well if you'd prefer to keep this release smaller/more stable.

Otherwise commit list LGTM ✅

**Comment by terrytangyuan** [comment]
@Joibel Good idea.

@agilgur5 I'd like to focus on fixes and chore(deps) in patch releases.

**Comment by agilgur5** [comment]
As I wrote [above](https://github.com/argoproj/argo-workflows/issues/11997#issuecomment-1793638660):

> They are primarily refactors in content, but their primary intent is to fix long wait times for the UI on slow networks or slow devices as described in https://github.com/argoproj/argo-workflows/discussions/11970

I would definitely not call them features at least

**Comment by agilgur5** [comment]
We probably want #12245 as well

**Comment by terrytangyuan** [comment]
> I would definitely not call them features at least

Sounds good. In the future, let's make sure the PR titles can tell us that.

**Comment by agilgur5** [comment]
Yea each PR individually is more of a refactor, but as a whole they are a fix -- in other words, a bunch of refactors that _enable_ a fix.
[Naming things](https://martinfowler.com/bliki/TwoHardThings.html) is a hard problem; as always feel free to change the titles if that makes things easier for you to release

**Comment by terrytangyuan** [comment]
Working branch https://github.com/argoproj/argo-workflows/tree/release-3.5.2

**Comment by terrytangyuan** [comment]
v3.5.2 tagged https://github.com/argoproj/argo-workflows/releases/tag/v3.5.2

**Comment by juliev0** [comment]
Request to include https://github.com/argoproj/argo-workflows/pull/12353

**Comment by terrytangyuan** [comment]
This needs to be included https://github.com/argoproj/argo-workflows/pull/12470

**Comment by agilgur5** [comment]
#12421 is also a fix for a 3.5.0 feature

**Comment by sarabala1979** [comment]
Hi 
I am working on release v3.5.3 which includes below PRs
https://github.com/argoproj/argo-workflows/pull/12421
https://github.com/argoproj/argo-workflows/pull/12470
https://github.com/argoproj/argo-workflows/pull/12353

**Comment by agilgur5** [comment]
Updating here that 3.5.3 was [released](https://github.com/argoproj/argo-workflows/releases/tag/v3.5.3)

**Comment by agilgur5** [comment]
#12397 for the next release

**Comment by terrytangyuan** [comment]
We might need another patch ASAP https://github.com/argoproj/argo-workflows/pull/12515

**Comment by terrytangyuan** [comment]
Released https://github.com/argoproj/argo-workflows/releases/tag/v3.5.4

**Comment by agilgur5** [comment]
Another vuln #12556 (which is actually from a new `go-git` dep after #12515)

**Comment by agilgur5** [comment]
#12562 fixes a regression in v3.5.0

**Comment by juliev0** [comment]
[12559](https://github.com/argoproj/argo-workflows/pull/12559) fixes a regression found in 3.5.3

**Comment by agilgur5** [comment]
#12573 fixes an `expr` / templating regression

**Comment by agilgur5** [comment]
> #12397 for the next release

This didn't make it into 3.5.4, so still needs a release

**Comment by sarabala1979** [comment]
We released v3.5.4 two weeks before. so if there is no urgent patch, patch can be schedule in 4 weeks. we Can schedule v3.5.5 on next two weeks(Feb 15)

**Comment by agilgur5** [comment]
#12492 would be good for any patch release

**Comment by tczhao** [comment]
I would like to include https://github.com/argoproj/argo-workflows/pull/12638 in the next patch release.
This fixes the issue where a pod is unable to initialise when the artifact path has subdir and is mounted using volumeMount

**Comment by agilgur5** [comment]
#12622 is a workaround for a (very impactful) k8s 1.27 issue (#11657)

**Comment by agilgur5** [comment]
#12652 adds some missing docs that would be good to have in `release-3.5`

**Comment by agilgur5** [comment]
#12666 fixes a warning and performance issue

**Comment by vermaxik** [comment]
> We released v3.5.4 two weeks before. so if there is no urgent patch, patch can be schedule in 4 weeks. we Can schedule v3.5.5 on next two weeks(Feb 15)

@sarabala1979 We're waiting for the 3.5.5 release, looks like it was shifted, any plans to release this week/next week?

**Comment by terrytangyuan** [comment]
We are trying out release rotation now. See https://github.com/argoproj/argo-workflows/issues/12592 

@isubasinghe is working on the next release

**Comment by agilgur5** [comment]
#12609 fixes a regression dating back to 3.3, so would be good to get into 3.5.x and 3.4.x

**Comment by agilgur5** [comment]
#12681 fixes a possible OOM due to a 3.5 feature

**Comment by tczhao** [comment]
Hi @isubasinghe ,
What is the state of the v3.5.5 release? We would really like to see it this week.

**Comment by agilgur5** [comment]
#12683 fixes a regression from 3.4.7+

**Comment by isubasinghe** [comment]
Good news, it is done now, I want to go over the changes carefully again though. 
I should probably go to sleep soon so I will stop now. 

Should be finished tomorrow evening or by Tuesday evening.

**Comment by agilgur5** [comment]
> I want to go over the changes carefully again though.

Do you want to post a branch or something for others to review?

**Comment by isubasinghe** [comment]
The changes included in patch 3.5.5 are:

**Fixes** 
- [x] a927379f7 fix: find correct retry node when using `templateRef`. Fixes: #12633 (#12683)
- [x] 5c8062e55 fix: Add limit to number of Workflows in CronWorkflow history (#12681)
- [x] 4ad0db97a fix: Patch taskset with subresources to delete completed node status.… (#12620)
- [x] 57a078f8b fix(typo): fix some typo (#12673)
- [x] 030d581d7 fix(ui): `ListWatch` should not _both_ set and depend on `nextOffset` (#12672)
- [x] 23f8c3527 fix(controller): re-allow changing executor `args` (#12609)
- [x] 148252a8a fix(controller): add missing namespace index from workflow informer (#12666)
- [x] 0acb4356d fix: retry node with expression status Running -> Pending (#12637)
- [x] 66680f1c9 fix(build): check for env vars in all dirs (#12652)
- [x] 130417b6c fix(docs): remove `workflow-controller-configmap.yaml` self reference (#12654)
- [x] ae0973aed fix: pass through burst and qps for auth.kubeclient (#12575)
- [x] 5f4b2350b fix: controller option to not watch configmap (#12622)
- [x] 6c8a7157f fix: artifact subdir error when using volumeMount (#12638)
- [x] fbd70aac1 fix: Allow valueFrom in dag arguments parameters. Fixes #11900 (#11902)
- [x] 09edbf76d fix(resources): improve ressource accounting. Fixes #12468 (#12492)
- [x] e771bde9e fix: make the process of patching pods exclusive (#12596)
- [x] 42262690f fix: upgrade expr-lang. Fixes #12037 (#12573)
- [x] 8f2746a98 fix: make sure taskresult completed when mark node succeed when it has outputs (#12537)
- [x] a15587755 fix: Mark resource && data template report-outputs-completed true (#12544)
- [x] 8d27a9f12 fix: make etcd errors transient (#12567)
- [x] af2cacb36 fix(ui): clone the `ListWatch` callback array in `WorkflowsList` (#12562)
- [x] c46986e0d fix: Global Artifact Passing. Fixes #12554 (#12559)
- [x] 1dbc856e5 fix: update minio chart repo (#12552)
- [x] 46c1324dc fix: cache configmap don't create with workflow has retrystrategy. Fixes: #12490 #10426 (#12491)
- [x] 1ab7cd207 fix: add resource quota evaluation timed out to transient (#12536)
- [x] 1202ae473 fix: prevent update race in workflow cache (Fixes #9574) (#12233)
- [x] e20f31226 fix: Fixed mutex with withSequence in http template broken. Fixes #12018 (#12176)
- [x] 3931e59c8 fix: SSO with Jumpcloud "email_verified" field #12257 (#12318)
- [x] b290e518d fix: wrong values are assigned to input parameters of workflowtemplat… (#12412)
- [x] b447951e1 fix: Add missing 'archived' prop for ArtifactPanel component. Fixes #12331 (#12397)
- [x] 44b33fadf fix: merge env bug in workflow-controller-configmap and container. Fixes #12424 (#12426)
- [x] bcf5672ec fix(docs): handle `fields` examples with `md_in_html` (#12465)
- [x] 96f25af05 fix(docs): exclude `docs/requirements.txt` from docs build (#12466)
- [x] 1968436a6 fix(docs): render Mermaid diagrams in docs (#12464)
- [x] d1cae63b9 fix: documentation links (#12446)

**chore(deps)**

- [x] 7d70fe264 chore(deps): upgrade argoproj/pkg version (#12651)
- [x] 873d3de4c chore(deps): fixed medium CVE in github.com/docker/docker v24.0.0+incompatible (#12635)
- [x] baef4856f chore(deps): bump github.com/cloudflare/circl to 1.3.7 to fix GHSA-9763-4f94-gfch (#12556)
- [x] b734b660e chore(deps): upgrade `swagger-ui-react` to v5 (#12540)
- [x] 19c729289 chore(deps): bump google.golang.org/api from 0.155.0 to 0.156.0 (#12507)
- [x] 5dd8002e8 chore(deps): bump golang.org/x/crypto from 0.17.0 to 0.18.0 (#12506)
- [x] 4a9ef2ae8 chore(deps): bump github.com/evanphx/json-patch from 5.7.0+incompatible to 5.8.0+incompatible (#12504)
- [x] 93914261c chore(deps): bump google.golang.org/api from 0.154.0 to 0.155.0 (#12479)
- [x] 6b2d775dd chore(deps): bump golang.org/x/sync from 0.5.0 to 0.6.0 (#12478)
- [x] 563011ace chore(deps): bump golang.org/x/term from 0.15.0 to 0.16.0 (#12477)
- [x] ee890e9ad chore(deps): bump tj-actions/changed-files from 40 to 41 (#12433)
- [x] 7b3d040c3 chore(deps): bump github.com/aliyun/aliyun-oss-go-sdk from 3.0.1+incompatible to 3.0.2+incompatible (#12428)
- [x] 04ebbe9bd chore(deps): bump moment from 2.29.4 to 2.30.1 in /ui (#12431)
- [x] f583400dd chore(deps): bump classnames from 2.3.3 to 2.5.1 in /ui (#12430)
- [x] 87c9be744 chore(deps): bump github.com/spf13/viper from 1.18.1 to 1.18.2 (#12403)
- [x] 54e02126e chore(deps): bump golang.org/x/crypto from 0.16.0 to 0.17.0 (#12405)
- [x] 777efeb27 chore(deps): bump react-datepicker from 4.24.0 to 4.25.0 in /ui (#12410)
- [x] 2f89beb6c chore(deps): bump github.com/go-openapi/jsonreference from 0.20.2 to 0.20.4 (#12404)
- [x] d900f074b chore(deps): bump github.com/coreos/go-oidc/v3 from 3.8.0 to 3.9.0 (#12380)
- [x] 6471bc002 chore(deps): bump github.com/minio/minio-go/v7 from 7.0.65 to 7.0.66 (#12379)
- [x] 255f50367 chore(deps): bump cloud.google.com/go/storage from 1.35.1 to 1.36.0 (#12378)
- [x] 99f49d364 chore(deps): bump google.golang.org/api from 0.153.0 to 0.154.0 (#12377)
- [x] ceaffd419 chore(deps): bump github.com/Azure/azure-sdk-for-go/sdk/azcore from 1.9.0 to 1.9.1 (#12376)
- [x] a9dc033d5 chore(deps): bump google.golang.org/api from 0.152.0 to 0.153.0 (#12348)
- [x] cd5cf92ed chore(deps): bump github.com/spf13/viper from 1.17.0 to 1.18.1 (#12347)
- [x] 975bbc58c chore(deps): bump github.com/coreos/go-oidc/v3 from 3.7.0 to 3.8.0 (#12345)
- [x] b0d170a9e chore(deps): bump golang.org/x/oauth2 from 0.14.0 to 0.15.0 (#12343)
- [x] e26abcd2f chore(deps): bump actions/setup-go from 4 to 5 (#12341)
- [x] 70c906497 chore(deps): bump react-datepicker from 4.23.0 to 4.24.0 in /ui (#12340)
- [x] d310920a6 chore(deps): bump cronstrue from 2.44.0 to 2.47.0 in /ui (#12338)
- [x] 7eee84d34 chore(deps): bump golang.org/x/crypto from 0.15.0 to 0.16.0 (#12292)
- [x] 544ed9069 chore(deps): bump github.com/Azure/azure-sdk-for-go/sdk/azcore from 1.8.0 to 1.9.0 (#12298)
- [x] 1f2de884c chore(deps): bump google.golang.org/api from 0.151.0 to 0.152.0 (#12299)
- [x] aeb1bdda1 chore(deps): bump github.com/creack/pty from 1.1.20 to 1.1.21 (#12312)
- [x] 03a753ed6 chore(deps): bump golang.org/x/term from 0.14.0 to 0.15.0 (#12311)
- [x] 5da4b5ced chore(deps): bump github.com/google/go-containerregistry from 0.16.1 to 0.17.0 (#12296)
- [x] cf870b81c chore(deps): upgrade `prettier` from v1.x to v3+  (#12290)
- [x] 664569bb1 chore(deps): bump cronstrue from 2.32.0 to 2.41.0 in /ui (#12144)

**feat**
- [x] 6abe8a950 feat: Add finalizer to workflow pod to prevent 'pod deleted'. Fixes #8783 Continuing Work of #9058 (#12413)

**Comment by isubasinghe** [comment]
Please help me check the correctness here: https://github.com/isubasinghe/argo-workflows/tree/release-3.5.5

**Comment by tczhao** [comment]
Would it be a good idea to make a PR to v3.5.4 and trigger git actions to make sure all tests pass?

**Comment by isubasinghe** [comment]
I've doubled checked it's fine and CI passes. I don't have the permissions to create a tag however. @terrytangyuan

**Comment by terrytangyuan** [comment]
Can you update the release branch? Once updated, I can also help create a tag: https://github.com/argoproj/argo-workflows/tree/release-3.5

**Comment by agilgur5** [comment]
> The changes included in patch 3.5.5 are:

I did notice that two missing from this list were mentioned above in this issue:  #12556 and #12581

> Please help me check the correctness here: https://github.com/isubasinghe/argo-workflows/tree/release-3.5.5

I checked a few of the individual commits that LGTM / match their counterparts. The notable difference is the reversed order of the commits (that you had mentioned offline due to the `cherry-pick.sh` script).
Also ran a `git diff main release-3.5.5` and and there were only a few things missing outside of features. The vast majority were build, CI, and docs, but some were deps changes and there were a few fixes that seemingly never made it in / were not explicitly listed before. We should try to get some of this in as well.

**Comment by agilgur5** [comment]
> I did notice that two missing from this list were mentioned above in this issue: #12556 and #12581

I added these two:
- [x] baef4856f chore(deps): bump github.com/cloudflare/circl to 1.3.7 to fix GHSA-9763-4f94-gfch (#12556)
- [x] d9caa75 docs: consistently use "> v{version} and after" (#12581)

and another patch that was recently added:
- [x] 9bec11438 fix: make WF global parameters available in retries (#12698)

https://github.com/argoproj/argo-workflows/tree/release-3.5

**Comment by isubasinghe** [comment]
Thanks @agilgur5, I suppose let's ship it

**Comment by terrytangyuan** [comment]
You should be able to create a tag now.

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/releases/tag/v3.5.5

Thanks @agilgur5 and @isubasinghe!

**Comment by z63d** [comment]
Would you consider cherry-picking [argoproj/argo-workflows#12312](https://github.com/argoproj/argo-workflows/pull/12312) into the v3.5 release branch? You can find more details in [argoproj/argo-workflows#12829](https://github.com/argoproj/argo-workflows/issues/12829).

**Comment by agilgur5** [comment]
> Would you consider cherry-picking #12312 into the v3.5 release branch?

Completed in https://github.com/argoproj/argo-workflows/pull/12312#issuecomment-2013158797

**Comment by yulin-li** [comment]
could we make a patch release for recent CVE fixes?

**Comment by terrytangyuan** [comment]
Yes, we should release a patch for security fixes.

**Comment by terrytangyuan** [comment]
https://github.com/argoproj/argo-workflows/pull/12900 and https://github.com/argoproj/argo-workflows/pull/12901

**Comment by SlaterByte** [comment]
@isubasinghe, I see that #12413 was originally included as a feature addition for v3.5.5, but the was removed from your final [comment](https://github.com/argoproj/argo-workflows/issues/11997#issuecomment-1965877332). Is this feature being bumped to v3.5.6 or to a v3.6.x release? I see a few followup PRs ( #12596, #12632, #12862) as well, so maybe there was a stability concern? Looking forward to getting this feature released. Thanks!

**Comment by agilgur5** [comment]
> I see that #12413 was originally included as a feature addition for v3.5.5, but the was removed from your final [comment](https://github.com/argoproj/argo-workflows/issues/11997#issuecomment-1965877332). Is this feature being bumped to v3.5.6 or to a v3.6.x release?

It's a feature, so it will be released in the next minor, v3.6.

**Comment by agilgur5** [comment]
Released [v3.5.6](https://github.com/argoproj/argo-workflows/releases/tag/v3.5.6)

**Comment by terrytangyuan** [comment]
Any objections to cherry-picking https://github.com/argoproj/argo-workflows/pull/12736 to the next 3.5 patch release?

**Comment by agilgur5** [comment]
Nope, had been planning to do so since it's a feature that fixes a (substantial) 3.5 regression(s)

**Comment by terrytangyuan** [comment]
I am planning to only cherry-pick important fixes to 3.5.7. Please comment on this issue if you'd like to include any specific commits. Here's the current list:

- [ ] https://github.com/argoproj/argo-workflows/pull/13021

**Comment by Joibel** [comment]
I'd like to get #13004 in to 3.5.7 please. It needs an approver review.

**Comment by shuangkun** [comment]
could #12701  be reviewed,  because it fixes a very old p1 issue #9193

**Comment by shuangkun** [comment]
could #12936 be added， some user needs it https://github.com/argoproj/argo-workflows/issues/12936#issuecomment-2111872757

**Comment by terrytangyuan** [comment]
All added to the list.

**Comment by terrytangyuan** [comment]
UI security fix: https://github.com/argoproj/argo-workflows/pull/13069

**Comment by agilgur5** [comment]
> UI security fix: #13069

This would require a several other backports to make work as I detailed in https://github.com/argoproj/argo-workflows/pull/13069#pullrequestreview-2079815858.


> @agilgur5 Can you help make sure all PRs in the list [#11997 (comment)](https://github.com/argoproj/argo-workflows/issues/11997#issuecomment-2113898451) are cherry-picked into release branch and then we can push the tag?

Other than the above, yes, that was my plan.

**Comment by agilgur5** [comment]
Released [v3.5.7](https://github.com/argoproj/argo-workflows/releases/tag/v3.5.7).

Includes all merged fixes and security patches except for two due to https://github.com/argoproj/argo-workflows/pull/13069#pullrequestreview-2079815858 and https://github.com/argoproj/argo-workflows/pull/13012#issuecomment-2132611999.

Also lots of docs backports and a few CI security backports

See the changelog for more details: #13096

**Comment by agilgur5** [comment]
Released [v3.5.8](https://github.com/argoproj/argo-workflows/releases/tag/v3.5.8).

Includes all merged fixes and security patches except for the two skipped in 3.5.7 [above](https://github.com/argoproj/argo-workflows/issues/11997#issuecomment-2132801705) and https://github.com/argoproj/argo-workflows/pull/13169#issuecomment-2173732881.
Plus a few docs backports.
 
See the changelog for more details: #13206

**Comment by agilgur5** [comment]
Released [v3.5.9](https://github.com/argoproj/argo-workflows/releases/tag/v3.5.9).

Includes all merged fixes and security patches except for the ones skipped in previous releases [above](https://github.com/argoproj/argo-workflows/issues/11997#issuecomment-2175012386).
Plus docs backports.
 
See the changelog for more details: #13414

**Comment by agilgur5** [comment]
Released [v3.5.10](https://github.com/argoproj/argo-workflows/releases/tag/v3.5.10).

Primarily includes a hotfix for #13415.
 
See the changelog for more details: #13423

**Comment by JPZ13** [comment]
Hey @agilgur5 - we've got a customer that needs one of the fixes in v3.5.11. I know you're dealing with some health issues. Would you like us to take the release to help out? We wish you a speedy recovery

**Comment by agilgur5** [comment]
@JPZ13 Yes please, I would appreciate that. The WorkflowTaskResults and API fixes are P1s so this has been very high on my list to get out as well.

Unfortunately, I was busy reviewing some of those fixes etc that I didn't get to this before my current flare up. Was thinking I'd be feeling good enough over the weekend or this week to knock it out in a few hours, but I've honestly barely touched my desktop in a week 😞 Have at most 2 hours at a time of focus before I feel unwell rn 😕

If Alan or Isitha take this over, just make sure to note where I left off in 3.5.x backporting, i.e. things that I didn't merge in 3.5.10 or earlier had complex merge conflicts etc

**Comment by Joibel** [comment]
@agilgur5 sorry that you're still feeling rotten. Get well soon.

Between us @isubasinghe and I will try to cut a 3.5.11 this week.

**Comment by terrytangyuan** [comment]
Need to patch this high vuln security fix https://github.com/argoproj/argo-workflows/pull/13626

**Comment by agilgur5** [comment]
@terrytangyuan that one won't make it into 3.5 per https://github.com/argoproj/argo-workflows/pull/13069#pullrequestreview-2079815858

**Comment by Joibel** [comment]
v3.5.11 cherry picks:
- [x] #13624
- [x] #13553
- [x] #13548
- [x] #13607
- [x] #13606
- [x] #13604
- [x] #13516
- [x] #13566
- [x] #13589
- [x] #12383
- [x] #13543
- [x] #13569
- [x] #13567
- [x] #13393
- [x] #13513
- [x] #12787
- [x] #13537
- [x] #13286
- [x] #13491
- [x] #13487
- [x] #13508
- [x] #13198
- [x] #13500
- [x] #13211
- [x] #13463
- [x] #13481
- [x] #13448
- [x] #13454
- [x] #13260
- [x] #13455
- [x] #13016
- [x] #13431
- [x] #13429
- [x] #13411
- [x] #13381
- [x] #13366
- [x] #13350
- [x] #12723
- [x] #13375
- [x] #13370
- [x] #13048
- [x] #13348
- [x] #13250
- [x] #13349
- [x] #13504

**Comment by Joibel** [comment]
I've released [v.3.5.11](https://github.com/argoproj/argo-workflows/releases/tag/v3.5.11) without #13626. I'm happy to do a v.3.5.12 shortly if we can work out a way forward.

@agilgur5 can you suggest or action a plan to allow us to do a release which patches this vulnerability. It the right choice to just leave it as is even though it is of minimal/no impact by our judgement. Security scanners will still be alerting that argo-workflows isn't safe. If that comes down to removing the API page that seems better than doing nothing.

**Comment by agilgur5** [comment]
@Joibel [on Slack](https://cloud-native.slack.com/archives/C0510EUH90V/p1718139040410149?thread_ts=1718130524.678479&cid=C0510EUH90V) I mentioned _downgrading_ it to potentially workaround some of these CVEs since 3.4's version wasn't vulnerable (at least not to the first one).
Removing it would be a breaking change, so I didn't want to do that till 3.6

**Comment by Joibel** [comment]
For the [latest issue](https://security.snyk.io/vuln/SNYK-JS-DOMPURIFY-7984421) 3.4 is vulnerable as it is using [dompurify 2.3.3](https://github.com/argoproj/argo-workflows/blob/464965c20c9cd310ea1f958db2a4ef620023bce6/ui/yarn.lock#L3988).

With that in mind I think we need to develop a strategy for 3.4 and 3.5. Any suggestions?

For 3.6 we should remove that API page I guess to reduce our surface area before RC2? Are you feeling up to a PR for that @agilgur5?

**Comment by agilgur5** [comment]
Yes removing it and replacing it with a link to the versioned docs is on my to-do list. Per the Slack thread, not just for surface area, but also because it's a _massive_ dep (2nd largest, itself being larger than the UI codebase excluding other deps) which increases load time, build time, etc etc. Also, now that the docs have versions and have the same UI, we can just link to them and otherwise provide the schema files for download.

> Perhaps upgrading that to 2.5.4 would work?

Yes, in that vuin's case it would.
The problem that arises is what to do for future vulns where we may not have options? Given that these vulns apply to a transitive dep of a single page and are usually non-impacting (we don't use the vulnerable functionality or are otherwise not susceptible), they are of very low importance in my head

**Comment by agilgur5** [comment]
> I've released [v.3.5.11](https://github.com/argoproj/argo-workflows/releases/tag/v3.5.11) without #13626.

CHANGELOG PR for reference: https://github.com/argoproj/argo-workflows/pull/13631

**Comment by mweibel** [comment]
is it possible to cherry-pick https://github.com/argoproj/argo-workflows/pull/13693 to the next patch release? Thank you!

**Comment by Joibel** [comment]
> is it possible to cherry-pick https://github.com/argoproj/argo-workflows/pull/13693 to the next patch release? Thank you!

It looks like it will cherry pick nicely. We will try and bring it in.

**Comment by isubasinghe** [comment]
These are the chosen candidates for a 3.5.12 release:

- [x] e0ca7ffd1 - https://github.com/argoproj/argo-workflows/pull/13580
- [x] a0ba3c70d - https://github.com/argoproj/argo-workflows/pull/13688
- [x] ca6c4144c - https://github.com/argoproj/argo-workflows/pull/13678
- [x] f1fbe09cb - https://github.com/argoproj/argo-workflows/pull/13201
- [ ] ba75efb22 - https://github.com/argoproj/argo-workflows/pull/13586
- [x] 15f2170a1 - https://github.com/argoproj/argo-workflows/pull/12071
- [x] 7a3372039 - https://github.com/argoproj/argo-workflows/pull/13693
- [x] dfcaca4b9 - https://github.com/argoproj/argo-workflows/pull/13531
- [x] 2735f6bb1 - https://github.com/argoproj/argo-workflows/pull/13737
- [ ] 7007cba39 - https://github.com/argoproj/argo-workflows/pull/13648
- [x] 6d9e0f566 - https://github.com/argoproj/argo-workflows/pull/13752
- [x] 948127c79 - https://github.com/argoproj/argo-workflows/pull/13655
- [x] a8c360945 - https://github.com/argoproj/argo-workflows/pull/13743
- [x] ea6dae9a3 - https://github.com/argoproj/argo-workflows/pull/13788
- [x] 49ff7a44b - https://github.com/argoproj/argo-workflows/pull/13760
- [ ] 1017c1dbe - https://github.com/argoproj/argo-workflows/pull/13807
- [x] 3dfea6d5a - https://github.com/argoproj/argo-workflows/pull/13820
- [x] eb23eb6b8 - https://github.com/argoproj/argo-workflows/pull/13798

**Comment by jswxstw** [comment]
v3.5.x patches missed #13446, so can #13446, #13524 be out in v3.5.13?

**Comment by terrytangyuan** [comment]
@Joibel Could you help answer the questions above?

**Comment by Joibel** [comment]
3.5. is out of support now, closing.
