### ISSUE TITLE
v2.12.9 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5119]
* [ ] kennytrytek: fix: Invalid OpenAPI Spec (Issue 4817) (#4831) fcf4e9929
* [ ] Alex Collins: chore: More opinionated linting (#5072) a50ddb206
* [ ] Simon Behar: feat: Add checker to ensure that env variable doc is up to date (#5091) 19b22f25a
* [ ] Alex Collins: feat(controller): Logs Kubernetes API requests (#5084) 210080a0c
* [ ] Yuan Tang: build: Fix path to openapi-gen binary (#5089) 2f7c9087c
* [ ] Alex Collins: feat(executor): Minimize the number of Kubernetes API requests made by executors (#4954) 2ff4db115
* [ ] Simon Behar: fix: Do not create pods under shutdown strategy (#5055) 68979f6e3
* [x] Saravanan Balasubramanian: fix: Synchronization lock handling in Step/DAG Template level (#5081) 75d09b0f2
* [ ] Yuan Tang: docs: Add document for environment variables (#5080) cda5dc2e3
* [ ] Nelson Rodrigues: docs: Add Jungle to USERS.md (#5096) 57b382825
* [ ] Alex Collins: feat(ui): Display pretty cron schedule (#5088) 3b7e373ee
* [x] Alex Collins: fix: Revert "fix(controller): keep special characters in json string when … … 19da392 …use withItems (#4814)" (#5076) 1a0889cf3
* [ ] Simon Behar: fix: Prefer to break labels by '-' in UI (#5083) 893e9c9fe
* [ ] Viktor Farcic: docs: Add community video to README (#5087) 75f08e2e5
* [x] Alex Collins: fix(controller): Fix creator dashes (#5082) 77b23098c
* [ ] Dylan Hellems: feat(controller): Add podMetadata field to workflow spec. Resolves #4985 (#5031) f461b040a
* [ ] Yuan Tang: feat(controller): Add retry policy to support retry only on transient errors (#4999) 3b63e7d85
* [ ] Yuan Tang: chore: Update links to argo-workflows documentation (#5070) 1578c6188
* [ ] Kaan C. Fidan: docs: Add Vispera to USERS.md (#5047) 34f29c8ec
* [ ] Alex Collins: build: Simpler Docker build (#5057) b18b9920f
* [ ] Alex Collins: fix(executor): Correct usage of time.Duration. Fixes #5046 (#5049) 21e137bab
* [ ] Yuan Tang: feat(executor): Add user agent to workflow executor (#5014) 19a34b1fa
* [ ] Simon Behar: chore!: Remove deprecated fields (#5035) f31e0c6f9
* [ ] drannenberg: fix: Invalid URL for API Docs (#5063) f59d46229
* [ ] Yuan Tang: feat: Allow to specify grace period for pod GC (#5033) daf1a71b4
* [ ] Simon Behar: chore: Move paths to /argo-workflows/ (#5059) 65fb530e2
* [ ] Simon Behar: fix: Use React state to avoid new page load in Workflow view (#5058) 26f48a9d9
* [ ] Simon Behar: fix: Don't allow graph container to have its own scroll (#5056) a0669b5d0
* [ ] Alex Collins: fix(cli): Add insecure-skip-verify for HTTP1. Fixes #5008 (#5015) 425173a28
* [ ] Yuan Tang: chore: Reuse LookupEnvDurationOr to parse duration from environment variables (#5032) 3edb55c19
* [ ] Alastair Maw: M is demonstrably not less than 1 in the examples (#5021) 48b669cca
* [ ] tczhao: feat(controller): configurable terminationGracePeriodSeconds (#4940) 5915a2164
* [ ] Stéphane Este-Gracias: Fix golang build (#5039) 5824fc6bb

**Comment by alexec** [comment]
Done.

**Comment by simster7** [comment]
Released
