### ISSUE TITLE
Cherry-pick for v2.12.10

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5179]
* [ ] Simon Behar: fix: Specify where in YAML validation error occurred (#5174) a9c420060
* [ ] Simon Behar: fix: Fix node filters in UI (#5162) 4b78a7ee4
* [ ] Yuan Tang: feat(controller): Support pod GC strategy based on label selector on pods (#5090) d9fb0c30f
* [ ] Florian: docs: Add DLR to USERS.md (#5157) 6618f4752
* [ ] Alex Collins: fix(executor): Do not make unneeded `get pod` when no sidecars (#5161) 91528cc85
* [ ] Simon Behar: fix: Better message formating for nodes (#5160) bec80c868
* [ ] dherman: fix: send periodic keepalive packets on eventstream connections (#5101) d33b5cc06
* [ ] Yuan Tang: fix: Append the error message prior to offloading node status (#5043) 0f9b22b6e
* [ ] Alex Collins: build: Fix build of `argocli` (#5150) b54f13d6f
* [ ] Yuan Tang: feat: Support automatically create OSS bucket if not exists (#5133) 4611a1673
* [ ] Alex Collins: feat(controller): Use different container runtime executors for each workflow. Close #4254 (#4998) 687479fa4
* [ ] Alex Collins: feat: Add `argo submit --verify` hidden flag. Closes #5136 (#5141) 590df1dca
* [ ] Roi Kramer: feat: added lint from stdin (#5095) 377c5f84c
* [ ] Alex Collins: feat(server): Write an audit log entry for SSO users (#5145) 633da2584
* [ ] Saravanan Balasubramanian: fix: Revert the unwanted change in example  (#5139) 2ab02d95e
* [ ] Simon Behar: fix: Multiple UI fixes (#5140) 1c7921299
* [ ] Alex Collins: feat(ui): Surface result and exit-code outputs (#5137) 46538d958
* [ ] Alex Collins: test: Enhanced e2e tests (#5128) ccf4c612f
* [ ] Yuan Tang: build: Fix path to golangci-lint binary (#5131) 5c5c9f1c9
* [ ] Simon Behar: feat: Build dev-* branches as engineering builds (#5129) 5e64ec402
* [ ] dherman: fix(ui): add a tooltip for commonly truncated fields in the events pane (#5062) 4aa9847e2
* [ ] Yuan Tang: feat: Support pgzip as an alternative (de)compression implementation (#5108) b1535e533
* [ ] Ken Kaizu: docs: Update workflow-controller-configmap workflowRestrictions example doc (#5109) fb3cab210
* [ ] Simon Behar: chore: Add SHA256 checksums to release (#5122) e2c360d2b
* [ ] Alex Collins: fix(executor): Fix S3 policy based auth. Fixes #5110 (#5111) b0685bdd0
* [ ] kennytrytek: fix: Invalid OpenAPI Spec (Issue 4817) (#4831) fcf4e9929
* [ ] Alex Collins: chore: More opinionated linting (#5072) a50ddb206
* [ ] Simon Behar: feat: Add checker to ensure that env variable doc is up to date (#5091) 19b22f25a
* [ ] Alex Collins: feat(controller): Logs Kubernetes API requests (#5084) 210080a0c
* [ ] Yuan Tang: build: Fix path to openapi-gen binary (#5089) 2f7c9087c
* [ ] Alex Collins: feat(executor): Minimize the number of Kubernetes API requests made by executors (#4954) 2ff4db115
* [X] Simon Behar: fix: Do not create pods under shutdown strategy (#5055) 68979f6e3
* [ ] Saravanan Balasubramanian: fix: Synchronization lock handling in Step/DAG Template level (#5081) 75d09b0f2
* [ ] Yuan Tang: docs: Add document for environment variables (#5080) cda5dc2e3

**Comment by alexec** [comment]
Nothing from me.

**Comment by simster7** [comment]
Release not needed

**Comment by terrytangyuan** [comment]
Is this type of issue typically for outlining all recent changes and then maintainers can point out which of them are necessary to cherry pick? Just trying to see if there's anything I can chime in to help.
