### ISSUE TITLE
v3.0.0-rc4 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5247]
**Commits are added by default**, un-add commits you do not wish to be included

* [ ] Saravanan Balasubramanian: chore: Pass cron schedule to workflow (#5138) b59c8ebdc
* [ ] Alex Collins: feat(controller): Expression template tags. Resolves #4548 & #1293 (#5115) e6fa41a1b
* [ ] Yuan Tang: docs: Add example on using label selector in pod GC (#5237) 54b04c642
* [ ] Dan Garfield: docs: Add link to community calendar (#5233) af5abc8e1
* [X] Yuan Tang: feat(controller): Allow to modify time related configurations in leader election (#5234) bd4b46cd1
* [X] Alex Collins: feat(controller): Reused existing workflow informer. Resolves #5202 (#5204) cb9676e88
* [ ] Alex Collins: chore: Remove un-used code (#5232) e5f3dc123
* [X] Zach Aller: fix(controller): Leader lease shared name improvments (#5218) d7dc48c11
* [ ] Alex Collins: fix(server): Enable HTTPS probe for TLS by default. See #5205 (#5228) 2d2fba30c
* [ ] Simon Behar: fix: Flakey TestDataTransformationArtifactRepositoryRef (#5226) fb19af1cf
* [X] Simon Behar: fix: Do not display pagination warning when there is no pagination (#5221) 6412bc687
* [ ] Simon Behar: feat: Support for data sourcing and transformation with `data` template (#4958) 0c226ca49
* [ ] Alex Collins: chore(server): Enable TLS by default. Resolves #5205 (#5212) 7a91ade85
* [ ] Alex Collins: chore(server)!: Required authentication by default. Resolves #5206 (#5211) 01d310235
* [X] Simon Behar: fix: Checkbox is not clickable (#5213) 694690b0e
* [X] Zach Aller: fix(controller): Leader Lease Shared Name (#5214) f0e8df07b
* [ ] Alex Collins: chore: Tidy up test/verification (#5209) d83cf2196
* [X] Markus Lippert: fix(controller): Support emissary on Windows (#5203) 47ac32376
* [ ] Alex Collins: fix(controller): More emissary minor bugs (#5193) 8acdb1baf
* [ ] Brandon: docs: workflow-controller-configmap.md entry about argo-server. (#5195) e282fcc83
* [ ] dinever: feat(cli): Add cost optimization nudges for Argo CLI (#5168) 48811117c
* [ ] Yuan Tang: docs: Document the new OnTransientError retry policy (#5196) 4635d352e
* [X] Simon Behar: fix: Ensure whitespaces is allowed between name and bracket (#5176) 26ce0c090
* [X] Simon Behar: fix: Consder templateRef when filtering by tag (#5190) 2abf08eb4
* [ ] Alex Collins: fix(executor): Fix emissary bugs (#5187) 23415b2c1
* [X] Simon Behar: fix: Propagate URL changes to react state (#5188) f5dcd1bd4
* [X] Alex Collins: fix(controller): Fix timezone support. Fixes #5181  (#5182) e5a5f0394
* [ ] Alex Collins: feat(server): Enforce TLS >= v1.2 (#5172) 199016a6b
* [ ] Alex Collins: test: Add additional resource template test (#5166) 8a8759f38
* [ ] Michael Crenshaw: docs: document the WorkflowTemplate workflowMetadata feature (#5177) a46ff8248
* [ ] Michael Crenshaw: docs: typo (#5183) 71bf06c32
* [ ] descrepes: docs: Grafana dashboard link added to metrics.md (#5165) 7cee66c8a

**Comment by alexec** [comment]
fix(controller): Work-around Golang flaw. Fixes #5192

**Comment by simster7** [comment]
Released
