### ISSUE TITLE
v2.12.10 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5326]
* [ ] Simon Behar: fix: Minor UI fixes (#5325) 8309fd831
* [x] Simon Behar: fix: Disallow object names with more than 63 chars (#5324) 67f8ca27b
* [ ] Alex Collins: fix(executor): Delegate PNS wait to K8SAPI executor. (#5307) b048875dc
* [x] Saravanan Balasubramanian: fix(controller): shutdownstrategy on running workflow (#5289) a5d1accff
* [x] Saravanan Balasubramanian: fix: Backward compatible workflowTemplateRef from 2.11.x to  2.12.x (#5314) 112378fc7
* [ ] Yuan Tang: feat(executor): Configurable retry backoff settings for workflow executor (#5309) 103bf2bca
* [ ] Simon Behar: fix: Makefile target (#5313) 2e857f095
* [ ] Simon Behar: feat: Track nodeView tab in URL (#5300) 1c6775a04
* [ ] Alex Collins: test: Fix tests (#5302) b4cb24e41
* [ ] Simon Behar: fix: Use ScopedLocalStorage instead of direct localStorage (#5301) dc5bb12e5
* [ ] Simon Behar: build: Decrease `make codegen` time by (at least) 4 min (#5284) e396ea0e0
* [ ] Yuan Tang: feat: Improve OSS artifact driver usability when load/save directories (#5293) a31fd4456
* [ ] Alex Collins: fix(executor): Enhance PNS executor. Resolves #5251 (#5296) 757e0be18
* [ ] Saravanan Balasubramanian: feat: Conditional Artifacts and Parameters (#4987) 78ec644cd
* [ ] Alex Collins: fix(executor): Fix emissary resource template bug (#5295) 1a8ce1f13
* [ ] Rush Tehrani: docs: Add Onepanel to projects (#5287) 288ab927b
* [ ] Alex Collins: feat(controller): Container set template. Closes #2551 (#5099) 8729587ee
* [ ] Yuan Tang: chore: Remove uses of deprecated fields in docs and manifests (#5200) 21a026b5d
* [ ] Yuan Tang: fix: Use bucket.ListObjects() for OSS ListObjects() implementation (#5283) e56da57a3
* [ ] Alex Collins: test: Make e2e more robust (#5277) eaf25ac3a
* [ ] Simon Behar: fix: Fixes around archiving workflows (#5278) b6961ce6f
* [ ] Alex Collins: fix: Correctly log sub-resource Kubernetes API requests (#5276) ab68ea4c3
* [ ] Yuan Tang: feat: Support ListObjects() for Alibaba OSS artifact driver (#5261) 66fa8da0f
* [ ] Yuan Tang: fix: Fix swapped artifact repository key and ref in error message (#5272) b062cbf04
* [ ] Alex Collins: fix(executor): Fix concurrency error in PNS executor. Fixes #5250 (#5258) 69c40c09a
* [ ] Alex Collins: fix(executor): Fix docker "created" issue. Fixes #5252 (#5249) 9b538d922
* [ ] Alex Collins: ci: Enable emissary on CI :-o (#5259) 38b0f551c
* [ ] Yuan Tang: fix(controller): Take labels change into account in SignificantPodChange() (#5253) 07283cda6
* [ ] Alex Collins: fix(controller): Work-around Golang bug. Fixes #5192 (#5230) c4bcabd7c
* [ ] Alex Collins: test: Rename 'whitelist' to 'allowed' (#5246) 145420984
* [ ] Saravanan Balasubramanian: chore: Pass cron schedule to workflow (#5138) b59c8ebdc
* [ ] Alex Collins: feat(controller): Expression template tags. Resolves #4548 & #1293 (#5115) e6fa41a1b
* [ ] Yuan Tang: docs: Add example on using label selector in pod GC (#5237) 54b04c642
* [ ] Dan Garfield: docs: Add link to community calendar (#5233) af5abc8e1
* [ ] Yuan Tang: feat(controller): Allow to modify time related configurations in leader election (#5234) bd4b46cd1
* [ ] Alex Collins: feat(controller): Reused existing workflow informer. Resolves #5202 (#5204) cb9676e88
* [ ] Alex Collins: chore: Remove un-used code (#5232) e5f3dc123
* [ ] Zach Aller: fix(controller): Leader lease shared name improvments (#5218) d7dc48c11
* [ ] Alex Collins: fix(server): Enable HTTPS probe for TLS by default. See #5205 (#5228) 2d2fba30c
* [ ] Simon Behar: fix: Flakey TestDataTransformationArtifactRepositoryRef (#5226) fb19af1cf
* [ ] Simon Behar: fix: Do not display pagination warning when there is no pagination (#5221) 6412bc687
* [ ] Simon Behar: feat: Support for data sourcing and transformation with `data` template (#4958) 0c226ca49
* [ ] Alex Collins: chore(server): Enable TLS by default. Resolves #5205 (#5212) 7a91ade85
* [ ] Alex Collins: chore(server)!: Required authentication by default. Resolves #5206 (#5211) 01d310235
* [ ] Simon Behar: fix: Checkbox is not clickable (#5213) 694690b0e
* [ ] Zach Aller: fix(controller): Leader Lease Shared Name (#5214) f0e8df07b
* [ ] Alex Collins: chore: Tidy up test/verification (#5209) d83cf2196
* [ ] Markus Lippert: fix(controller): Support emissary on Windows (#5203) 47ac32376
* [ ] Alex Collins: fix(controller): More emissary minor bugs (#5193) 8acdb1baf
* [ ] Brandon: docs: workflow-controller-configmap.md entry about argo-server. (#5195) e282fcc83
* [ ] dinever: feat(cli): Add cost optimization nudges for Argo CLI (#5168) 48811117c
* [ ] Yuan Tang: docs: Document the new OnTransientError retry policy (#5196) 4635d352e
* [x] Simon Behar: fix: Ensure whitespaces is allowed between name and bracket (#5176) 26ce0c090
* [ ] Simon Behar: fix: Consder templateRef when filtering by tag (#5190) 2abf08eb4
* [ ] Alex Collins: fix(executor): Fix emissary bugs (#5187) 23415b2c1
* [ ] Simon Behar: fix: Propagate URL changes to react state (#5188) f5dcd1bd4
* [ ] Alex Collins: fix(controller): Fix timezone support. Fixes #5181  (#5182) e5a5f0394
* [ ] Alex Collins: feat(server): Enforce TLS >= v1.2 (#5172) 199016a6b
* [ ] Alex Collins: test: Add additional resource template test (#5166) 8a8759f38
* [ ] Michael Crenshaw: docs: document the WorkflowTemplate workflowMetadata feature (#5177) a46ff8248
* [ ] Michael Crenshaw: docs: typo (#5183) 71bf06c32
* [ ] descrepes: docs: Grafana dashboard link added to metrics.md (#5165) 7cee66c8a
* [ ] Alex Collins: feat(controller) Emissary executor.  (#4925) ab361667a
* [ ] Simon Behar: chore: Add missing CLI short docstrings (#5175) 8af359547
* [ ] Simon Behar: fix: Specify where in YAML validation error occurred (#5174) a9c420060
* [ ] Simon Behar: fix: Fix node filters in UI (#5162) 4b78a7ee4
* [ ] Yuan Tang: feat(controller): Support pod GC strategy based on label selector on pods (#5090) d9fb0c30f
* [ ] Florian: docs: Add DLR to USERS.md (#5157) 6618f4752
* [ ] Alex Collins: fix(executor): Do not make unneeded `get pod` when no sidecars (#5161) 91528cc85
* [ ] Simon Behar: fix: Better message formating for nodes (#5160) bec80c868
* [ ] dherman: fix: send periodic keepalive packets on eventstream connections (#5101) d33b5cc06
* [ ] Yuan Tang: fix: Append the error message prior to offloading node status (#5043) 0f9b22b6e
* [ ] Alex Collins: build: Fix build of `argocli` (#5150) b54f13d6f
* [ ] Yuan Tang: feat: Support automatically create OSS bucket if not exists (#5133) 4611a1673
* [ ] Alex Collins: feat(controller): Use different container runtime executors for each workflow. Close #4254 (#4998) 687479fa4
* [ ] Alex Collins: feat: Add `argo submit --verify` hidden flag. Closes #5136 (#5141) 590df1dca
* [ ] Roi Kramer: feat: added lint from stdin (#5095) 377c5f84c
* [ ] Alex Collins: feat(server): Write an audit log entry for SSO users (#5145) 633da2584
* [ ] Saravanan Balasubramanian: fix: Revert the unwanted change in example  (#5139) 2ab02d95e
* [ ] Simon Behar: fix: Multiple UI fixes (#5140) 1c7921299
* [ ] Alex Collins: feat(ui): Surface result and exit-code outputs (#5137) 46538d958
* [ ] Alex Collins: test: Enhanced e2e tests (#5128) ccf4c612f
* [ ] Yuan Tang: build: Fix path to golangci-lint binary (#5131) 5c5c9f1c9
* [ ] Simon Behar: feat: Build dev-* branches as engineering builds (#5129) 5e64ec402
* [ ] dherman: fix(ui): add a tooltip for commonly truncated fields in the events pane (#5062) 4aa9847e2
* [ ] Yuan Tang: feat: Support pgzip as an alternative (de)compression implementation (#5108) b1535e533
* [ ] Ken Kaizu: docs: Update workflow-controller-configmap workflowRestrictions example doc (#5109) fb3cab210
* [ ] Simon Behar: chore: Add SHA256 checksums to release (#5122) e2c360d2b
* [ ] Alex Collins: fix(executor): Fix S3 policy based auth. Fixes #5110 (#5111) b0685bdd0
* [ ] kennytrytek: fix: Invalid OpenAPI Spec (Issue 4817) (#4831) fcf4e9929
* [ ] Alex Collins: chore: More opinionated linting (#5072) a50ddb206
* [ ] Simon Behar: feat: Add checker to ensure that env variable doc is up to date (#5091) 19b22f25a
* [ ] Alex Collins: feat(controller): Logs Kubernetes API requests (#5084) 210080a0c
* [ ] Yuan Tang: build: Fix path to openapi-gen binary (#5089) 2f7c9087c
* [ ] Alex Collins: feat(executor): Minimize the number of Kubernetes API requests made by executors (#4954) 2ff4db115
* [ ] Simon Behar: fix: Do not create pods under shutdown strategy (#5055) 68979f6e3
* [ ] Saravanan Balasubramanian: fix: Synchronization lock handling in Step/DAG Template level (#5081) 75d09b0f2
* [ ] Yuan Tang: docs: Add document for environment variables (#5080) cda5dc2e3
* [ ] Nelson Rodrigues: docs: Add Jungle to USERS.md (#5096) 57b382825
* [ ] Alex Collins: feat(ui): Display pretty cron schedule (#5088) 3b7e373ee
* [ ] Alex Collins: fix: Revert "fix(controller): keep special characters in json string when … … 19da392 …use withItems (#4814)" (#5076) 1a0889cf3
* [ ] Simon Behar: fix: Prefer to break labels by '-' in UI (#5083) 893e9c9fe
* [ ] Viktor Farcic: docs: Add community video to README (#5087) 75f08e2e5

**Comment by simster7** [comment]
Released
