### ISSUE TITLE
v3.0.0-rc5 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5327]
* [x] Simon Behar: fix: Minor UI fixes (#5325) 8309fd831
* [x] Simon Behar: fix: Disallow object names with more than 63 chars (#5324) 67f8ca27b
* [x] Alex Collins: fix(executor): Delegate PNS wait to K8SAPI executor. (#5307) b048875dc
* [x] Saravanan Balasubramanian: fix(controller): shutdownstrategy on running workflow (#5289) a5d1accff
* [x] Saravanan Balasubramanian: fix: Backward compatible workflowTemplateRef from 2.11.x to  2.12.x (#5314) 112378fc7
* [ ] Yuan Tang: feat(executor): Configurable retry backoff settings for workflow executor (#5309) 103bf2bca
* [ ] Simon Behar: fix: Makefile target (#5313) 2e857f095
* [x] Simon Behar: feat: Track nodeView tab in URL (#5300) 1c6775a04
* [ ] Alex Collins: test: Fix tests (#5302) b4cb24e41
* [x] Simon Behar: fix: Use ScopedLocalStorage instead of direct localStorage (#5301) dc5bb12e5
* [x] Simon Behar: build: Decrease `make codegen` time by (at least) 4 min (#5284) e396ea0e0
* [ ] Yuan Tang: feat: Improve OSS artifact driver usability when load/save directories (#5293) a31fd4456
* [x] Alex Collins: fix(executor): Enhance PNS executor. Resolves #5251 (#5296) 757e0be18
* [ ] Saravanan Balasubramanian: feat: Conditional Artifacts and Parameters (#4987) 78ec644cd
* [ ] Alex Collins: fix(executor): Fix emissary resource template bug (#5295) 1a8ce1f13
* [ ] Rush Tehrani: docs: Add Onepanel to projects (#5287) 288ab927b
* [ ] Alex Collins: feat(controller): Container set template. Closes #2551 (#5099) 8729587ee
* [ ] Yuan Tang: chore: Remove uses of deprecated fields in docs and manifests (#5200) 21a026b5d
* [ ] Yuan Tang: fix: Use bucket.ListObjects() for OSS ListObjects() implementation (#5283) e56da57a3
* [ ] Alex Collins: test: Make e2e more robust (#5277) eaf25ac3a
* [x] Simon Behar: fix: Fixes around archiving workflows (#5278) b6961ce6f
* [x] Alex Collins: fix: Correctly log sub-resource Kubernetes API requests (#5276) ab68ea4c3
* [ ] Yuan Tang: feat: Support ListObjects() for Alibaba OSS artifact driver (#5261) 66fa8da0f
* [ ] Yuan Tang: fix: Fix swapped artifact repository key and ref in error message (#5272) b062cbf04
* [x] Alex Collins: fix(executor): Fix concurrency error in PNS executor. Fixes #5250 (#5258) 69c40c09a
* [x] Alex Collins: fix(executor): Fix docker "created" issue. Fixes #5252 (#5249) 9b538d922
* [ ] Alex Collins: ci: Enable emissary on CI :-o (#5259) 38b0f551c
* [x] Yuan Tang: fix(controller): Take labels change into account in SignificantPodChange() (#5253) 07283cda6
* [x] Alex Collins: fix(controller): Work-around Golang bug. Fixes #5192 (#5230) c4bcabd7c
* [ ] Alex Collins: test: Rename 'whitelist' to 'allowed' (#5246) 145420984
* [x] Saravanan Balasubramanian: chore: Pass cron schedule to workflow (#5138) b59c8ebdc
* [ ] Alex Collins: feat(controller): Expression template tags. Resolves #4548 & #1293 (#5115) e6fa41a1b
* [ ] Yuan Tang: docs: Add example on using label selector in pod GC (#5237) 54b04c642
* [ ] Dan Garfield: docs: Add link to community calendar (#5233) af5abc8e1

**Comment by alexec** [comment]
Done.

**Comment by alexec** [comment]
Done.

**Comment by simster7** [comment]
Released
