### ISSUE TITLE
v3.0.0-rc7 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5409]
* [ ] surj-bains: docs: add polarpoint.io (#5387) 4c4cbd2e
* [ ] Shoubhik Bose: docs: Update code of conduct (#5404) 26eb8a95
* [ ] Yuan Tang: feat: Allow transient errors in StopWorkflow() (#5396) b24aaeaf
* [ ] dinever: fix(controller): Fixed wrong error message (#5390) 1ec7ac0f
* [ ] Stephan van Maris: fix(ui): typo (#5391) 4b7e3513
* [x] Saravanan Balasubramanian: fix(test): TestWorkflowTemplateRefWithShutdownAndSuspend flaky (#5381) 982e5e9d
* [ ] Simon Behar: feat(controller): Add failFast flag to DAG and Step templates (#5315) 57c05dfa
* [x] Alex Collins: fix(executor): Kill injected sidecars. Fixes #5337 (#5345) fcb09899
* [ ] Stephan van Maris: feat: Add helper functions to expr when parsing metadata. Fixes #5351 (#5374) 1f7cf1e3
* [x] Alex Collins: fix(controller): Fix `podSpecPatch` (#5360) d828717c
* [X] Simon Behar: fix: Fix S3 file loading (#5353) 2d331f3a
* [x] Alex Collins: fix(executor): Make docker executor more robust. (#5363) 9faae18a
* [x] Yuan Tang: fix(executor): Fix resource patch when not providing flags. Fixes #5310 (#5311) e0f71f3a
* [ ] Alex Collins: fix(controller): Correctly log pods/exec call (#5359) 94e155b0
* [ ] Simon Behar: docs: Add data doc to website (#5358) 2320bdc7
* [ ] Alex Collins: fix(ui): Fix container-set log viewing in UI (#5348) 80b5ab9b
* [ ] Simon Behar: fix: More Makefile fixes (#5347) bde9f217
* [ ] Alex Collins: test: Make tests more robust, again (#5346) 36f672fc
* [ ] Alex Collins: docs: Add @terrytangyuan as reviewer (#5191) 93e4d4fe
* [ ] dherman: docs: copy information about what is argo to the docs landing page (#5336) a7903879
* [ ] Simon Behar: fix: Ensure release images are 'clean' (#5344) 849a5f9a
* [ ] Simon Behar: fix: Ensure DEV_BRANCH is correct (#5343) 23b8c031
* [ ] Alex Collins: ci: Fix argoexec build (#5335) ad7653b4
* [ ] Alex Collins: ci: Github actions refactor (#5280) 814944cb
* [ ] Alex Collins: fix(executor): Fix container set bugs (#5317) ba949c3a
* [ ] Yuan Tang: feat: Support structured JSON logging for controller, executor, and server (#5158) 9d2e9615
* [x] Saravanan Balasubramanian: fix(test): Flaky TestWorkflowShutdownStrategy  (#5331) 7fc1f2f2

**Comment by Sefriol** [comment]
Hey! I am just wondering if there is a time frame for an official v3.0 release? ;)

**Comment by terrytangyuan** [comment]
Perhaps cherry pick this one since it's a regression? (patch without flags will not work)

fix(executor): Fix resource patch when not providing flags. Fixes #5310 (#5311) e0f71f3

**Comment by simster7** [comment]
> Consider cherry-picking this one since it's a regression?

Done

**Comment by simster7** [comment]
> Hey! I am just wondering if there is a time frame for an official/stable v3.0 release? ;)

I believe we want to do one or two more RCs, which means GA should be in two to three weeks

**Comment by alexec** [comment]
Can we add #5212?

**Comment by simster7** [comment]
Released
