### ISSUE TITLE
v3.0.0-rc9 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5488]
* [x] Simon Behar: fix(ui): Multiple UI fixes (#5498) 4eb351cba
* [x] Simon Behar: fix(controller): Fix workflows with retryStrategy left Running after completion (#5497) dfe6ceb43
* [ ] Simon Behar: test: Make cron test suite robust (#5453) be44ce9dd
* [ ] Alex Collins: ci: Add codecov.yaml to silence red-herring errors (#5482) 939019075
* [ ] Roi Kramer: fix(cli): Linting improvements (#5224) ea26a964b
* [x] Yuan Tang: fix(controller): Only set global parameters after workflow validation succeeded to avoid panics (#5477) 513756ebf
* [ ] Zhong Dai: docs: fixed the typo, The submit ... doesn't make sense (#5470) 5bd7ce81d
* [ ] Yuan Tang: chore: Remove unused work queue in Cron controller (#5461) d10696d34
* [ ] Alex Collins: fix(controller): Enhance output capture (#5450) 9a1c046ee
* [ ] Saïfane FARFAR: feat(server): Disable Basic auth if server is not running in client mode (#5401) 46aaa700e
* [ ] Yuan Tang: fix(controller): Add permissions to create/update configmaps for memoization in quick-start manifests (#5447) e638981bf
* [ ] dinever: fix(controller): Fix the issue of {{retries}} in PodSpecPatch not being updated (#5389) b01ca3a1d
* [x] Simon Behar: fix: Set daemoned nodes to Succeeded when boudary ends (#5421) 72ee1cce9
* [x] Alex Collins: fix(executor): Ignore non-running Docker kill errors (#5451) d9f201001
* [ ] Saravanan Balasubramanian: feat: Template defaults (#5410) 7e4e1b78c
* [ ] Alex Collins: ci: More e2e test work (#5458) 3b129a8f2
* [x] Simon Behar: fix: Fix getStepOrDAGTaskName (#5454) 440a68976
* [x] Simon Behar: fix: Various UI fixes (#5449) 8d2006181
* [ ] Alex Collins: build: `make start` tails logs (#5416) fc8ecc455
* [x] Alex Collins: fix(executor): PNS support artifacts for short-running containers (#5427) 2371a6d3f
* [x] Saravanan Balasubramanian: fix(test): TestWorkflowTemplateRefWithShutdownAndSuspend flakiness (#5441) 07ef0e6b8
* [x] Yuan Tang: fix(cli): Only append parse result when not nil to avoid panic (#5424) c16a471cb
* [x] Alex Collins: fix(ui): Fix link button. Fixes #5429 (#5430) 8f03970be
* [x] Yuan Tang: fix(executor): Surface error when wait container fails to establish pod watch (#5372) f4432043c
* [ ] Alex Collins: feat(executor): Move exit code capture to controller. See #5251 (#5328) d71786571
* [ ] Jesse Suen: docs: add documentation about network security (#5420) 525ddecba
* [x] Saravanan Balasubramanian: fix(test): Fix TestWorkflowTemplateRefWithShutdownAndSuspend flakyness (#5418) 04f3a957b
* [ ] Yuan Tang: feat(executor): Switch to use SDK and poll-based resource status checking (#5364) ed957dd9c
* [ ] Alex Collins: feat(executor) Add injected sidecar support to Emissary (#5383) d3eeddb1f
* [ ] Alex Collins: docs: Document releases. Closes #5379 (#5402) d3079b317
* [ ] Simon Behar: fix: Do not allow cron workflow names with more than 52 chars (#5407) 189b6a8e3
* [x] Alex Collins: feat(executor): Reduce poll time 3s to 1s for PNS and Emissary executors (#5386) 8e137582c
* [ ] surj-bains: docs: add polarpoint.io (#5387) 4c4cbd2e2
* [ ] Shoubhik Bose: docs: Update code of conduct (#5404) 26eb8a953

**Comment by terrytangyuan** [comment]
Could we cherry-pick the following as well? @alexec Please double check https://github.com/argoproj/argo-workflows/pull/5372 as well since I saw that you marked it as v3.1 milestone.

*  Yuan Tang: fix(controller): Only set global parameters after workflow validation succeeded to avoid panics (#5477) 513756e
 * Yuan Tang: fix(cli): Only append parse result when not nil to avoid panic (#5424) c16a471
 * Yuan Tang: fix(executor): Surface error when wait container fails to establish pod watch (#5372) f443204

**Comment by simster7** [comment]
Released
