### ISSUE TITLE
v3.0.0-rc10 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5541]
* [ ] Simon Behar: chore: Lint master (#5527) eb6f3a14f
* [ ] Yuan Tang: docs: Add instruction on configuring env vars for controller and executor (#5524) a443c53d1
* [ ] Yuan Tang: feat(controller): Add last hit timestamp to memoization caches (#5487) 76b6a0eff
* [x] Simon Behar: fix: Default to insecure mode when no certs are present (#5511) a61d84cc0
* [ ] Riccardo Piccoli: fix: add softonic as user (#5522) 4a1caca1e
* [ ] Alex Collins: docs: Add demo link to README.md (#5512) dcc51665c
* [ ] wanglong001: fix: Spelling Mistake (#5507) bbdf651b7
* [ ] Shoubhik Bose: fix: avoid short names in deployment manifests (#5475) b8af3411b
* [ ] Nicolas Michel: docs: Conditionals example improved with complex syntax (#5467) 24ccdf40c
* [x] Simon Behar: fix(controller): Use node.Name instead of node.DisplayName for onExit nodes (#5486) d964fe448
* [x] Alex Collins: fix(ui): Correct Argo Events swagger (#5490) 80cea6a36
* [x] Alex Collins: fix(executor): Always poll for Docker injected sidecars. Resolves #5448 (#5479) 865b1fe8b
* [ ] Shoubhik Bose: fix: avoid short names in Dockerfiles (#5474) c13755b16
* [ ] Alex Collins: ci: Set E2E_TIMEOUT=1m in CI (#5499) 95bd1ccba
* [ ] Reijer Copier: fix: Add logging to aid troubleshooting (#5501) beb0f26be
* [ ] Shoubhik Bose: fix: Run controller as un-privileged (#5460) 306594164
* [x] Saravanan Balasubramanian: chore: Handling panic in go routines (#5489) c8645fc40
* [ ] Shoubhik Bose: fix: certs in non-root (#5476) 2a099f8ab
* [ ] Michael Weibel: docs: add limitation about windows versions (#5462) d246bcf44

**Comment by alexec** [comment]
done

**Comment by alexec** [comment]
I vote we GA.

**Comment by simster7** [comment]
Same, I'll make a GA release

**Comment by book987** [comment]
Hi, can we pick #5315 in RC10?

**Comment by simster7** [comment]
> Hi, can we pick #5315 in RC10?

Hi @book987. Sorry, this didn't make it on the release. Since it's a feature we'll want to release is with `v3.1`. I can make a dev build with `v3.0.0` + #5315 for you to test and get it straight away. Are you interested?

**Comment by simster7** [comment]
Released
