### ISSUE TITLE
v2.12.11 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5542]
* [ ] Simon Behar: chore: Lint master (#5527) eb6f3a14f
* [ ] Yuan Tang: docs: Add instruction on configuring env vars for controller and executor (#5524) a443c53d1
* [ ] Yuan Tang: feat(controller): Add last hit timestamp to memoization caches (#5487) 76b6a0eff
* [ ] Simon Behar: fix: Default to insecure mode when no certs are present (#5511) a61d84cc0
* [ ] Riccardo Piccoli: fix: add softonic as user (#5522) 4a1caca1e
* [ ] Alex Collins: docs: Add demo link to README.md (#5512) dcc51665c
* [ ] wanglong001: fix: Spelling Mistake (#5507) bbdf651b7
* [ ] Shoubhik Bose: fix: avoid short names in deployment manifests (#5475) b8af3411b
* [ ] Nicolas Michel: docs: Conditionals example improved with complex syntax (#5467) 24ccdf40c
* [ ] Simon Behar: fix(controller): Use node.Name instead of node.DisplayName for onExit nodes (#5486) d964fe448
* [ ] Alex Collins: fix(ui): Correct Argo Events swagger (#5490) 80cea6a36
* [ ] Alex Collins: fix(executor): Always poll for Docker injected sidecars. Resolves #5448 (#5479) 865b1fe8b
* [ ] Shoubhik Bose: fix: avoid short names in Dockerfiles (#5474) c13755b16
* [ ] Alex Collins: ci: Set E2E_TIMEOUT=1m in CI (#5499) 95bd1ccba
* [ ] Reijer Copier: fix: Add logging to aid troubleshooting (#5501) beb0f26be
* [ ] Shoubhik Bose: fix: Run controller as un-privileged (#5460) 306594164
* [x] Saravanan Balasubramanian: chore: Handling panic in go routines (#5489) c8645fc40
* [ ] Shoubhik Bose: fix: certs in non-root (#5476) 2a099f8ab
* [ ] Michael Weibel: docs: add limitation about windows versions (#5462) d246bcf44
* [ ] Simon Behar: fix(ui): Multiple UI fixes (#5498) 4eb351cba
* [ ] Simon Behar: fix(controller): Fix workflows with retryStrategy left Running after completion (#5497) dfe6ceb43
* [ ] Simon Behar: test: Make cron test suite robust (#5453) be44ce9dd
* [ ] Alex Collins: ci: Add codecov.yaml to silence red-herring errors (#5482) 939019075
* [ ] Roi Kramer: fix(cli): Linting improvements (#5224) ea26a964b
* [ ] Yuan Tang: fix(controller): Only set global parameters after workflow validation succeeded to avoid panics (#5477) 513756ebf
* [ ] Zhong Dai: docs: fixed the typo, The submit ... doesn't make sense (#5470) 5bd7ce81d
* [ ] Yuan Tang: chore: Remove unused work queue in Cron controller (#5461) d10696d34
* [ ] Alex Collins: fix(controller): Enhance output capture (#5450) 9a1c046ee
* [ ] Saïfane FARFAR: feat(server): Disable Basic auth if server is not running in client mode (#5401) 46aaa700e
* [ ] Yuan Tang: fix(controller): Add permissions to create/update configmaps for memoization in quick-start manifests (#5447) e638981bf
* [ ] dinever: fix(controller): Fix the issue of {{retries}} in PodSpecPatch not being updated (#5389) b01ca3a1d
* [ ] Simon Behar: fix: Set daemoned nodes to Succeeded when boudary ends (#5421) 72ee1cce9
* [ ] Alex Collins: fix(executor): Ignore non-running Docker kill errors (#5451) d9f201001
* [ ] Saravanan Balasubramanian: feat: Template defaults (#5410) 7e4e1b78c
* [ ] Alex Collins: ci: More e2e test work (#5458) 3b129a8f2
* [ ] Simon Behar: fix: Fix getStepOrDAGTaskName (#5454) 440a68976
* [ ] Simon Behar: fix: Various UI fixes (#5449) 8d2006181
* [ ] Alex Collins: build: `make start` tails logs (#5416) fc8ecc455
* [ ] Alex Collins: fix(executor): PNS support artifacts for short-running containers (#5427) 2371a6d3f
* [ ] Saravanan Balasubramanian: fix(test): TestWorkflowTemplateRefWithShutdownAndSuspend flakiness (#5441) 07ef0e6b8
* [ ] Yuan Tang: fix(cli): Only append parse result when not nil to avoid panic (#5424) c16a471cb
* [ ] Alex Collins: fix(ui): Fix link button. Fixes #5429 (#5430) 8f03970be
* [ ] Yuan Tang: fix(executor): Surface error when wait container fails to establish pod watch (#5372) f4432043c
* [ ] Alex Collins: feat(executor): Move exit code capture to controller. See #5251 (#5328) d71786571
* [ ] Jesse Suen: docs: add documentation about network security (#5420) 525ddecba
* [ ] Saravanan Balasubramanian: fix(test): Fix TestWorkflowTemplateRefWithShutdownAndSuspend flakyness (#5418) 04f3a957b
* [ ] Yuan Tang: feat(executor): Switch to use SDK and poll-based resource status checking (#5364) ed957dd9c
* [ ] Alex Collins: feat(executor) Add injected sidecar support to Emissary (#5383) d3eeddb1f
* [ ] Alex Collins: docs: Document releases. Closes #5379 (#5402) d3079b317
* [ ] Simon Behar: fix: Do not allow cron workflow names with more than 52 chars (#5407) 189b6a8e3
* [ ] Alex Collins: feat(executor): Reduce poll time 3s to 1s for PNS and Emissary executors (#5386) 8e137582c
* [ ] surj-bains: docs: add polarpoint.io (#5387) 4c4cbd2e2
* [ ] Shoubhik Bose: docs: Update code of conduct (#5404) 26eb8a953
* [ ] Yuan Tang: feat: Allow transient errors in StopWorkflow() (#5396) b24aaeaff
* [ ] dinever: fix(controller): Fixed wrong error message (#5390) 1ec7ac0fa
* [ ] Stephan van Maris: fix(ui): typo (#5391) 4b7e3513e
* [ ] Saravanan Balasubramanian: fix(test): TestWorkflowTemplateRefWithShutdownAndSuspend flaky (#5381) 982e5e9df
* [ ] Simon Behar: feat(controller): Add failFast flag to DAG and Step templates (#5315) 57c05dfab
* [ ] Alex Collins: fix(executor): Kill injected sidecars. Fixes #5337 (#5345) fcb098995
* [ ] Stephan van Maris: feat: Add helper functions to expr when parsing metadata. Fixes #5351 (#5374) 1f7cf1e3b
* [ ] Alex Collins: fix(controller): Fix `podSpecPatch` (#5360) d828717c5
* [ ] Simon Behar: fix: Fix S3 file loading (#5353) 2d331f3a4
* [ ] Alex Collins: fix(executor): Make docker executor more robust. (#5363) 9faae18a1
* [ ] Yuan Tang: fix(executor): Fix resource patch when not providing flags. Fixes #5310 (#5311) e0f71f3af
* [ ] Alex Collins: fix(controller): Correctly log pods/exec call (#5359) 94e155b08
* [ ] Simon Behar: docs: Add data doc to website (#5358) 2320bdc7d
* [ ] Alex Collins: fix(ui): Fix container-set log viewing in UI (#5348) 80b5ab9b8
* [ ] Simon Behar: fix: More Makefile fixes (#5347) bde9f217e
* [ ] Alex Collins: test: Make tests more robust, again (#5346) 36f672fc5
* [ ] Alex Collins: docs: Add @terrytangyuan as reviewer (#5191) 93e4d4fe2
* [ ] dherman: docs: copy information about what is argo to the docs landing page (#5336) a79038791
* [ ] Simon Behar: fix: Ensure release images are 'clean' (#5344) 849a5f9aa
* [ ] Simon Behar: fix: Ensure DEV_BRANCH is correct (#5343) 23b8c0319
* [ ] Alex Collins: ci: Fix argoexec build (#5335) ad7653b48
* [ ] Alex Collins: ci: Github actions refactor (#5280) 814944cb8
* [ ] Alex Collins: fix(executor): Fix container set bugs (#5317) ba949c3a6
* [ ] Yuan Tang: feat: Support structured JSON logging for controller, executor, and server (#5158) 9d2e9615e

Added 199016a feat(server): Enforce TLS >= v1.2 (#5172)

**Comment by alexec** [comment]
Done

**Comment by simster7** [comment]
`2ba0a43`

**Comment by alexec** [comment]
Released.
