### ISSUE TITLE
v3.0.1 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5576]
* [x] Simon Behar: fix: Switch InsecureSkipVerify to true (#5575) 4e450e250
* [x] BOOK: fix(controller): clean up before insert into argo_archived_workflows_labels (#5568) ed54f158d
* [ ] Yuan Tang: fix: Remove invalid label value for last hit timestamp from caches (#5528) 2b3655ecb
* [x] Alex Collins: fix(executor): GODEBUG=x509ignoreCN=0 (#5562) 2ba0a4369
* [ ] Alex Collins: docs: Updated README.md (#5560) 17ff2c17c
* [ ] Kishore Chitrapu: docs: added Intralinks (#5561) 3df62791d
* [ ] Simon Behar: fix: Build static files in engineering builds (#5559) 3c3754f98
* [ ] BOOK: fix(cli): exit when calling subcommand node without args (#5556) 23ccd9cf3
* [x] Tim Collins: fix: Reference new argo-workflows url in in-app links (#5553) aa0494859
* [ ] Iven: docs: Add Zhihu as user (#5555) 26ca3fab9
* [x] Alex Collins: fix(server): Disable CN check (Go 15 does not support). Fixes #5539 (#5550) 20f00470e
* [ ] Riccardo Piccoli: fix: allow mountPaths with traling slash (#5521) 872897ff9
* [ ] Shoubhik Bose: fix: certs in non-root (#5476) fee4d0613
* [ ] Shoubhik Bose: fix: Run controller as un-privileged (#5460) c96a3257a

**Comment by alexec** [comment]
I've remove Shuoubhik's PRs as they risk introducing new problems.

I've added 20f0047, but I think you might end up reverting.

**Comment by simster7** [comment]
> I've remove Shuoubhik's PRs as they risk introducing new problems.

:+1: we can test those and if all good include them in v3.0.2

**Comment by alexec** [comment]
I think we don't need them.

**Comment by simster7** [comment]
Released
