### ISSUE TITLE
Improve template filtering/grouping on metrics page

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-workflows#57]
Metrics screen shows aggregated run stats for each template. Statistics is aggregated by repo, template name, branch. From user's point of view there is one template in repo and branches contains different versions of it, so statistics should be aggregated by repo/template name.

Following changes are required:
1. [x] Implement API which returns unique list of template names.
1. [x] Filter jobs by template name instead of template id: https://github.com/argoproj/argo/issues/183
1. [x] Add template name filter to jobs global search: https://github.com/argoproj/argo/issues/184
1. [x] Allow navigate to jobs from metics page: https://github.com/argoproj/argo/issues/185

**Comment by alexmt** [comment]
Created PR for API change which allows fetching unique template names/repos:  https://github.com/argoproj/argo/pull/182

**Comment by wokeGit** [comment]
PR for #185 https://github.com/argoproj/argo/pull/197
