### ISSUE TITLE
v3.0.2 cherry-pick

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5715]
* [x] Yuan Tang: fix: Only save memoization cache when node succeeded (#5711) dba2c044
* [x] Alex Collins: fix(controller): Fix cron timezone support. Fixes #5653 (#5712) 8e9e6d67
* [x] Alex Collins: fix(ui): Fix `showWorkflows` button. Fixes #5645 (#5693) 0a6f2fc3
* [x] Alex Collins: fix(ui): Fix YAML/JSON toggle. Fixes #5690 (#5694) f9635563
* [x] Alex Collins: fix(cli): Validate cron on update. Fixes #5691 (#5692) b267e3cf
* [x] Alex Collins: fix(executor): Ignore not existing metadata. Fixes #5656 (#5695) 9a872de1
* [ ] Alex Collins: ci: Separate `make wait` (#5696) e93ee4fe
* [x] Alex Collins: fix(executor): More logs for PNS sidecar termination. #5627 (#5683) 91c08cdd
* [x] Alex Collins: fix(controller): Correct bug for repository ref without default key. Fixes #5646 (#5660) f6be5691
* [x] Alex Collins: build: Specify Dockerfile version (#5689) 5a397226
* [ ] tobisinghania: feat(controller): Allow to disable leader election (#5638) (#5648) e3d1d1e8
* [ ] Yuan Tang: docs: Revert "docs: Update link to the new CNCF Slack channel (#5681)" (#5684) 3c8f5617
* [ ] tczhao: docs(tls): 3.0 defaults to tls enabled (#5686) cad916ef
* [ ] Niklas Hansson: feat(cli): Add offline linting (#5569) 86073914
* [ ] dinever: feat(ui): Support expression evaluation in links (#5666) a0185236
* [ ] Yuan Tang: fix(executor): Correctly surface error when resource is deleted during status checking (#5675) 24ac7252
* [ ] Yuan Tang: docs: Update link to the new CNCF Slack channel (#5681) eab122bb
* [ ] tczhao: docs(cron): add dst description (#5679) 3fab1e5d
* [x] Michael Ruoss: fix(ui): strip inner quotes from argoToken (#5677) 1d367ddf
* [ ] Pruthvi Papasani: fix: Increase Name width to 3 and decrease NameSpace width to 1 (#5678) bf5d7bfa
* [ ] tczhao: feat(ui): support any yaml reference in link (#5667) 71dfc797
* [ ] Alex Collins: ci: Fix test-cli: STATIC_FILES=false (#5673) fce82bfd
* [ ] Yuan Tang: chore: Update link to k8s API conventions (#5674) e80177a6
* [x] kennytrytek: fix: git clone on non-default branch fails (Fixes #5629) (#5630) ec3b82d9
* [ ] uucloud: fix(executor):Failure node failed to get archived log (#5671) d5e492c2
* [ ] dinever: fix(artifacts): only retry on transient S3 errors (#5579) b7d69053
* [x] Alex Collins: fix: Default ARGO_SECURE=true. Fixes #5607 (#5626) defbd600
* [ ] Bogdan Luput: docs: manifests for SSO using ArgoCD Dex, to be used with Kustomize (#5647) 9c942d59
* [x] Simon Behar: fix: Make task/step name extractor robust (#5672) 46ec3028
* [ ] Yuan Tang: chore: Correctly log version string and remove unnecessary error check (#5664) ded95bc3
* [ ] Alex Collins: ci: Try to make CI more robust (#5633) 54f4c262
* [ ] Saravanan Balasubramanian: chore: Support substitute global variable in Spec level elements (#5565) cc7e310c
* [x] Yuan Tang: fix: Surface error during wait timeout for OSS artifact driver API calls (#5601) 88917cbd
* [ ] Tim Collins: docs: Document SSO expiry option (#5552) ec4c662c
* [x] Alex Collins: fix(ui): Fix editor. Fixes #5613 Fixes #5617 (#5620) b76fac75
* [x] Iven: fix(ui): various ui fixes (#5606) 9d175cf9
* [ ] Yuan Tang: feat: Identifiable user agents in various Argo commands (#5624) b4ce78bb
* [ ] Luciano Sá: docs: server runs over https (#5604) 13fa6524
* [ ] Vlad Losev: feat(executor): Support accessing output parameters by PNS executor running as non-root (#5564) 22a8e93c
* [ ] Vivek Kumar: add -o short option for argo cli get command (#5533) 2baae1dc
* [x] Saravanan Balasubramanian: fix(controller): Workflow hangs indefinitely during ContainerCreating if the Pod or Node unexpectedly dies (#5585) 0edd32b5
* [x] tczhao: feat(ui): let workflow dag and node info scroll independently (#5603) d0a0289e
* [ ] Yuan Tang: fix: Improve error message when missing required fields in resource manifest (#5578) 2651bd61
* [ ] Yuan Tang: feat: Support security token for OSS artifact driver (#5491) 4f3bbdcb
* [ ] Yuan Tang: docs: Add badge to @argoproj Twitter handle (#5590) 5f51e6d7
* [x] Vladimir Ivanov: fix: parse username from git url when using SSH key auth (#5156) 9b6c8b45
* [x] Simon Behar: fix(controller): Consider nested expanded task in reference (#5594) 7276bc39
* [ ] Jiaxin Shan: docs: Add ByteDance as user (#5593) 79eb50b4
* [ ] Rand Xie: docs: Add Robinhood as user (#5589) c941ef8b
* [ ] Alex Collins: build: Add make nuke; speed-up make start (#5583) 1dbae739

**Comment by alexec** [comment]
done

**Comment by alexec** [comment]
@simster7 I just added another one (the dockefile v1.2). I needed this for Dataflow deployments, and I expect we need it for WFs.

**Comment by simster7** [comment]
> @simster7 I just added another one (the dockefile v1.2). I needed this for Dataflow deployments, and I expect we need it for WFs.

Done, thank you
