### ISSUE TITLE
v3.0.3 cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#5820]
- [ ] Peixuan Ding: feat(cli): resubmit workflows by label and field selector (#5807) 507b92cf9

- [ ] Yuan Tang: chore: Surface parse duration error in operator (#5814) 3f808661c
- [ ] Nicoló Lino: docs: fix typo in async-pattern page (#5810) a65cc3e27
- [ ] Radolumbo: fix: Add note about hyphenated variables (#5805) bdd44c723
- [ ] Peixuan Ding: feat(cli): Retry workflows by label selector and field selector (#5795) b9a79e065
- [x] markterm: fix: Node set updating global output parameter updates global. #5699 (#5700) 8f2acee32
- [ ] Peixuan Ding: feat(controller): Add validation for ContainerSet (#5758) 076ff18a8
- [x] Yuan Tang: fix: Reset workflow started time to current when retrying workflow. Fixes #5796 (#5798) 4b3a30f4e
- [ ] Peixuan Ding: build: fix codegen failure on master branch (#5799) 418395b7f
- [x] Wen-Chih (Ryan) Lo: fix: change log level to warn level (#5790) 4af011318
- [ ] Alex Collins: test: Refactoring test JSON marshalling. (#5785) 0283fafd0
- [ ] AIKAWA: fix(docs): Fix yaml snippet (#5788) 7e974dcda
- [ ] sa-: docs: fix typo (#5781) 01f37b81d
- [ ] Yuan Tang: feat: Support bucket lifecycle for OSS artifact driver (#5731) 4a55e6f0b
- [ ] kennytrytek: feat: Emit WorkflowNodeRunning Event (#5531) 3cdb22a1e
- [ ] Niklas Hansson: upgrade github.com/gogo/protobuf (#5780) 66c770993
- [ ] Iven: chore: Prevent free-port.sh from killing browsers (#5791) 26f08c10a
- [ ] Alex Collins: docs: Add training doc (#5777) 4aff34c9c
- [ ] dinever: fix(ui): Fix an UI dropdown flickering issue (#5772) cb55cba07
- [ ] Christophe Blin: docs: Update managed-namespace.md (#5768) 9dd3c6a49
- [ ] dinever: feat(cli): Stop workflows by label selector and field selector (#5752) 60a64c825
- [ ] Yuan Tang: docs: Redirect Argo community documents to argoproj/argoproj (#5734) 0efb57d0c
- [ ] dinever: fix(ui): Fix the UI crashing issue (#5751) 05af5edfc
- [x] Radolumbo: fix(ui): Remove the ability to change namespaces via the UI in Managed Namespace Mode. Closes #5577 (#5729) 407740046
- [ ] dinever: fix(ui): Fix workflow summary page unscrollable issue (#5743) 2a050348b
- [ ] Michael Crenshaw: chore: Fix expr array equality operator (#5744) 11e045dca
- [x] Michael Ruoss: fix(ui): Fix greediness in regex for auth token replacement (#5746) 500d93387
- [ ] dinever: fix(server): Fix the issue where GetArtifact didn't look for input artifacts (#5705) 284adfe16
- [ ] dinever: fix(ui): Fix workflow list table column width mismatch (#5736) 511bbed2b
- [ ] Tianchu Zhao: chore(url): move edge case paths to /argo-workflows/ (#5730) 0a1bff19d
- [ ] Yuan Tang: fix(executor): Remove unnecessary check on resource group (#5723) 2b8740943
- [ ] Brandon: docs: Added clarifying points for multi-namespace usage (#5725) e387b41f3
- [ ] Alex Collins: ci: Fix argoexec-dev target (#5714) 0ebf6c0a4

**Comment by alexec** [comment]
done

**Comment by alexec** [comment]
@sarabala1979 these commits may have not been backported to v3.0.2 - can you please make sure it makes it into v3.0.3?

e3d1d1e822c01e2765bab2d57d9537849cd0f720
4c3b0ac530acaac22abb453df3de09e8c74068fb

**Comment by alexec** [comment]
Can we also add:

461b0b3cda111da1461c217d4a375c9e8a6fba50

**Comment by alexec** [comment]
And we need to also add this to fix the build:

Alex Collins: ci: Fix argoexec-dev target (#5714) 0ebf6c0

**Comment by alexec** [comment]
We should also add  e332be5.

**Comment by ppapasani1** [comment]
@sarabala1979 Can you please include #5678 in this version. #5736  and #5678 and related, they both should go in the same release. Thanks

**Comment by alexec** [comment]
- [ ] 418395b7f build: fix codegen failure on master branch (#5799)
- [ ] 4b3a30f4e fix: Reset workflow started time to current when retrying workflow. Fixes #5796 (#5798)
- [ ] 076ff18a8 feat(controller): Add validation for ContainerSet (#5758)
- [ ] 8f2acee32 fix: Node set updating global output parameter updates global. #5699 (#5700)
- [ ] b9a79e065 feat(cli): Retry workflows by label selector and field selector (#5795)
- [ ] bdd44c723 fix: Add note about hyphenated variables (#5805)
- [ ] a65cc3e27 docs: fix typo in async-pattern page (#5810)
- [ ] 3f808661c chore: Surface parse duration error in operator (#5814)
- [ ] 507b92cf9 feat(cli): resubmit workflows by label and field selector (#5807)
- [ ] 5ba08ed81 docs: wrong parent name of 'wait-approval' step (#5815)
- [ ] 461b0b3cd fix(executor): Fix artifactory saving files. Fixes #5733 (#5775)
- [ ] a4d275af1 docs: Fix emptyDir pattern example. Fixes #5825 (#5826)
- [ ] 86545f63e 5739 (#5797)
- [ ] 5ff48bbc5 feat: Allow to toggle GZip implementations in docker executor (#5698)
- [ ] c59f59ad0 feat: Support Arguments in Exit Handler (#5455)
- [ ] e332be5ec fix(ui): dont show cluster workflows in namespaced mode. Closes #5841 (#5846)
- [ ] 8f59af532 ci: Run Snyk on `go.mod` (#5787)
- [ ] ab786ecba fix: Reset started time for each node to current when retrying workflow (#5801)
- [ ] 7ec262a56 feat(cli): Support input from device files for lint command (#5851)
- [ ] d66954f5b feat(controller): Add config for potential CPU hogs (#5853)
- [ ] 2b3396fad feat: configurable windows os version (#5816)
- [ ] c6825acca fix(executor): Enable PNS executor to better kill sidecars. Fixes #5779 (#5794)
- [ ] 206aff005 docs: Added organization (#5856)
- [ ] 1a5393593 fix(controller): Remove un-safe Sprig funcs. Fixes #5286 (#5850)
- [ ] d3eb5bc6f (origin/master, master) docs: Add FAQs in memoization doc and add link in the err message (#5847)
