### ISSUE TITLE
v3.0.4

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5896]
- [x]  fix(ui): Fix workflow summary page unscrollable issue (#5743)
- [x] bug related to "pod deleted" #5811
- [x] pod spec jumbling #e71d33c
- [x] Alex Collins: fix(controller): Fix pod spec jumbling. Fixes #5897 (#5899) e71d33c54
- [ ] Jan Heylen: fix: workflow-controller: use parentId (#5831) 9a10bd475
- [ ] Alex Collins: build!: Automatically add manifests to `v*` tags (#5880) 3fff791e4
- [ ] Alex Collins: test: 3m faster and more robust e2e (#5883) be207a97f
- [ ] Iven: docs: Fix typo (#5884) 23175b6be
- [ ] jsato8094: docs: Added a period to the end of the sentence (#5869) 6487afb4e
- [ ] Alex Collins: build: Draft releases automatically (#5867) d86d458b1
- [ ] Saravanan Balasubramanian: fix(controller): Fix active pods count in node pending status with pod deleted. (#5836) 2687e240c
- [ ] Alex Collins: fix(controller): Error template ref exit handlers. Fixes #5835 (#5837) 3428b832d
- [ ] Yuan Tang: docs: Add FAQs in memoization doc and add link in the err message (#5847) d3eb5bc6f
- [ ] Alex Collins: fix(controller): Remove un-safe Sprig funcs. Fixes #5286 (#5850) 1a5393593
- [ ] Caue Augusto dos Santos: docs: Added organization (#5856) 206aff005
- [x] Alex Collins: fix(executor): Enable PNS executor to better kill sidecars. Fixes #5779 (#5794) c6825acca
- [ ] Michael Weibel: feat: configurable windows os version (#5816) 2b3396fad
- [x] Alex Collins: feat(controller): Add config for potential CPU hogs (#5853) d66954f5b
- [ ] Kevin Hwang: feat(cli): Support input from device files for lint command (#5851) 7ec262a56
- [ ] Yuan Tang: fix: Reset started time for each node to current when retrying workflow (#5801) ab786ecba
- [ ] Alex Collins: ci: Run Snyk on `go.mod` (#5787) 8f59af532
- [x] Radolumbo: fix(ui): dont show cluster workflows in namespaced mode. Closes #5841 (#5846) e332be5ec
- [ ] Saravanan Balasubramanian: feat: Support Arguments in Exit Handler (#5455) c59f59ad0
- [ ] Yuan Tang: feat: Allow to toggle GZip implementations in docker executor (#5698) 5ff48bbc5
- [ ] alexey: 5739 (#5797) 86545f63e
- [ ] Yuan Tang: docs: Fix emptyDir pattern example. Fixes #5825 (#5826) a4d275af1
- [x] Alex Collins: fix(executor): Fix artifactory saving files. Fixes #5733 (#5775) 461b0b3cd
- [ ] Nicoló Lino: docs: wrong parent name of 'wait-approval' step (#5815) 5ba08ed81
- [ ] Peixuan Ding: feat(cli): resubmit workflows by label and field selector (#5807) 507b92cf9
- [ ] Yuan Tang: chore: Surface parse duration error in operator (#5814) 3f808661c
- [ ] Nicoló Lino: docs: fix typo in async-pattern page (#5810) a65cc3e27
- [ ] Radolumbo: fix: Add note about hyphenated variables (#5805) bdd44c723
- [ ] Peixuan Ding: feat(cli): Retry workflows by label selector and field selector (#5795) b9a79e065
- [ ] markterm: fix: Node set updating global output parameter updates global. #5699 (#5700) 8f2acee32
- [ ] Peixuan Ding: feat(controller): Add validation for ContainerSet (#5758) 076ff18a8

**Comment by alexec** [comment]
I've marked some that need adding. I think there are some duplicates/already backported.

**Comment by heyleke** [comment]
Will "Jan Heylen: fix: workflow-controller: use parentId" be taken along in v3.0.4? Or do I misinterprete the once not marked?
