### ISSUE TITLE
v3.0.5

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5969]
`git log --oneline -n10 --grep ^fix master `

- [x] d55a8dbb8 feat(controller): Add liveness probe (#5875)
- [ ] 46dcaea53 fix(controller): Lock nodes in pod reconciliation. Fixes #5979 (#5982)
- [x] 60b6b5cf6 fix(controller): Empty global output param crashes (#5931)
- [x] 453086f94 fix(ui): ensure that the artifacts property exists before inspecting it (#5977)
- [ ] 7b54b182c small fixes of spelling mistakes (#5886)
- [x] 56b71d07d fix(controller): Revert cb9676e88857193b762b417f2c45b38e2e0967f9. Fixes #5852 (#5933)
- [ ] e05f7cbe6 fix(controller): Suspend and Resume is not working in WorkflowTemplateRef scenario (#5802)
- [ ] 8fde4e4f4 fix(installation): Enable capacity to override namespace with Kustomize (#5907)
- [x] e71d33c54 fix(controller): Fix pod spec jumbling. Fixes #5897 (#5899)
- [ ] 9a10bd475 fix: workflow-controller: use parentId (#5831)
- [ ] 2687e240c fix(controller): Fix active pods count in node pending status with pod deleted. (#5836)
- [ ] 3428b832d fix(controller): Error template ref exit handlers. Fixes #5835 (#5837)
- [ ] 1a5393593 fix(controller): Remove un-safe Sprig funcs. Fixes #5286 (#5850)
- [x] c6825acca fix(executor): Enable PNS executor to better kill sidecars. Fixes #5779 (#5794)

```
 git log --oneline -n10 --grep ^fix release-3.0
06744da67 fix(ui): Fix workflow summary page unscrollable issue (#5743)
d3ed51e7a fix(controller): Fix pod spec jumbling. Fixes #5897 (#5899)
d9e583a12 fix: Fix active pods count in node pending status with pod deleted. (#5898)
80142b120 fix(controller): Error template ref exit handlers. Fixes #5835 (#5837)
8a4a3729d fix(executor): Enable PNS executor to better kill sidecars. Fixes #5779 (#5794)
a4c246b2b fix(ui): dont show cluster workflows in namespaced mode. Closes #5841 (#5846)
910f552de fix: certs in non-root (#5476)
f6493ac36 fix(executor): Fix artifactory saving files. Fixes #5733 (#5775)
6c16cec61 fix(controller): Enable metrics server on stand-by  controller (#5540)
0ae8061c0 fix: Node set updating global output parameter updates global. #5699 (#5700)
```

**Comment by alexec** [comment]
https://argoproj.github.io/argo-workflows/releasing/
