### ISSUE TITLE
v3.1.0-rc14

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6124]
- [ ] 44dc1aabc (origin/master, master) docs: Add note on the requirements of resource templates. Fixes #5566 (#6125)
- [ ] b5bd0242d Update events.md (#6119)
- [x] a497e82e0 fix(executor): Fix docker not terminating. Fixes #6064 (#6083)
- [x] 1d76c4815 (tmp) feat(manifests): add 'app' label to workflow-controller-metrics service (#6079)
- [x] 1533dd467 fix(executor): Fix emissary kill. Fixes #6030 (#6084)
- [ ] 7c55ef53d docs: Document v3.2 upgrading (alpine) (#6106)
- [ ] fe47c8a98 docs: updated CHANGELOG.md (#6104)
- [ ] 25c67243c docs: Update upgrading.md (#6105)
- [ ] e7808afd3 docs: add Glovo to users (#6098)
- [ ] c18305893 build: Fix `make codegen` (#6090)
- [ ] 245764eab chore(executor): Adjust resource JSON object log to debug level (#6100)
- [ ] 00b56e543 fix(executor): Fix `kubectl` permission error (#6091)
- [ ] 7dc6515ce Point to latest stable release (#6092)
- [ ] be63efe89 feat(executor)!: Change `argoexec` base image to alpine. Closes #5720 (#6006)
- [ ] 937bbb9d9 feat(executor): Configurable interval for wait container to check container statuses. Fixes #5943 (#6088)
- [ ] c111b4294 fix(executor): Improve artifact error messages. Fixes #6070 (#6086)
- [ ] 391cafb13 docs: Document default values for the environment variables (#6087)
- [ ] eddd42014 docs: Update bug_report.md
- [ ] 2ce30b737 docs: Add link to changelog in release notes (#6085)
- [ ] 53bd960b6 Update upgrading.md

**Comment by alexec** [comment]
@sarabala1979 anything else to add to v3.1?
