### ISSUE TITLE
v3.0.8 cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#6126]
- [ ] Denis Bellotti: Update events.md (#6119) b5bd0242d
- [x] Alex Collins: fix(executor): Fix docker not terminating. Fixes #6064 (#6083) a497e82e0
- [ ] Daan Seynaeve: feat(manifests): add 'app' label to workflow-controller-metrics service (#6079) 1d76c4815
- [ ] Alex Collins: fix(executor): Fix emissary kill. Fixes #6030 (#6084) 1533dd467
- [ ] Alex Collins: docs: Document v3.2 upgrading (alpine) (#6106) 7c55ef53d
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6104) fe47c8a98
- [ ] Alex Collins: docs: Update upgrading.md (#6105) 25c67243c
- [ ] Carlos Montemuino: docs: add Glovo to users (#6098) e7808afd3
- [ ] Alex Collins: build: Fix `make codegen` (#6090) c18305893
- [ ] Yuan Tang: chore(executor): Adjust resource JSON object log to debug level (#6100) 245764eab
- [ ] Alex Collins: fix(executor): Fix `kubectl` permission error (#6091) 00b56e543
- [ ] Kaito Ii: Point to latest stable release (#6092) 7dc6515ce
- [ ] Alex Collins: feat(executor)!: Change `argoexec` base image to alpine. Closes #5720 (#6006) be63efe89
- [ ] Yuan Tang: feat(executor): Configurable interval for wait container to check container statuses. Fixes #5943 (#6088) 937bbb9d9
- [ ] Alex Collins: fix(executor): Improve artifact error messages. Fixes #6070 (#6086) c111b4294
- [ ] Yuan Tang: docs: Document default values for the environment variables (#6087) 391cafb13
- [ ] Alex Collins: docs: Update bug_report.md eddd42014
- [ ] Yuan Tang: docs: Add link to changelog in release notes (#6085) 2ce30b737
- [ ] Alex Collins: Update upgrading.md 53bd960b6
- [ ] Simon Behar: feat: Add TaskSet CRD and HTTP Template (#5628) 493595a78
- [ ] Alex Collins: docs: Document upgrading. Fixes #6076 (#6081) 687da78b5
- [ ] Alex Collins: fix(ui): Tweak workflow log viewer (#6074) 4bb4d528e
- [x] Saravanan Balasubramanian: fix(controller): Handling panic in leaderelection (#6072) f8f63e628
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6075) 4f4b78e4f
- [ ] Yuan Tang: fix(executor): Fix compatibility issue when selfLink is no longer populated for k8s>=1.21. Fixes #6045 (#6014) 803855bc9
- [ ] Alex Collins: feat(ui): Add text filter to logs. Fixes #6059 (#6061) 1f3493aba
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6058) f1fcb43b6
- [ ] Yuan Tang: fix(controller): Only clean-up pod when both main and wait containers have terminated. Fixes #5981 (#6033) eaeaec71f
- [ ] Alex Collins: chore: Remove build/chore/ci/docs/test and merge commits from CHANGEL… (#6057) 232d97ed3
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6054) 0a0935ceb
- [ ] Alex Collins: fix(ui): Add editor nav and make taller (#6047) ee283ee6d
- [ ] Simon Behar: docs: Must use k8sapi to run on GKE Autopilot (#6046) d8ab07a27
- [ ] Aayush Rangwala: docs: Add VMware to USERS.md (#6048) 50dc542be
- [ ] Kasper Aaquist Johansen: fix(ui): Changed placing of chat/get help button. Fixes #5817 (#6016) 529c30dd5
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6040) c8b7ef1a5
- [ ] Alex Collins: feat(controller): Add per-namespace parallelism limits. Closes #6037 (#6039) e262b3afd
- [ ] Alex Collins: feat(controller): Support rate-limitng pod creation. (#4892) 73539fadb
- [ ] Alex Collins: fix(server): Only hydrate nodes if they are needed. Fixes #6000 (#6004) e566c106b
- [ ] Yuan Tang: docs: Update Go version to 1.15 in local dev guide (#6035) c21af210a
- [ ] Alex Collins: ci: Dry-run publish-release on master (#6029) 2e70ff2f9
- [ ] Stephan van Maris: fix(ui): typo (#6027) d218ea717
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6026) 02be24228
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6025) c3895e4ce
- [ ] Peixuan Ding: fix(ui): Fix link for archived logs (#6019) bad615550
- [ ] Alex Collins: docs: Add FAQ (#6023) 2d077e4d5
- [ ] Alex Collins: revert: "fix(executor): Fix compatibility issue with k8s>=1.21 when s… (#6012) 3cfc96b7c
- [ ] Alex Collins: fix(controller): Increase readiness timeout from 1s to 30s (#6007) 7e27044b7
- [ ] Antony Chazapis: feat: Pass include script output as an environment variable (#5994) 79f5fa5f3
- [ ] Christophe Blin: Mention that 'archive' do not support logs of pods (#6005) d7517cfca
- [ ] Alex Collins: ci: only run changelog job on tag (#6003) 6cda063ac
- [ ] Yuan Tang: fix(executor): Fix compatibility issue with k8s>=1.21 when selfLink is no longer populated (#5992) d7c5cf6c9
- [ ] Yuan Tang: fix(validate): Fix DAG validation on task names when depends/dependencies is not used. Fixes #5993 (#5998) a2c6241ae
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#5999) 8b2561502
- [ ] amit: docs: Correct quoting. Fixes #5957 (#6001) 516c54a7f
- [ ] Alex Collins: fix(controller): Fix sync manager panic. Fixes #5939 (#5991) a99d5b821
- [ ] William Reed: fix(executor): resource patch for non-json patches regression (#5951) 80f8473a1
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#5989) 7cebfc5c8
- [ ] Alex Collins: fix(controller): Listen on :6060 (#5988) f3d95821f
- [ ] Simon Behar: docs: Update releasing.md (#5803) ffd429ea9
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#5986) c8ffc9700
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#5985) 75ceb9bf3
- [ ] Alex Collins: feat(controller): Add liveness probe (#5875) d55a8dbb8
- [ ] Alex Collins: fix(controller): Lock nodes in pod reconciliation. Fixes #5979 (#5982) 46dcaea53
- [ ] Saravanan Balasubramanian: fix(controller): Empty global output param crashes (#5931) 60b6b5cf6
- [ ] dherman: fix(ui): ensure that the artifacts property exists before inspecting it (#5977) 453086f94
- [ ] Alex Collins: docs: update bug_report.md (#5971) 079a506e4
- [ ] Maximilian Roos: docs: fix indentation (#5970) adda0e46e
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#5968) 7a8d16c0d
- [ ] Caelan U: docs: Fix typo on examples page, add link to GH directory (#5961) e6e8dec95
- [ ] Zach Aller: feat: add disableSubmodules for git artifacts (#5910) 67a38e33e
- [ ] Johannes Olsson: docs: Update code of conduct link. (#5872) 4dd8d4b98
- [ ] Lars Kerick: small fixes of spelling mistakes (#5886) 7b54b182c
- [ ] Lars Kerick: docs: fixed typo (#5890) edb5933ab
- [ ] Alex Collins: docs: correct workflow-pod-security-context.md (#5949) b42c3e2ff
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#5945) 766127941
- [ ] Alex Collins: fix(controller): Revert cb9676e88857193b762b417f2c45b38e2e0967f9. Fixes #5852 (#5933) 56b71d07d
- [ ] Alex Collins: docs: Correct the order of versions in the CHANGELOG.md (#5941) 8cb0e5c7d
- [ ] Michael Crenshaw: chore: fix whitespace issue (#5940) 3659e679e
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#5932) f0540a9ba
- [ ] Saravanan Balasubramanian: fix(controller): Suspend and Resume is not working in WorkflowTemplateRef scenario (#5802) e05f7cbe6
- [ ] Daverkex: fix(installation): Enable capacity to override namespace with Kustomize (#5907) 8fde4e4f4
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#5924) 37e75b5f9
- [ ] Alex Collins: ci: fixes to changelog generation (#5923) 304ab5261
- [ ] Everton: feat: DAG/TASK Custom Metrics Example (#5894) 128861c50
- [ ] Alex Collins: ci: Add correct title to CHANGELOG.md PRs (#5915) 830a159e6
- [ ] Jerguš Lejko: Update configure-artifact-repository.md (#5909) 0acaf3b40
- [ ] Alex Collins: docs: Change `http` to `https` for argo-server. Fixes #5866 (#5904) 948c28465
- [ ] github-actions[bot]: docs:Changes by create-pull-request action (#5913) f8bff12e2

**Comment by alexec** [comment]
done - just 1 from me

**Comment by sarabala1979** [comment]
- [ ] Brandon High: docs: Remove RBAC for SSO from Roadmap (Already implemented) (#6174) 991d8641c
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6160) b8109bbea
- [ ] Reijer Copier: fix(controller): dehydrate workflow before deleting offloaded node status (#6112) 9fe8c1085
- [ ] Yuan Tang: fix(controller): Allow retry on transient errors when validating workflow spec. Fixes #6163 (#6178) 510b4a816
- [ ] Stefan Sedich: feat(server): Allow redirect_uri to be automatically resolved when using sso (#6167) 4f847e099
- [ ] Simon Behar: docs: Use 'depends' instead of 'dependencies' in examples (#6166) dd19e49f0
- [ ] Simon Behar: feat(ui): Add checkbox to check all workflows in list. Fixes #6069 (#6158) 95ad561ae
- [ ] Alex Collins: test: Fix logging test (#6159) d0487cae2
- [ ] Alex Collins: fix(ui): Fix event-flow scrolling. Fixes #6133 (#6147) 43f68f4aa
- [ ] Alex Collins: fix(executor): Capture emissary main-logs. Fixes #6145 (#6146) 9f0cdbdd7
- [ ] Alex Collins: fix(ui): Fix-up local storage namespaces. Fixes #6109 (#6144) 963bed34b
- [ ] Caden: docs: Update Graviti's website link (#6148) fd6ac088a
- [ ] Alex Collins: docs: Fix release-notes.md 0a16a5210
- [ ] Alex Collins: fix(controller): Performance improvement for Sprig. Fixes #6135 (#6140) 80599325f
- [ ] kennytrytek: fix: Allow setting workflow input parameters in UI. Fixes #4234 (#5319) 868868ee2
- [ ] Yuan Tang: chore: Upgrade Alibaba OSS to use more secure ListObjectsV2() (#6142) f3fe565bf
- [ ] Alex Collins: chore: Update stress rig and docs. Fixes #6136 (#6141) 48e394d16
- [ ] meijin: build image output to docker (#6128) 357429635
- [ ] Christophe Blin: docs: Document the extraction of data from a k8s resource (#6102) 1332c59ab
- [ ] Alex Collins: build: Remove PNS_PRIVILEGED=true (#6138) f2fde4e0e
- [ ] Yuan Tang: fix(executor): Check whether any errors within checkResourceState() are transient. Fixes #6118. (#6134) b38fd1404
- [ ] Luces Huayhuaca: add troubleshooting notes section for running-locally docs (#6132) db95dbfa1
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6127) 16839620c
- [ ] Yuan Tang: docs: Add note on the requirements of resource templates. Fixes #5566 (#6125) 44dc1aabc

**Comment by alexec** [comment]
I've checked two more items.
