### ISSUE TITLE
v3.1.0 cherry-pick

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6185]
git log --oneline v3.1.0-rc14..master|grep -v 'docs\|feat\|build'

- [ ] d0487cae2 test: Fix logging test (#6159)
- [ ] 43f68f4aa fix(ui): Fix event-flow scrolling. Fixes #6133 (#6147)
- [ ] 9f0cdbdd7 fix(executor): Capture emissary main-logs. Fixes #6145 (#6146)
- [ ] 963bed34b fix(ui): Fix-up local storage namespaces. Fixes #6109 (#6144)
- [ ] 80599325f fix(controller): Performance improvement for Sprig. Fixes #6135 (#6140)
- [ ] 868868ee2 fix: Allow setting workflow input parameters in UI. Fixes #4234 (#5319)
- [ ] f3fe565bf chore: Upgrade Alibaba OSS to use more secure ListObjectsV2() (#6142)
- [ ] b38fd1404 fix(executor): Check whether any errors within checkResourceState() are transient. Fixes #6118. (#6134)
- [ ] b5bd0242d Update events.md (#6119)
- [ ] a497e82e0 fix(executor): Fix docker not terminating. Fixes #6064 (#6083)
- [ ] 1533dd467 fix(executor): Fix emissary kill. Fixes #6030 (#6084)
- [ ] 245764eab chore(executor): Adjust resource JSON object log to debug level (#6100)
- [ ] 00b56e543 fix(executor): Fix `kubectl` permission error (#6091)
- [ ] 7dc6515ce Point to latest stable release (#6092) Fixes #5943 (#6088)
- [ ] c111b4294 fix(executor): Improve artifact error messages. Fixes #6070 (#6086)
- [ ] 53bd960b6 Update upgrading.md

**Comment by alexec** [comment]
@sarabala1979 @terrytangyuan please check any that you want back-porting to v3.1.0 GA.

**Comment by terrytangyuan** [comment]
I have no permission to edit the list but could you please cherry-pick the following to v3.1.0 GA?
* b38fd14 fix(executor): Check whether any errors within checkResourceState() are transient. Fixes #6118. (#6134)
* f3fe565 chore: Upgrade Alibaba OSS to use more secure ListObjectsV2() (#6142)
*  245764e chore(executor): Adjust resource JSON object log to debug level (#6100)

**Comment by alexec** [comment]
`FAIL: TestCLISuite/TestLogProblems`
