### ISSUE TITLE
v3.0.1 cherry-pick

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6241]
- [x] 19da54109 fix(conttroller): Always set finishedAt dote. Fixes #6135 (#6139)
- [ ] 92eb8b766 fix: Reduce argoexec image size (#6197) NO
- [x] 8d3627d3f fix: Fix certain sibling tasks not connected to parent (#6193)
- [ ] 4fd38facb fix: Fix security issues related to file closing and paths (G307 & G304) (#6200) NO
- [ ] cecc379ce refactor: Remove the need for pod annotations to be mounted as a volume (#6022) NO
- [ ] 0e94283ae fix(server): Fix issue with auto oauth redirect URL in callback and handle proxies (#6175) NO
- [x] 0cc5a24c5 fix(controller): Wrong validate order when validate DAG task's argument (#6190) 
- [x] 9fe8c1085 fix(controller): dehydrate workflow before deleting offloaded node status (#6112)
- [x] 510b4a816 fix(controller): Allow retry on transient errors when validating workflow spec. Fixes #6163 (#6178)

**Comment by alexec** [comment]
[v3.1 builds](https://github.com/argoproj/argo-workflows/actions/workflows/ci-build.yaml?query=branch%3Arelease-3.1)
