### ISSUE TITLE
v3.1.2 cherry-pick 

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#6330]
- [x] Alex Collins: feat(controller): Store artifact repository in workflow status. Fixes #6255 (#6299) 85c9279a9
- [ ] Denis Bellotti: docs: code format (#6269) 088c48b8d
- [ ] brgoode: require sso redirect url to be an argo url (#6211) d07d933be
- [ ] Byungjin Park (Claud): docs: Fix typo (#6311) e790e2276
- [ ] Alex Collins: fix(cli): Only list needed fields. Fixes #6000 (#6298) c2360c4c4
- [ ] Michael Crenshaw: docs: docs and hacks improvements (#6310) 4de976c71
- [ ] Tianchu Zhao: docs(controller): add missing emissary executor (#6291) 126701476
- [x] Yuan (Bob) Gong: fix(executor): emissary - make /var/run/argo files readable from non-root users. Fixes #6238 (#6304) c11584940
- [x] Alex Collins: fix(executor): Tolerate docker re-creating containers. Fixes #6244 (#6252) c9246d3d4
- [ ] Michael Crenshaw: docs: add json destructuring example (#6250) fa4b32a53
- [ ] Niklas Hansson: docs: fix end of files, new lines and remove multiple lines (#6240) 100c79bdc
- [ ] Yuan Tang: ci: Add Go code security scanner via gosec. Fixes #6203 (#6232) 97f2c50cd
- [ ] Simon Behar: feat: Introduce when condition to retryStrategy (#6114) f78b759cf
- [ ] Yuan (Bob) Gong: fix(executor): emissary - make argoexec executable from non-root containers. Fixes #6238 (#6247) 05c901fd4
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6242) f79d1694c
- [ ] Alex Collins: docs: update bug report template (#6236) 43212590d
- [ ] Stefan Sedich: feat: Add support for deletion delay when using PodGC (#6168) 73a36d8bf

**Comment by alexec** [comment]
I've checked 3 items.

**Comment by sarabala1979** [comment]
- [ ] Saravanan Balasubramanian: fix(cli): v3.1 Argo Auth Token (#6344) 3db467e6b
- [ ] Saravanan Balasubramanian: fix(controller): Not updating StoredWorkflowSpec when WFT changed during workflow running (#6342) d7c09778a
- [ ] Alex Collins: ci: only run Snyk once a day on master dbb537a26
- [ ] Alex Collins: chore: deleted wft.yaml aeed93669
- [ ] Yuan Tang: feat(controller): Differentiate CronWorkflow submission vs invalid spec error metrics (#6309) 7c38fb01b
- [ ] Michael Crenshaw: docs: document how to access hyphenated steps in expression templates (#6318) dd4855966
- [ ] Valér Orlovský: docs: document using ingress with TLS enabled (#6324) e2c7f4a7d
