### ISSUE TITLE
v3.1.3 Cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#6435]
- [ ] jibuji: fix: support archive.none for OSS directory artifacts (#6312) 40b08240d
- [x] Saravanan Balasubramanian: fix(controller): Same workflow nodes are not executing parallel even semaphore locks available (#6418) 7ec5b3ea9
- [x] Saravanan Balasubramanian: fix(controller): Randomly expr expression fail to resolve (#6410) c29b275d5
- [ ] Yuan (Bob) Gong: docs(executor): emissary executor also runs on GKE autopilot (#6430) f1792f68c
- [ ] Huan-Cheng Chang: fix(controller/cli): Resolve global artifacts created in nested workflows (#6422) dd3c11252
- [ ] Antoine Dao: fix(emissary): throw argo error on file not exist (#6392) b17d1bf7b
- [x] Alex Collins: fix(executor): Remove 15s guard for Docker executor. Fixes #6415 (#6427) 946e4a4a6
- [ ] Luces Huayhuaca: chore: upgrade to k8s v0.20.4 (#6143) 96b165e18
- [x] Alex Collins: fix(executor): remove unused import preventing compilation 29ebc2a6a
- [ ] Joe McGovern: feat(controller): opt-in to sending pod node events as pod (#6377) cc701a1af
- [ ] Tianchu Zhao: feat(artifact): enable gcs ListObjects (#6409) 959ce6b7f
- [ ] Alex Collins: chore: correct CODEOWNERS syntax 896600648
- [ ] Alex Collins: chore: add @alexec as proto codeowner f47ada3cd
- [x] Yuan (Bob) Gong: fix(executor/emissary): fix nonroot sidecars + input/output params & artifacts (#6403) 30e2518c2
- [x] Saravanan Balasubramanian: fix(controller): Global parameter is not getting updated (#6401) 4da8fd940
- [ ] Alex Collins: docs: updated sidecar-injection.md c4bdc217e
- [x] Alex Collins: fix(controller): Force main container name to be "main" as per v3.0. Fixes #6405 (#6408) f2d24b1d9
- [ ] Tianchu Zhao: fix(executor): fix GCS artifact retry (#6302) 2df5f66a3
- [ ] Dominik Deren: docs: updating documentation on how to setup IRSA on AWS (#6406) c80f4bc73
- [ ] Alex Collins: docs: Updating upgrading.md. Closes #6314 10c0fa5f9
- [x] Alex Collins: fix(controller): Mark workflows wait for semaphore as pending. Fixes #6351 (#6356) 092b4271b
- [x] Tianchu Zhao: fix(controller): allow initial duration to be 0 instead of current_time-0 (#6389) 453539690
- [ ] Yuan Tang: docs: Add note on additional required permission for createBucketIfNotPresent for OSS driver (#6378) 2bf711b32
- [ ] Thiago Bittencourt Gil:  docs: Add 4intelligence (#6400) b15a79cc3
- [x] Alexander Matyushentsev: fix: Server crash when opening timeline tab for big workflows (#6369) f4b89dc8e
- [ ] Alex Collins: Revert "fix: examples/ci.yaml indent (#6328)" 99359a095
- [ ] Antoine Dao: fix(gcs): throw argo not found error if key not exist (#6393) 66c441006
- [ ] Zadkiel: chore: import grafana dashboard (#6365) 2c2525981
- [ ] KUNG HO BACK: fix: examples/ci.yaml indent (#6328) 3f72fe506
- [ ] Tianchu Zhao: fix(controller): fix retry on transient errors when validating workflow spec (#6370) 9233a8de7
- [x] Tianchu Zhao: fix(controller): allow workflow.duration to pass validator (#6376) 488aec3ca
- [ ] Yuan Tang: feat(controller): Allow configurable host name label key when retrying different hosts (#6341) d6ec03238
- [x] Antoine Dao: fix(fields): handle nexted fields when excluding (#6359) bd5a8a99b
- [x] BOOK: feat(controller): sortDAGTasks supports sort by field Depends (#6307) cfab7db53
- [ ] Yuan Tang: fix(cli): Overridding name/generateName when creating CronWorkflows if specified (#6308) 6e58b35c3
- [ ] Tianchu Zhao: docs(users): Add WooliesX (#6358) 5f0d6ab87
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6348) 16308fa61
- [x] Tianchu Zhao: fix(crd): temp fix 34s timeout bug for k8s 1.20+ (#6350) b388c63d0
- [ ] Yuan Tang: docs: Add Alibaba Group to USERS.md (#6353) eced49411

**Comment by alexec** [comment]
@terrytangyuan do you want to mark any for OSS?
@tczhao there are a few fixes for GCS is this list. Do you think they should be included?

**Comment by alexec** [comment]
I'd like to include #6434, once it is merged.

**Comment by sarabala1979** [comment]
- [ ] Alex Collins: fix(controller): Reinstate support for outputs.results for containers. Fixes #6428 (#6434) 51c15764d

**Comment by terrytangyuan** [comment]
Nothing to include for OSS for this release but could you include the following commit?

Yuan Tang: feat(controller): Allow configurable host name label key when retrying different hosts #6341 d6ec032

**Comment by tczhao** [comment]
I'm keen to include the GCS fixes

- Tianchu Zhao: feat(artifact): enable gcs ListObjects (feat(executor): enable gcs artifact ListObjects, supports data-transformations #6409) 959ce6b
- Tianchu Zhao: fix(executor): fix GCS artifact retry (fix(executor): fix GCS artifact retry #6302) 2df5f66

**Comment by alexec** [comment]
Released!

**Comment by Bobgy** [comment]
Hi @alexec @sarabala1979, I think we missed cherry picking my first PR fix for emissary with nonroot: https://github.com/argoproj/argo-workflows/pull/6247/files. It's also required for running emissary with nonroot containers.

https://github.com/argoproj/argo-workflows/blob/release-3.1/workflow/executor/emissary/binary.go#L19

**Comment by sarabala1979** [comment]
@terrytangyuan  We already released v3.1.3. Which includes only the checked once.  Sorry, we missed your comments.  you might be commented after we start releasing process. I can do 3.1.4 this week. I will create cherry-pick issue tomorrow.

**Comment by Bobgy** [comment]
No worries, thank you for the quick response! Looking forward to the next release.
