### ISSUE TITLE
v3.1.4 cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#6468]
Few PRs are already released in v3.1.3.  Please select your PR that needs to release in v3.1.4

- [x] Saravanan Balasubramanian: fix: Exit template shouldn't fail with max parallelism reached (#6456) 5fde8fa72
- [x] Marcin Gucki: fix(controller): fix retry on different hosts (#6429) c5d2461cf
- [x] Peixuan Ding: fix(server): Fix nil pointer error when getting artifacts from a step without artifacts (#6465) 0f6f36270
- [ ] Daisuke Taniwaki: docs: Add ubie to users (#6462) a250bab02
- [ ] Mohammad Ali: feat(server): Support OIDC custom claims for AuthN. Closes #5953 (#6444) 903415249
- [x] Antoine Dao: fix(pods): set resources from script templates (#6450) 3e9d8373d
- [ ] Alex Collins: docs: add 30m to issue template (#6446) a39725d04
- [ ] Simon Behar: fix: Do not display clipboard if there is no text (#6452) 3abeb0120
- [ ] Saravanan Balasubramanian: feat(controller): HTTP Template and Agent support feature  (#5750) b16a0a098
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6438) 20efb5293
- [ ] dpeer6: feat(server): support changing MaxGRPCMessageSize using env variable (#6420) dc043ce87
- [ ] Alex Collins: fix(controller): Reinstate support for outputs.results for containers. Fixes #6428 (#6434) 51c15764d
- [ ] jibuji: fix: support archive.none for OSS directory artifacts (#6312) 40b08240d
- [ ] _**Saravanan Balasubramanian: fix(controller): Same workflow nodes are not executing parallel even semaphore locks available (#6418) 7ec5b3ea9**_
- [ ] _**Saravanan Balasubramanian: fix(controller): Randomly expr expression fail to resolve (#6410) c29b275d5**_
- [ ] Yuan (Bob) Gong: docs(executor): emissary executor also runs on GKE autopilot (#6430) f1792f68c
- [ ] Huan-Cheng Chang: fix(controller/cli): Resolve global artifacts created in nested workflows (#6422) dd3c11252
- [x] Antoine Dao: fix(emissary): throw argo error on file not exist (#6392) b17d1bf7b
- [ ] _**Alex Collins: fix(executor): Remove 15s guard for Docker executor. Fixes #6415 (#6427) 946e4a4a6**_
- [ ] Luces Huayhuaca: chore: upgrade to k8s v0.20.4 (#6143) 96b165e18
- [ ] **_Alex Collins: fix(executor): remove unused import preventing compilation 29ebc2a6a_**
- [ ] Joe McGovern: feat(controller): opt-in to sending pod node events as pod (#6377) cc701a1af
- [ ] Tianchu Zhao: feat(artifact): enable gcs ListObjects (#6409) 959ce6b7f
- [ ] Alex Collins: chore: correct CODEOWNERS syntax 896600648
- [ ] Alex Collins: chore: add @alexec as proto codeowner f47ada3cd
- [x] Yuan (Bob) Gong: fix(executor/emissary): fix nonroot sidecars + input/output params & artifacts (#6403) 30e2518c2
- [ ] **_Saravanan Balasubramanian: fix(controller): Global parameter is not getting updated (#6401) 4da8fd940_**
- [ ] Alex Collins: docs: updated sidecar-injection.md c4bdc217e
- [ ] _**Alex Collins: fix(controller): Force main container name to be "main" as per v3.0. Fixes #6405 (#6408) f2d24b1d9**_
- [x] Tianchu Zhao: fix(executor): fix GCS artifact retry (#6302) 2df5f66a3
- [ ] Dominik Deren: docs: updating documentation on how to setup IRSA on AWS (#6406) c80f4bc73
- [ ] Alex Collins: docs: Updating upgrading.md. Closes #6314 10c0fa5f9
- [ ] _**Alex Collins: fix(controller): Mark workflows wait for semaphore as pending. Fixes #6351 (#6356) 092b4271b**_
- [ ] **_Tianchu Zhao: fix(controller): allow initial duration to be 0 instead of current_time-0 (#6389) 453539690_**
- [ ] Yuan Tang: docs: Add note on additional required permission for createBucketIfNotPresent for OSS driver (#6378) 2bf711b32
- [ ] Thiago Bittencourt Gil:  docs: Add 4intelligence (#6400) b15a79cc3
- [ ] **_Alexander Matyushentsev: fix: Server crash when opening timeline tab for big workflows (#6369) f4b89dc8e_**
- [ ] Alex Collins: Revert "fix: examples/ci.yaml indent (#6328)" 99359a095
- [x] Antoine Dao: fix(gcs): throw argo not found error if key not exist (#6393) 66c441006
- [ ] Zadkiel: chore: import grafana dashboard (#6365) 2c2525981
- [ ] KUNG HO BACK: fix: examples/ci.yaml indent (#6328) 3f72fe506
- [ ] Tianchu Zhao: fix(controller): fix retry on transient errors when validating workflow spec (#6370) 9233a8de7
- [ ] Tianchu Zhao: fix(controller): allow workflow.duration to pass validator (#6376) 488aec3ca
- [ ] Yuan Tang: feat(controller): Allow configurable host name label key when retrying different hosts (#6341) d6ec03238
- [ ] **_Antoine Dao: fix(fields): handle nexted fields when excluding (#6359) bd5a8a99b_**
- [ ] BOOK: feat(controller): sortDAGTasks supports sort by field Depends (#6307) cfab7db53
- [ ] Yuan Tang: fix(cli): Overridding name/generateName when creating CronWorkflows if specified (#6308) 6e58b35c3
- [ ] Tianchu Zhao: docs(users): Add WooliesX (#6358) 5f0d6ab87
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6348) 16308fa61

**Comment by alexec** [comment]
@Bobgy can you mark the ones you needed again please?

**Comment by Bobgy** [comment]
Thanks!
I was talking about https://github.com/argoproj/argo-workflows/pull/6247.

**Comment by Bobgy** [comment]
I want this too

Yuan (Bob) Gong: fix(executor/emissary): fix nonroot sidecars + input/output params & artifacts (fix(executor/emissary): fix nonroot sidecars + input/output params & artifacts #6403) 30e2518

But I think it's already cherry picked

**Comment by sarabala1979** [comment]
@Bobgy I selected it. Do you have any more issues that need to be included in v3.1.4? I am planning to start release tomorrow

**Comment by Bobgy** [comment]
Thanks, I didn't hit any other issues so far.

I am just curious, I think some fixes like the following are generally good to have, but they are not picked at the moment. How do you decide?

Antoine Dao: fix(emissary): throw argo error on file not exist (fix(emissary): throw argo error on file not exist #6392) b17d1bf

 Alex Collins: fix(executor): Remove 15s guard for Docker executor. Fixes wait container won't exit #6415 (fix(executor): Remove 15s guard for Docker executor. Fixes #6415 #6427)

**Comment by sarabala1979** [comment]
- [ ] Simon Behar: fix: Consider onExit children of Retry nodes (#6451) 7ef0f4750

**Comment by Bobgy** [comment]
Hi @sarabala1979, I'm still not seeing my fix in #6247 cherrypicked into 3.1.4.
https://github.com/argoproj/argo-workflows/blob/247776d66fa6bf988f861ba82f181e386a972626/workflow/executor/emissary/binary.go#L19

**Comment by sarabala1979** [comment]
I did cherry pick and resolve conflict on windows file. Let me check.

**Comment by sarabala1979** [comment]
@Bobgy I miss understood. I was including Yuan (Bob) Gong: fix(executor/emissary): fix nonroot sidecars + input/output params & artifacts (fix(executor/emissary): fix nonroot sidecars + input/output params & artifacts #6403) 30e2518.
I missed your comment saying the issue is not on the list. 
finally, find it https://github.com/argoproj/argo-workflows/commit/05c901fd4f622aa9aa87b3eabfc87f0bec6dea30
somewhat it was missed in 3.1.3 also.  I am releasing v3.1.5

**Comment by Bobgy** [comment]
Yes, it's a different PR. Sorry I split my fix into multiple PRs in the first place. I see it makes it more confusing than necessary.
I'll test more cases in the initial PR next time. : )
