### ISSUE TITLE
Trail of Bits

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6520]
https://github.com/argoproj/argoproj/blob/master/docs/argo_security_final_report.pdf

- [x] TOB-ARGO-006 Unhandled deferred file close operations- quick-start only https://github.com/argoproj/argo-workflows/issues/5312
- [x] TOB-ARGO-007 MinIO container runs as root - quick-start only https://github.com/argoproj/argo-workflows/issues/5860
- [ ] TOB-ARGO-008. File extension comparisons are case sensitive - informational
- [x] TOB-ARGO-009 HTTP used by default for Web UI - fixed in https://github.com/argoproj/argo-workflows/issues/5206
- [x] #6972
- [x] #6973
- [x] #6974
- [ ] TOB-ARGO-014 Git artifact fetcher does not validate revision names - informational
- [x] #6522
- [ ] TOB-ARGO-020 Incorrect logging of command arguments in the RunCommandExt convenience function - informational
- [ ] TOB-ARGO-031 he WaitPID function is vulnerable to a PID-reuse attack - informational 
- [x] TOB-ARGO-034 Argo projects do not provide documentation for release cycle - fixed in https://github.com/argoproj/argo-workflows/issues/5379
- [x] #6521

Also

* https://github.com/argoproj/argo-workflows/issues/5206
* https://github.com/argoproj/argo-workflows/issues/8370
* https://github.com/argoproj/argo-workflows/issues/5205
* https://github.com/argoproj/argo-workflows/issues/5215 - low severity
* https://github.com/argoproj/argo-workflows/issues/5216 - low severity
* https://github.com/argoproj/argo-workflows/issues/5217 - medium severity
* https://github.com/argoproj/argo-workflows/issues/5861

**Comment by alexec** [comment]
@sarabala1979 please can you double-check I've correctly identified all issues?

**Comment by alexec** [comment]
All serious issues have been done.
