### ISSUE TITLE
v3.1.6 cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#6530]
- [x] Saravanan Balasubramanian: fix: Fix the Status update for node with synchronization lock (#6525) 903ce68ff
- [x] Alex Collins: fix: Upgrade pkg to v0.10.1. Fixes #6521 (#6523) a38460342
- [ ] Saravanan Balasubramanian: fix(controller): fix tasket warning in Non-HTTP Template scanerio (#6518) 0670f652c
- [ ] Alex Collins: docs: update PR template 863d22631
- [ ] Ivan Karol: docs: Update argo-server-auth-mode.md (#6487) 7648585b5
- [ ] Tetsuya Shiota: fix: PROFILE=SSO to PROFILE=sso for case-sensitive filesystem (#6502) 32970f4cd
- [x] William Van Hevelingen: fix(controller): Fix panic in addParamToGlobalScope (#6485) 3d5ac9b2b
- [ ] Tetsuya Shiota: feat(ui): use dl tag instead of p tag in user-info ui (#6505) d1d96b0a6
- [ ] Sebastian Nyberg: Add link to latest release in installation.md (#6509) 5b8f7977a
- [ ] steve-marmalade: build: Fix changelog script to display the tag creation date (#6510) 8b69ec452
- [ ] wanghong230: docs: Update the Auth doc default mode (#6514) f886ff974
- [x] Yuan (Bob) Gong: fix(executor/docker): re-revert -- fix random errors with message "No such container:path". Fixes #6352 (#6508) 24bb1b77a
- [x] Alex Collins: fix: Remove client private key from client auth REST config (#6506) e2e822dd5
- [ ] Alex Collins: docs: Correct CHANGELOG.md 8d60296f6
- [ ] Alex Collins: Revert "fix(executor/docker): fix random errors with message "No such container:path". Fixes #6352 (#6483)" a3fd704a1
- [ ] Alex Collins: docs: Update installation guide 745c1cfcb
- [ ] Saravanan Balasubramanian: fix(controller): Delete the PVCs in workflowtemplateRef (#6493) a105b137c
- [ ] Joe McGovern: feat: Annotate pod events with workflow name and UID (#6455) 3373dc512
- [ ] Kyle Prager: docs: specifying that metadata header name must be lowercase to match selector in WorkflowEventBinding (#6496) c6b6f67a5
- [ ] Yuan (Bob) Gong: fix(executor/docker): fix random errors with message "No such container:path". Fixes #6352 (#6483) e4a53d4bf
- [x] Michael Crenshaw: fix(controller): JSON-unmarshal marshaled expression template before evaluating (#6285) 2a2ecc916
- [ ] Alex Collins: build: Fix build. Fixes #6484 (#6486) 7bf825bfc
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6477) 764cc97bd
- [ ] Alex Collins: feat(controller): Inline templates. Closes #5105 (#5749) ec9641531
- [ ] Simon Behar: fix: Consider onExit children of Retry nodes (#6451) 7ef0f4750
- [ ] Alex Collins: feat!: Upgrade to Golang 1.16. Fixes #5563 (#6471) 7f2c58972
- [ ] Geoffrey Huntley: docs(users): add gitpod (#6466) 94244243c
- [ ] Alex Collins: docs: Document running at massive scale. Fixes #6443 (#6459) a457da364

**Comment by alexec** [comment]
done

**Comment by Bobgy** [comment]
Can I ask for cherry pick  Yuan (Bob) Gong: fix(executor/docker): re-revert -- fix random errors with message "No such container:path". Fixes Random failures with message "Error: No such container:path: ... This does not look like a tar archive tar" #6352 (fix(executor/docker): re-revert -- fix random errors with message "No such container:path". Fixes #6352 #6508)?

**Comment by Marks-Ed** [comment]
Reckon I could sneak https://github.com/argoproj/argo-workflows/pull/6512 in or will that need to wait until 3.1.7?

**Comment by sarabala1979** [comment]
> Reckon I could sneak #6512 in or will that need to wait until 3.1.7?

we will include it

- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6524) 88520891a
- [x] Ed Marks: fix: use execWf when setting PodMetadata (#6512) dc4f0a172
- [ ] Henrik Blixt: docs: TOB-ARGO-TM16: Update Quickstart guide (#6515) 333df2b1f
- [ ] Miles Croxford: docs(users): add arabesque (#6533) 047ae4f5e

**Comment by Bobgy** [comment]
Thank you!
