### ISSUE TITLE
v3.1.9  cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#6654]
- [x] Saravanan Balasubramanian: fix(controller): Set finishedAt for workflow with Daemon steps (#6650) a147f178d
- [x] Alex Collins: fix: Do not index complete workflow semaphores (#6639) 5522d4b4c
- [x] Jesse Suen: fix: `argo node set` panic: index out of range and correct docs (#6653) 2ac3c48d3
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6652) 946a9c3f7
- [ ] Yuan Tang: feat(controller): Add a shared index informer for ConfigMaps (#6644) 6d46fd9f8
- [ ] Alex Collins: docs: correct https://bit.ly/book-30m-with-argo-team URL 20cb10fa1
- [ ] Alex Collins: feat: Upgrade dataflow to v0.0.98 (#6637) 91abb47db
- [ ] Alex Collins: build: Fix repository prefix (#6636) 64e5ab70c
- [ ] Saravanan Balasubramanian: fix: Fixed typo in clusterrole (#6626) d8b90f2b8
- [ ] Yuan Tang: docs: Fix incorrect link to examples (#6630) 563cd3195
- [ ] Alex Collins: fix: Upgrade Dataflow to v0.0.96 (#6622) 51307e11e
- [ ] Curtis Vogt: ci: Build Docker manifest with complete dep list (#6621) d4fe87356
- [ ] Andrey Melnikov: fix: Argo Workflow specs link to not go to raw content (#6624) f1c188f3e
- [ ] J.P. Zivalich:  docs: Add slack exit handler example. Resolves #4152  (#6612) 07e29263a
- [x] smile-luobin: fix(controller): Initialize throttler during starting workflow-controller. Fixes: #6599 (#6608) 29cf73548
- [ ] Alex Collins: docs: Remove sym-links from docs (#6617) e10f6448e
- [ ] Simon Behar: docs: Document #6297 breaking change (#6616) 2c7182798
- [ ] Alex Collins: build: disable UI by default for `make start` 1c25a249d
- [ ] Alex Collins: chore: Run `make codegen` d19909a29
- [ ] Tetsuya Shiota: fix: manifests/quick-start/sso for running locally PROFILE=sso (#6503) a394a91f5
- [ ] Siebjee: docs: fix continue on failure dag example (#6609) 0ab5c28e4
- [ ] Michael Pöllath: docs: Fix template-defaults duplicated in docs and add missing whitespace in h1 (#6601) 4fb382e6f
- [ ] Alex Collins: fix: Fix `gosec` warnings, disable pprof by default. Fixes #6594 (#6596) 8678f007e
- [ ] Alex Collins: docs: Document IP address logging. Fixes #5216 3411407f1
- [ ] Alex Collins: docs: Document auth rate limiting. Fixes #5217 77f477d1f
- [ ] Alex Collins: chore: Upgrade cobra to v1.2.1  (#6597) 530c21d3c
- [ ] Alex Collins: fix!: Enable authentication by default on Argo Server `/metrics` endpoint. Fixes #6592 (#6595) 3aac377e2
- [ ] Yuan Tang: ci: Disable builds on forks (#6589) be07a8a5a
- [ ] Yuan Tang: fix(executor): Disambiguate PNS executor initialization log (#6582) 656639666
- [ ] Yuan Tang: fix: Fix unit test with missing createRunningPods() (#6585) d6f5acb40
- [ ] Simon Behar: chore: Remove onExit naming transition scaffolding code (#6297) 48d7ad36c
- [ ] Alex Collins: feat: upgrade argo-dataflow to v0.0.90 (#6563) b0e050e54
- [ ] Josh Soref: docs: Add period (#6580) 33b0f7a31
- [x] Antoine Dao: fix(gcs): backoff bool should be false if error is transient (#6577) 30340c427
- [ ] Yuan Tang: feat(artifact): Allow to set bucket logging for OSS artifact driver (#6554) 1e34cec88
- [ ] Luciano Sá: docs: fixed typo (#6573) 58130cf4a
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6575) 7c365b9f5
- [ ] Gage Orsburn: feat: Adding SSO support for Okta. Fixes #6165 (#6572) 3595ac59c
- [ ] Saravanan Balasubramanian: fix: Panic in getTemplateOutputsFromScope (#6560) f1cf7ee03
- [x] Windfarer: fix(executor/pns): panic of pidFileHandles concurrent writes (#6569) 64fbf6955
- [ ] Alex Collins: ci: Allow 8m  for unit tests on CI ec10f6a1a
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6567) b70fbb6cc
- [ ] Alex Collins: fix: Fix `x509: certificate signed by unknown authority` error (#6566) ae7eeeb50
- [ ] Alex Collins: docs: Updated CHANGELOG.md f9d8fd801
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6562) 2ffe865bd
- [x] Yuan (Bob) Gong: fix(executor/docker): fix failed to wait for main container to complete: timed out waiting for the condition: container does not exist (#6561) 205d233cd
- [ ] Yuan Tang: ci: Run gosec as part of golangci lint step (#6555) 1fd861a7e
- [ ] Aaron Mell: feat: S3 Encryption At Rest (#6549) d41c03702
- [x] David Collom: fix: Generate TLS Certificates on startup and only keep in memory (#6540) 478d79469
- [ ] Yuan Tang: build: Add missing libcap binary to fix argoexec image build (#6559) 5464c4c7b
- [ ] Yuan Tang: build: Switch to use kustomize subcommand in kubectl (#6546) 15e1db9ea
- [ ] wanghong230: fix: use golangci-lint v1.37.0 to support apple M1 (#6548) f711ce4d5
- [ ] wanghong230: fix: replace docker.io with quay.io to avoid the image pull limit (#6539) 37395d681
- [ ] Tom Meadows: fix: argo-sever mistype (#6543) a1a8d4421
- [ ] Alex Collins: feat: Show Argo Dataflow pipelines in the UI (#5742) a57b3ad9e
- [ ] Alex Collins: test: Skip TestGetPodByNode. See #6458 c27f668d9
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6538) 702736a29
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6524) 88520891a
- [x] Ed Marks: fix: use execWf when setting PodMetadata (#6512) dc4f0a172
- [ ] Henrik Blixt: docs: TOB-ARGO-TM16: Update Quickstart guide (#6515) 333df2b1f
- [ ] Miles Croxford: docs(users): add arabesque (#6533) 047ae4f5e

**Comment by alexec** [comment]
Done. Some might only be for v3.2, so if you get merge conflict, then they might not need backporting.

**Comment by sarabala1979** [comment]
@alexec do you think we can include this fix https://github.com/argoproj/argo-workflows/pull/6639? it is a great to fix for performance

**Comment by alexec** [comment]
> @alexec do you think we can include this fix #6639? it is a great to fix for performance

If you like.

**Comment by sarabala1979** [comment]
- [ ] Saravanan Balasubramanian: fix(cli): Added validatation for StartAt, FinishedAt and ID (#6661) 929351267
- [ ] Yuan Tang: chore: Remove unnecessary wf.yaml at top-level directory (#665

5) e1a1b81cc
