### ISSUE TITLE
v3.1.11 cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#6721]
- [ ] 大雄: fix: kill sidecar timeout issue (#6700) 0b3f62cbe
- [ ] Tianchu Zhao: feat(ui): logsViewer use archived log if node finish and archived (#6708) cf14cad41
- [x] Tianchu Zhao: fix(ui): undefined cron timestamp (#6713) 3ba7d5fd6
- [x] Saravanan Balasubramanian: fix: panic in prepareMetricScope (#6720) 4c9c92292
- [x] Tianchu Zhao: fix(executor): handle hdfs optional artifact at retriving hdfs file stat (#6703) d1299ec80
- [ ] Damian Czaja: feat: Provide context to NewAPIClient (#6667) 11657fe16
- [ ] Tianchu Zhao: feat: archivewf add name filter. Fixes #5824 (#6706) a1cc0f557
- [ ] Tianchu Zhao: fix(ui): report phase button alignment (#6707) 1e31eb856
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6701) fd5350023
- [ ] Alex Collins: fix: run Snyk on UI. Fixes #6604 (#6651) d45395b6f
- [ ] Tianchu Zhao: fix(ui): button margin (#6699) 2e174bd4c
- [ ] Elliot Maincourt: fix(emissary): strip trailing slash from artifact src before creating… (#6696) 4b5d7ecfd
- [ ] Yuan Tang: feat: Support loading parameter values from configmaps (#6662) 28c8dc7a9

**Comment by jacek-jablonski** [comment]
Possible to include [cf14cad](https://github.com/argoproj/argo-workflows/commit/cf14cad41e1a8428cae8382398ee778892e63198)?

**Comment by sarabala1979** [comment]
@jacek-jablonski v3.1.11 is already released. I can include this next release. Please let me know how critical this issue is for you.
