### ISSUE TITLE
v3.1.13 cherry pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#6820]
- [x] Saravanan Balasubramanian: fix: Missing duration metrics if controller restart (#6815) ffb0db711
- [ ] Tianchu Zhao: feat(controller): add workflow level archivedLogs. Fixes #6663 (#6802) 81bfa21eb
- [ ] Yuan Tang: docs: Fix link to community survey (#6797) 44fd7140b
- [ ] Andrey Velichkevich: docs: Add Cisco to list of users (#6796) e188fe188
- [ ] ygelfand: fix: update outdated links for cli (#6791) 6995d682d
- [ ] Anthony Scott: docs: Additional details added to workflow archive doc pages (#6787) 9be0882e3
- [ ] Philippe Richard: fix(lint): checking error for viper command flag binding (#6788) b35aabe86
- [ ] Philippe Richard: feat: Add env vars config for argo-server and workflow-controller (#6767) 96c562649
- [x] Alex Collins: fix: Fix expression template random errors. Fixes #6673 (#6786) 7a7171f46
- [ ] Alex Collins: build: fix UI param c8bbdd756
- [ ] Julian Fleischer: docs: Add "incrmntal" to list of users (#6784) 50a1c7a08
- [ ] Tianchu Zhao: fix(controller): fix template archivelocation-archivelog behaviour (#6754) 067576ed7
- [ ] tooptoop4: fix(ui): workflow event binding typo (#6782) d747fc5ea
- [x] smile-luobin: fix: Fix bugs, unable to resolve tasks aggregated outputs in dag outputs. Fixes #6684 (#6692) 9dc33f617
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6780) 65565a1f3
- [ ] Tianchu Zhao: fix(controller): TestPodExists unit test, add delay to wait for informer getting pod info (#6783) 954292d50
- [ ] William Van Hevelingen: chore: Update k8s to v0.21.4 (#6558) 2c81aaa70
- [ ] Alex Collins: docs: updated issue templates 63aecdb0b
- [ ] Alex Collins: docs: added regression report 3d0f5f5ed
- [ ] Alex Collins: docs: add `triage` label to bug report b8223e51b
- [ ] Alex Collins: docs: added labels to bug report 7770f3c2a
- [ ] TCgogogo: fix: fix a typo in example file dag-conditional-artifacts.yaml (#6775) 710e82366
- [ ] Alex Collins: feat: upgrade Argo Dataflow to v0.0.104 (#6749) b82884600
- [ ] Brewster Malevich: docs: Fix bad callout render in quick-start docs (#6762) 9cb25d95a
- [ ] Tianchu Zhao: fix(controller): TestPodExists unit test (#6763) 1a76e6581
- [ ] yyyyyy888: docs: Add Sutpc company into the user list. (#6764) 96afac1ef
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6745) bc21183af
- [ ] Stephen Raghunath: docs: Fix indentation describing how steps work (#6738) 7684ef4a0
- [ ] Saravanan Balasubramanian: fix: Daemond status stuck with Running (#6742) 6875479db
- [ ] J.P. Zivalich: feat: Add template node to pod name. Fixes #1319 (#6712) e5b131a33
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6734) 9936cf680
- [ ] Joshua Carp: fix: correct minor typos in docs (#6722) 69e438426
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6723) a449b4772
- [ ] Yuan Tang: docs: Fix link to examples in website (#6730) a82f42f27
- [ ] Tianchu Zhao: fix(executor): allow emptyRepo artifact input. Fixes #5857 (#6711) ae5398698
- [x] Anish Dangi: fix: remove windows UNC paths from wait/init containers. Fixes #6583 (#6704) e57249e64

**Comment by alexec** [comment]
done
