### ISSUE TITLE
v3.2.1 cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#6951]
- [x] J.P. Zivalich: fix(ui): Change pod names to new format. Fixes #6865 (#6925) 67fe87ba9
- [x] Saravanan Balasubramanian: fix: BASE_HREF ignore (#6926) 1bcfa1aa5
- [x] Micah Beeman: fix(controller): Fix getPodByNode, TestGetPodByNode. Fixes #6458 (#6897) 41515d65c
- [ ] Yuan Tang: docs: Fix demonstration of using existing ConfigMap in memoization cache (#6920) 9efc9e8fc
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6914) a29d0c639
- [x] Alex Collins: fix: do not delete expr tag tmpl values. Fixes #6909 (#6921) 5a7708c2c
- [ ] Tianchu Zhao: feat(ui): label autocomplete for report tab (#6881) 2fd4b8aad
- [ ] Alex Collins: build: simplify using Golang 1.16 (#6893) 606011b1c
- [ ] Tianchu Zhao: feat(ui): resume on selected node. Fixes #5763 (#6885) c5b1533d3
- [ ] Yuan Tang: docs: Add notes to params from configmap examples (#6894) 26cf5e3f4
- [ ] Saravanan Balasubramanian: fix: Parameter with Value and Default (#6887) ef6aad617
- [x] zorulo: fix: Resource requests on init/wait containers. Fixes #6809 (#6879) 4d38404df
- [ ] Tianchu Zhao: fix(ui): fixed width button (#6883) cca4792c5
- [ ] Tianchu Zhao: feat(server): archivedWf add namePrefix search. Fixes #6743 (#6801) b54809771
- [ ] Tianchu Zhao: feat: add autocomplete for labels for archived workflow (#6776) 689ad6818
- [ ] Yuan Tang: docs: Update ecosystem section (#6878) efa11e0e9
- [ ] Alex Collins: build: upgrade mockery to v2 (#6877) a9ea0a541
- [x] Hong Wang: fix: upgrade sprig to v3.2.2 (#6876) c962bb189
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6872) 26cbbada1
