### ISSUE TITLE
v3.1.14 cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#6975]
- [ ]  J.P. Zivalich: fix(ui): Change pod names to new format. Fixes Cannot view logs in UI for multi-template workflows #6865 (fix(ui): Change pod names to new format. Fixes #6865 #6925) 67fe87b
- [ ]  Saravanan Balasubramanian: fix: BASE_HREF ignore (fix: BASE_HREF ignore #6926) 1bcfa1a
- [ ]  Micah Beeman: fix(controller): Fix getPodByNode, TestGetPodByNode. Fixes TestGetPodByNode is flakey #6458 (fix(controller): Fix getPodByNode, TestGetPodByNode. Fixes #6458 #6897) 41515d6
- [ ]  Yuan Tang: docs: Fix demonstration of using existing ConfigMap in memoization cache (docs: Fix demonstration of using existing ConfigMap in memoization cache #6920) 9efc9e8
- [ ]  github-actions[bot]: docs: updated CHANGELOG.md (docs: updated CHANGELOG.md #6914) a29d0c6
- [ ]  Alex Collins: fix: do not delete expr tag tmpl values. Fixes Cannot refer to some parameters from expression template #6909 (fix: do not delete expr tag tmpl values. Fixes #6909 #6921) 5a7708c
- [ ]  Tianchu Zhao: feat(ui): label autocomplete for report tab (feat(ui): label autocomplete for report tab #6881) 2fd4b8a
- [ ]  Alex Collins: build: simplify using Golang 1.16 (build: simplify using Golang 1.16 #6893) 606011b
- [ ]  Tianchu Zhao: feat(ui): resume on selected node. Fixes Can the resume function only target a node,not target a workflow #5763 (feat(ui): resume on selected node. Fixes #5763 #6885) c5b1533
- [ ]  Yuan Tang: docs: Add notes to params from configmap examples (docs: Add notes to params from configmap examples to reduce user errors #6894) 26cf5e3
- [ ]  Saravanan Balasubramanian: fix: Parameter with Value and Default (fix: Parameter with Value and Default #6887) ef6aad6
- [ ]  zorulo: fix: Resource requests on init/wait containers. Fixes Executor resource requests not applied to init/wait containers #6809 (fix: Resource requests on init/wait containers. Fixes #6809 #6879) 4d38404
- [ ]  Tianchu Zhao: fix(ui): fixed width button (fix(ui): fixed width button. Fixes #4973 #6883) cca4792
- [ ]  Tianchu Zhao: feat(server): archivedWf add namePrefix search. Fixes Possibility to search archived workflows by name #6743 (feat(server): archivedWf add namePrefix search. Fixes #6743 #6801) b548097
- [ ]  Tianchu Zhao: feat: add autocomplete for labels for archived workflow (feat: add autocomplete for labels for archived workflow #6776) 689ad68
- [ ]  Yuan Tang: docs: Update ecosystem section (docs: Update ecosystem section #6878) efa11e0
- [ ]  Alex Collins: build: upgrade mockery to v2 (build: upgrade mockery to v2 #6877) a9ea0a5
- [ ]  Hong Wang: fix: upgrade sprig to v3.2.2 (fix: upgrade sprig to v3.2.2 #6876) c962bb1
- [ ]  github-actions[bot]: docs: updated CHANGELOG.md (docs: updated CHANGELOG.md #6872) 26cbbad
