### ISSUE TITLE
v3.2.2 cherry pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#7002]
- [ ] J.P. Zivalich: fix: Restore default pod name version to v1 (#6998) 86ddda592
- [ ] Tianchu Zhao: fix(artifact)!: default https to any URL missing a scheme. Fixes #6973 (#6985) 0446f521d
- [ ] Alex Collins: docs: update default executor (#6996) 9ca9d2e68
- [ ] Alex Collins: docs: Mention #6712 in upgrading guide (#6992) 0d43e2ee2
- [ ] Zadkiel: fix(typo): correct typo in event-dispatch error log (#6688) cfdebf64e
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#6977) 6b696f465
- [ ] NextNiclas: fix: OAuth2 callback with self-signed Root CA. Fixes #6793 (#6978) 2a15853ec
- [ ] Fabrice Jammes: docs: Update empty-dir.md (#6987) a2d15c349
- [ ] smile-luobin: feat: fix workflow configmap argument cannot be referenced as local variable. Fixes #6869 (#6898) 6384e5f21
- [ ] NextNiclas: fix: Allow self-signed Root CA for SSO. Fixes #6793 (#6961) 72356abad
- [ ] Yuan Tang: docs: Add myself to list of approvers (#6963) 3c5c52723
- [ ] Tianchu Zhao: feat(ui): add label filter to template workflow (#6955) e1fe5b58a
- [ ] Yuan Tang: docs: Add Akuity to the list of users (#6969) 193e9ea37
- [ ] Miroslav Tomasik: fix: response on canceled workflow action (#6859) (#6967) c705294c9
- [ ] William Van Hevelingen: docs: Fix typo in pr template (#6965) b6369dcb0
- [ ] SalvadorC: fix: Unreachable code in util/tls/tls.go. Fixes  #6950 (#6960) cf9a6cdd0
- [ ] Arthur Sudre: fix: multi-steps workflow (#6957) 6e1f2505a
- [ ] J.P. Zivalich: chore(ui): Move pod name functions and add tests. Fixes #6946 (#6954) 1239ba8ef
- [ ] Saravanan Balasubramanian: chore: Upgrade argo event 1.15 (#6932) d815031dc
- [ ] Peter Evers: fix(docs): fix data transformation example (#6901) 452433989
- [ ] Alex Collins: ci: increase lint timeout from 6m ot 10m 20ac307a9
- [ ] Bob Haddleton: fix(executor): add test for non-root user creating a script (#6905) 73d60108b
- [ ] Iven: fix: Skip empty withParam tasks. Fixes #6834 (#6912) 79d03a920
- [ ] Tianchu Zhao: feat(executor): default executor to emissary. Fixes #6785 (#6882) b0d1f6583
