### ISSUE TITLE
v3.2.3 cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#7070]
- [ ] Julien Duchesne: feat: Add user's email in the server gatekeeper logs (#7062) 60f2ae95e
- [ ] Tianchu Zhao: fix: Unit test TestNewOperation order of pipeline execution maybe different to order of submit (#7069) 31bf57b64
- [ ] Tianchu Zhao: docs(cli): fix cron delete flag description (#7058) 18c953df6
- [x] Saravanan Balasubramanian: fix: Precedence of ContainerRuntimeExecutor and ContainerRuntimeExecutors (#7056) 4734cbc44
- [x] Alex Collins:  feat: Bring Java client into core.  (#7026) 56ee94147
- [ ] Saravanan Balasubramanian: fix: Memozie for Step and DAG level (#7028) 65ff89ac8
- [ ] Joshua Carp: docs: Make cost optimization docs less aws-specific. (#7049) 8fb40f7ce
- [ ] Joyce Piscos: feat: Upgrade to Golang 1.17 (#7029) 8d7ca73b0
- [ ] Alex Collins: test: disable `TestDoNotCreatePodsUnderStopBehavior` for `docker` executor. Fixes #7040 (#7048) 3979f40d7
- [ ] Ziv Levi: fix: Support RFC3339 in creationTimeStamp. Fixes #6906 (#7044) 0baa4a203
- [ ] Tianchu Zhao: feat(ui): add label/state filter to cronworkflow. Fixes #7034 (#7035) 25e1939e2
- [ ] Alex Collins: feat(server): Sync dispatch of webhook events by default. Fixes #6981 and #6732 (#6995) 0758eab11
- [ ] William Van Hevelingen: docs: Add contributor meeting information and fix slack channel (#7031) d3442472e
- [x] Alex Collins: fix: Minor corrections to Swagger/JSON schema (#7027) ba472e131
- [ ] Alex Collins: docs: Fix docs build. Fixes #7023 (#7024) 93c301dff
- [ ] Joshua Carp: docs: Document "offload node status is not supported" error. (#7005) 74145734e
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#7019) 54af93ca5
- [ ] momom-i: feat: add unknown pod watch error explanation to FAQ.md (#6988) 182b696df
- [ ] Tianchu Zhao: fix(controller): use correct pod.name in retry/podspecpatch scenario. Fixes #7007 (#7008) 3f0a531aa
- [ ] Tianchu Zhao: feat(ui): wider stroke width for selected node (#7000) 6a674e7cb
- [ ] Tianchu Zhao: fix(ui): labels in report/archive should be sorted (#7009) 7f5262338
- [x] smile-luobin: fix(controller): fix bugs in processing retry node output parameters. Fixes #6948 (#6956) 50813daaf
- [ ] Alex Collins: docs: Document container set resource requests (#6997) 7ed515419
- [ ] Joshua Carp: docs: Document template default merge behavior. (#7003) a276e86ab
- [ ] Joshua Carp: docs: Document synchronization mutex usage. (#7006) de91209f1
