### ISSUE TITLE
v3.2.4 cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#7171]
- [ ] Julien Duchesne: feat: Add user's email in the server gatekeeper logs (#7062) 60f2ae95e
- [ ] Tianchu Zhao: fix: Unit test TestNewOperation order of pipeline execution maybe different to order of submit (#7069) 31bf57b64
- [ ] Tianchu Zhao: docs(cli): fix cron delete flag description (#7058) 18c953df6
- [x] Saravanan Balasubramanian: fix: Precedence of ContainerRuntimeExecutor and ContainerRuntimeExecutors (#7056) 4734cbc44
- [ ] Alex Collins:  feat: Bring Java client into core.  (#7026) 56ee94147
- [x] Saravanan Balasubramanian: fix: Memozie for Step and DAG level (#7028) 65ff89ac8
- [ ] Joshua Carp: docs: Make cost optimization docs less aws-specific. (#7049) 8fb40f7ce
- [ ] Joyce Piscos: feat: Upgrade to Golang 1.17 (#7029) 8d7ca73b0
- [ ] Alex Collins: test: disable `TestDoNotCreatePodsUnderStopBehavior` for `docker` executor. Fixes #7040 (#7048) 3979f40d7
- [ ] Ziv Levi: fix: Support RFC3339 in creationTimeStamp. Fixes #6906 (#7044) 0baa4a203
- [ ] Tianchu Zhao: feat(ui): add label/state filter to cronworkflow. Fixes #7034 (#7035) 25e1939e2
- [ ] Alex Collins: feat(server): Sync dispatch of webhook events by default. Fixes #6981 and #6732 (#6995) 0758eab11
- [ ] William Van Hevelingen: docs: Add contributor meeting information and fix slack channel (#7031) d3442472e
- [ ] Alex Collins: fix: Minor corrections to Swagger/JSON schema (#7027) ba472e131
- [ ] Alex Collins: docs: Fix docs build. Fixes #7023 (#7024) 93c301dff
- [ ] Joshua Carp: docs: Document "offload node status is not supported" error. (#7005) 74145734e
- [ ] github-actions[bot]: docs: updated CHANGELOG.md (#7019) 54af93ca5
- [ ] momom-i: feat: add unknown pod watch error explanation to FAQ.md (#6988) 182b696df
- [x] Tianchu Zhao: fix(controller): use correct pod.name in retry/podspecpatch scenario. Fixes #7007 (#7008) 3f0a531aa
- [ ] Tianchu Zhao: feat(ui): wider stroke width for selected node (#7000) 6a674e7cb
- [ ] Tianchu Zhao: fix(ui): labels in report/archive should be sorted (#7009) 7f5262338
- [x] smile-luobin: fix(controller): fix bugs in processing retry node output parameters. Fixes #6948 (#6956) 50813daaf
- [ ] Alex Collins: docs: Document container set resource requests (#6997) 7ed515419
- [ ] Joshua Carp: docs: Document template default merge behavior. (#7003) a276e86ab
- [ ] Joshua Carp: docs: Document synchronization mutex usage. (#7006) de91209f1

**Comment by iulianionita-ai** [comment]
Could you, please include in 3.2.4 https://github.com/argoproj/argo-workflows/pull/7084 ?

**Comment by yasselavila** [comment]
Please, if you can include #7084 it would be very nice. Thanks

**Comment by sarabala1979** [comment]
Sure

**Comment by book987** [comment]
Hi, Could you please include #6912 ? Thanks

**Comment by alexec** [comment]
Please add:

Bob Haddleton: fix(executor): add test for non-root user creating a script ( fix(executor): change script file permissions to 0o644 and add test for non-root user creating a script #6905) 73d6010

**Comment by alexec** [comment]
@sarabala1979 I think we should make, for patch release, all fixes are always added.

**Comment by simster7** [comment]
@sarabala1979 Any reason why only commits made before Oct 27 are included in this?

**Comment by alexec** [comment]
@sarabala1979 I think we might want an updated list? I get a different list of fixes:

```
git log v3.2.3..origin/master --oneline --grep 'fix.*:'
```

**Comment by sarabala1979** [comment]
> @sarabala1979 I think we might want an updated list? I get a different list of fixes:
> 
> ```
> git log v3.2.3..origin/master --oneline --grep 'fix.*:'
> ```
> 
> [0482964](https://github.com/argoproj/argo-workflows/commit/0482964d9bc09585fd908ed5f912fd8c72f399ff) fix(ui): Correctly show zero-state when CRDs not installed. Fixes #7001 (#7169) [f9e554d](https://github.com/argoproj/argo-workflows/commit/f9e554d268fd9dbaf0e07f8a10a8ac03097250ce) fix: Relative submodules in git artifacts. Fixes #7141 (#7162) [22af736](https://github.com/argoproj/argo-workflows/commit/22af7365049a34603cd109e2bcfa51eeee5e1393) fix: Reorder CI checks so required checks run first (#7142) [bd3be11](https://github.com/argoproj/argo-workflows/commit/bd3be115299708dc4f97f3559e6f57f38c0c0d48) fix: Return error when YAML submission is invalid (#7135) [209ff9d](https://github.com/argoproj/argo-workflows/commit/209ff9d9bd094e1c230be509d2444ae36b4ff04e) fix: Respect template.HTTP.timeoutSeconds (#7136) [02165aa](https://github.com/argoproj/argo-workflows/commit/02165aaeb83754ee15c635b3707b119a88ec43bd) fix(controller): default volume/mount to emissary (#7125) [3d59726](https://github.com/argoproj/argo-workflows/commit/3d597269e48215080e3318019f1d95ee01d7dacd) fix: typo in node-field-selector.md (#7116) [ca87f29](https://github.com/argoproj/argo-workflows/commit/ca87f2906995b8fecb796d94299f54f6dfbd6a41) fix: Daemon step in running state, but dependents don't start (#7107) [1e87159](https://github.com/argoproj/argo-workflows/commit/1e871595414d05e2b250bfa3577cf23b9ab7fa38) fix: Add pod name format annotation. Fixes #6962 and #6989 (#6982) [c5de76b](https://github.com/argoproj/argo-workflows/commit/c5de76b6a2d7b13c6ac7bc798e5c7615bf015de1) fix: Format issue on WorkflowEventBinding parameters. Fixes #7042 (#7087) [64fce4a](https://github.com/argoproj/argo-workflows/commit/64fce4a827692cb67284d800ad92f1af37f654fc) fix: Ensure HTTP reconciliation occurs for onExit nodes (#7084) [d6a62c3](https://github.com/argoproj/argo-workflows/commit/d6a62c3e26d49ab752851be288bcd503386e8ff6) fix: Ensure HTTP templates have children assigned (#7082) [46767b8](https://github.com/argoproj/argo-workflows/commit/46767b86bc29cd8cb1df08fdcc0b5bb351c243f3) fix(ui): Correct HTTP connection in pipeline view (#7077) [201ba55](https://github.com/argoproj/argo-workflows/commit/201ba552557b9edc5908c5224471fec4823b3302) fix: add outputs.parameters scope to script/containerSet templates. Fixes #6439 (#7045) [31bf57b](https://github.com/argoproj/argo-workflows/commit/31bf57b643be995860ec77b942c2b587faa0b4ff) fix: Unit test TestNewOperation order of pipeline execution maybe different to order of submit (#7069) [4734cbc](https://github.com/argoproj/argo-workflows/commit/4734cbc44dedeb2c7e5984aab5dc9b0c846ff491) fix: Precedence of ContainerRuntimeExecutor and ContainerRuntimeExecutors (#7056) [65ff89a](https://github.com/argoproj/argo-workflows/commit/65ff89ac81a8350fb5c34043146fcb1ec4ffbf23) fix: Memozie for Step and DAG level (#7028) [0baa4a2](https://github.com/argoproj/argo-workflows/commit/0baa4a2039b981e1ca118a04ceb6ac6439a82d0d) fix: Support RFC3339 in creationTimeStamp. Fixes #6906 (#7044) [ba472e1](https://github.com/argoproj/argo-workflows/commit/ba472e1319d1a393107947aa6d5980906d1cb711) fix: Minor corrections to Swagger/JSON schema (#7027) [3f0a531](https://github.com/argoproj/argo-workflows/commit/3f0a531aa14142a5f4f749093b23f690c98eb41e) fix(controller): use correct pod.name in retry/podspecpatch scenario. Fixes #7007 (#7008) [7f52623](https://github.com/argoproj/argo-workflows/commit/7f526233824c5065c7a9ee63dac59f168f04f95d) fix(ui): labels in report/archive should be sorted (#7009) [50813da](https://github.com/argoproj/argo-workflows/commit/50813daaf5b718d143af84f0f5847273114734da) fix(controller): fix bugs in processing retry node output parameters. Fixes #6948 (#6956) [86ddda5](https://github.com/argoproj/argo-workflows/commit/86ddda592c4f432f629775908bc9b737ab920cde) fix: Restore default pod name version to v1 (#6998) [0446f52](https://github.com/argoproj/argo-workflows/commit/0446f521d045b542734ee11fafea99daa2ee3105) fix(artifact)!: default https to any URL missing a scheme. Fixes #6973 (#6985) [cfdebf6](https://github.com/argoproj/argo-workflows/commit/cfdebf64eed8b87bf0f84f4284323e72f6d14cbb) fix(typo): correct typo in event-dispatch error log (#6688) [2a15853](https://github.com/argoproj/argo-workflows/commit/2a15853ec32701dd2dbccea2cc735d8334da1680) fix: OAuth2 callback with self-signed Root CA. Fixes #6793 (#6978) [72356ab](https://github.com/argoproj/argo-workflows/commit/72356abad157b26905be9251c654413b5eb9e6c7) fix: Allow self-signed Root CA for SSO. Fixes #6793 (#6961) [c705294](https://github.com/argoproj/argo-workflows/commit/c705294c9813b496b2de5c2ecd6f578d86a329b6) fix: response on canceled workflow action (#6859) (#6967) [cf9a6cd](https://github.com/argoproj/argo-workflows/commit/cf9a6cdd098901873ac584db649b694041530eb2) fix: Unreachable code in util/tls/tls.go. Fixes #6950 (#6960) [6e1f250](https://github.com/argoproj/argo-workflows/commit/6e1f2505a18e427d3a39fadafad2fd83f6eff521) fix: multi-steps workflow (#6957) [4524339](https://github.com/argoproj/argo-workflows/commit/4524339892ae3e98bf6a5c9f11c5e2f41622f06c) fix(docs): fix data transformation example (#6901) [73d6010](https://github.com/argoproj/argo-workflows/commit/73d60108b74341baf162580c11323624ba3936b5) fix(executor): add test for non-root user creating a script (#6905) [79d03a9](https://github.com/argoproj/argo-workflows/commit/79d03a9203d85d270017b5f0104fbf88879c6cdc) fix: Skip empty withParam tasks. Fixes #6834 (#6912) [67fe87b](https://github.com/argoproj/argo-workflows/commit/67fe87ba9f3b8dbcb0f330a7ef593403d8909061) fix(ui): Change pod names to new format. Fixes #6865 (#6925) [1bcfa1a](https://github.com/argoproj/argo-workflows/commit/1bcfa1aa5dcb90559772be2a32512ba17d72c4ed) fix: BASE_HREF ignore (#6926) [41515d6](https://github.com/argoproj/argo-workflows/commit/41515d65c2cc3ac1f492942e21fd33c4e31acdb1) fix(controller): Fix getPodByNode, TestGetPodByNode. Fixes #6458 (#6897) [5a7708c](https://github.com/argoproj/argo-workflows/commit/5a7708c2c449544905bbed474f9edc21e9fcf3e7) fix: do not delete expr tag tmpl values. Fixes #6909 (#6921) [ef6aad6](https://github.com/argoproj/argo-workflows/commit/ef6aad6171c4ed165078e9569364d7d7c54b434f) fix: Parameter with Value and Default (#6887) [4d38404](https://github.com/argoproj/argo-workflows/commit/4d38404dfe2d6b941fece60c56db21a3b6f70c4b) fix: Resource requests on init/wait containers. Fixes #6809 (#6879) [cca4792](https://github.com/argoproj/argo-workflows/commit/cca4792c5adfd44340238122f7fe4e6010a96676) fix(ui): fixed width button (#6883) [c962bb1](https://github.com/argoproj/argo-workflows/commit/c962bb189b491bcd8d2c4bedb75f778ca1301305) fix: upgrade sprig to v3.2.2 (#6876)

Agreed as long as fix doesn't have new upcoming feature changes/dependency

**Comment by sarabala1979** [comment]
- [ ]  0482964 fix(ui): Correctly show zero-state when CRDs not installed. Fixes #7001 (#7169)
- [ ] f9e554d fix: Relative submodules in git artifacts. Fixes #7141 (#7162)
- [ ] 22af736 fix: Reorder CI checks so required checks run first (#7142)
- [ ] bd3be11 fix: Return error when YAML submission is invalid (#7135)
- [ ] 209ff9d fix: Respect template.HTTP.timeoutSeconds (#7136)
- [ ] 02165aa fix(controller): default volume/mount to emissary (#7125)
- [ ] 3d59726 fix: typo in node-field-selector.md (#7116)
- [ ] ca87f29 fix: Daemon step in running state, but dependents don't start (#7107)
- [ ] 1e87159 fix: Add pod name format annotation. Fixes #6962 and #6989 (#6982)
- [ ] c5de76b fix: Format issue on WorkflowEventBinding parameters. Fixes #7042 (#7087)
- [ ] 64fce4a fix: Ensure HTTP reconciliation occurs for onExit nodes (#7084)
- [ ] d6a62c3 fix: Ensure HTTP templates have children assigned (#7082)
- [ ] 46767b8 fix(ui): Correct HTTP connection in pipeline view (#7077)
- [ ] 201ba55 fix: add outputs.parameters scope to script/containerSet templates. Fixes #6439 (#7045)
- [ ] 31bf57b fix: Unit test TestNewOperation order of pipeline execution maybe different to order of submit (#7069)
- [ ] 4734cbc fix: Precedence of ContainerRuntimeExecutor and ContainerRuntimeExecutors (#7056)
- [ ] 65ff89a fix: Memozie for Step and DAG level (#7028)
- [ ] 0baa4a2 fix: Support RFC3339 in creationTimeStamp. Fixes #6906 (#7044)
- [ ] ba472e1 fix: Minor corrections to Swagger/JSON schema (#7027)
- [ ] 3f0a531 fix(controller): use correct pod.name in retry/podspecpatch scenario. Fixes #7007 (#7008)
- [ ] 7f52623 fix(ui): labels in report/archive should be sorted (#7009)
- [ ] 50813da fix(controller): fix bugs in processing retry node output parameters. Fixes #6948 (#6956)
- [ ] 86ddda5 fix: Restore default pod name version to v1 (#6998)
- [ ] 0446f52 fix(artifact)!: default https to any URL missing a scheme. Fixes #6973 (#6985)
- [ ] cfdebf6 fix(typo): correct typo in event-dispatch error log (#6688)
- [ ] 2a15853 fix: OAuth2 callback with self-signed Root CA. Fixes #6793 (#6978)
- [ ] 72356ab fix: Allow self-signed Root CA for SSO. Fixes #6793 (#6961)
- [ ] c705294 fix: response on canceled workflow action (#6859) (#6967)
- [ ] cf9a6cd fix: Unreachable code in util/tls/tls.go. Fixes #6950 (#6960)
- [ ] 6e1f250 fix: multi-steps workflow (#6957)
- [ ] 4524339 fix(docs): fix data transformation example (#6901)
- [ ] 73d6010 fix(executor): add test for non-root user creating a script (#6905)
- [ ] 79d03a9 fix: Skip empty withParam tasks. Fixes #6834 (#6912)
- [ ] 67fe87b fix(ui): Change pod names to new format. Fixes #6865 (#6925)
- [ ] 1bcfa1a fix: BASE_HREF ignore (#6926)
- [ ] 41515d6 fix(controller): Fix getPodByNode, TestGetPodByNode. Fixes #6458 (#6897)
- [ ] 5a7708c fix: do not delete expr tag tmpl values. Fixes #6909 (#6921)
- [ ] ef6aad6 fix: Parameter with Value and Default (#6887)
- [ ] 4d38404 fix: Resource requests on init/wait containers. Fixes #6809 (#6879)
- [ ] cca4792 fix(ui): fixed width button (#6883)
- [ ] c962bb1 fix: upgrade sprig to v3.2.2 (#6876)

**Comment by sarabala1979** [comment]
@alexec I think 3.2 we will follow the cherry pick way. after 3.3 onwards we will merge all fixes (appropriates) to patch release instead of pick and choose.

**Comment by sarabala1979** [comment]
I will include it

**Comment by sarabala1979** [comment]
- [ ] fix(executor): add test for non-root user creating a script (#6905)https://github.com/argoproj/argo-workflows/commit/73d60108b74341baf162580c11323624ba3936b5

**Comment by mitchellgordon95** [comment]
Is it too late to get #6995 in? it's been a couple weeks and it would definitely help me out.

**Comment by alexec** [comment]
We don't normally back port features I'm afraid.

**Comment by kostas-theo** [comment]
Hi @alexec - This issue is still opened and 3.2.4 has been released. Are the listed items still slated to be included in the next release?

**Comment by alexec** [comment]
Please see changeling.
