### ISSUE TITLE
v3.2.5 Release

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#7414]
- [ ] Dillen Padhiar: fix: added check for initContainer name in workflow template (#7411) 014bac90f
- [x] Simon Behar: fix: Skip missed executions if CronWorkflow schedule is changed. Fixes #7182 (#7353) 932040848
- [ ] Simon Behar: fix: Propogate errors in task worker and don't return (#7357) 78dd747c6
- [x] Takumi Sue: fix: argument of PodName function (fixes #7315) (#7316) 8bd7f3971
- [x] Dominik Deren: fix: improve error message for ListArchivedWorkflows (#7345) 1a3b87bdf
- [ ] Alex Collins: fix: Use and enforce structured logging. Fixes #7243  (#7324) 77d87da3b
- [x] BOOK: fix: cannot access HTTP template's outputs (#7200) cb8c06369
- [ ] Simon Behar: fix: Use DEFAULT_REQUEUE_TIME for Agent. Fixes #7269 (#7296) e0d5abcff
- [x] Alex Collins: fix(ui): Fix events error. Fixes #7320 (#7321) 242360a4f
- [x] Yuan Tang: fix: Validate the type of configmap before loading parameters. Fixes #7312 (#7314) cf78ff6d7
- [x] Saravanan Balasubramanian: fix: Handle the panic in operate function (#7262) 08254f547
- [x] Takumi Sue: fix: pod name shown in log when pod deletion (#7301) 88cbea332
- [x] Simon Behar: fix: Use default value for empty env vars (#7297) 6c47c91e2
- [x] Alex Collins: fix: Fix `argo auth token`. Fixes #7175 (#7186) e0455772a
- [ ] Benny Cornelissen: fix: improve feedback when submitting a workflow from the CLI w/o a serviceaccount specified (#7246) 0ea855479
- [ ] Takumi Sue: docs: fix typo timout -> timeout (#7244) 8b530df48
- [x] Alex Collins: fix: refactor/fix pod GC. Fixes #7159 (#7176) 1d715a05c
- [ ] Mathew Wicks: docs: fix checkout path for local dev (#7241) 8477c73e1
- [x] Rob Herley: fix: add gh ecdsa and ed25519 to known hosts (#7226) f34715475
- [x] Guillaume Fillon: fix: Fix ANSI color sequences escaping (#7211) eb9a42897
- [ ] Michael Weibel: fix: Do not patch empty progress. fixes #7184 (#7204) 1453edca7
- [x] Mathew Wicks: fix: ci sleep command syntax for macOS 12 (#7203) 34e5b5477
- [x] kennytrytek: fix: allow wf templates without parameter values (Fixes #6044) (#7124) 17fb9d813
- [ ] kennytrytek: fix(test): Make TestMonitorProgress Faster (#7185) 225a5a33a
- [x] Alex Collins: fix(ui): Correctly show zero-state when CRDs not installed. Fixes #7001 (#7169) 0482964d9
- [x] Valér Orlovský: fix: Relative submodules in git artifacts. Fixes #7141 (#7162) f9e554d26
- [x] Alex Collins: chore: fix `make test` (#7157) 5796081cd
- [x] Simon Behar: fix: Reorder CI checks so required checks run first (#7142) 22af73650
- [x] Simon Behar: fix: Return error when YAML submission is invalid (#7135) bd3be1152
- [x] Simon Behar: fix: Respect template.HTTP.timeoutSeconds (#7136) 209ff9d9b
- [x] Tianchu Zhao: fix(controller): default volume/mount to emissary (#7125) 02165aaeb
- [ ] Kyle Hanks: fix: typo in node-field-selector.md (#7116) 3d597269e
- [x] Sebastiaan Tammer: docs: fixed a typo in security.md (#7117) 863d8b9ad
- [x] Saravanan Balasubramanian: fix: Daemon step in running state, but dependents don't start (#7107) ca87f2906
- [x] J.P. Zivalich: fix: Add pod name format annotation. Fixes #6962 and #6989 (#6982) 1e8715954
- [x] Alex Collins: build: prevent bad commit messages, fix broken builds (#7086) 0fb104481
- [x] Jonathan: fix: Format issue on WorkflowEventBinding parameters. Fixes #7042 (#7087) c5de76b6a
- [x] Simon Behar: fix: Ensure HTTP reconciliation occurs for onExit nodes (#7084) 64fce4a82
- [x] Simon Behar: fix: Ensure HTTP templates have children assigned (#7082) d6a62c3e2
- [x] Alex Collins: ci: fix SDK publishing 91671cdd1
- [x] Alex Collins: fix(ui): Correct HTTP connection in pipeline view (#7077) 46767b86b
- [x] Ziv Levi: fix: add outputs.parameters scope to script/containerSet templates. Fixes #6439 (#7045) 201ba5525
- [ ] Tianchu Zhao: fix: Unit test TestNewOperation order of pipeline execution maybe different to order of submit (#7069) 31bf57b64
- [x] Tianchu Zhao: docs(cli): fix cron delete flag description (#7058) 18c953df6
- [x] Saravanan Balasubramanian: fix: Precedence of ContainerRuntimeExecutor and ContainerRuntimeExecutors (#7056) 4734cbc44
- [x] Saravanan Balasubramanian: fix: Memozie for Step and DAG level (#7028) 65ff89ac8
- [x] Ziv Levi: fix: Support RFC3339 in creationTimeStamp. Fixes #6906 (#7044) 0baa4a203
- [x] William Van Hevelingen: docs: Add contributor meeting information and fix slack channel (#7031) d3442472e
- [x] Alex Collins: fix: Minor corrections to Swagger/JSON schema (#7027) ba472e131
- [x] Tianchu Zhao: fix(controller): use correct pod.name in retry/podspecpatch scenario. Fixes #7007 (#7008) 3f0a531aa
- [ ] Tianchu Zhao: fix(ui): labels in report/archive should be sorted (#7009) 7f5262338
- [x] smile-luobin: fix(controller): fix bugs in processing retry node output parameters. Fixes #6948 (#6956) 50813daaf
- [x] J.P. Zivalich: fix: Restore default pod name version to v1 (#6998) 86ddda592
- [x] Tianchu Zhao: fix(artifact)!: default https to any URL missing a scheme. Fixes #6973 (#6985) 0446f521d
- [x] Zadkiel: fix(typo): correct typo in event-dispatch error log (#6688) cfdebf64e
- [x] NextNiclas: fix: OAuth2 callback with self-signed Root CA. Fixes #6793 (#6978) 2a15853ec
- [ ] smile-luobin: feat: fix workflow configmap argument cannot be referenced as local variable. Fixes #6869 (#6898) 6384e5f21
- [x] NextNiclas: fix: Allow self-signed Root CA for SSO. Fixes #6793 (#6961) 72356abad
- [x] Miroslav Tomasik: fix: response on canceled workflow action (#6859) (#6967) c705294c9
- [x] SalvadorC: fix: Unreachable code in util/tls/tls.go. Fixes  #6950 (#6960) cf9a6cdd0
- [x] Arthur Sudre: fix: multi-steps workflow (#6957) 6e1f2505a
- [x] Peter Evers: fix(docs): fix data transformation example (#6901) 452433989
- [x] Bob Haddleton: fix(executor): add test for non-root user creating a script (#6905) 73d60108b
- [x] Iven: fix: Skip empty withParam tasks. Fixes #6834 (#6912) 79d03a920
- [ ] J.P. Zivalich: fix(ui): Change pod names to new format. Fixes #6865 (#6925) 67fe87ba9
- [x] Saravanan Balasubramanian: fix: BASE_HREF ignore (#6926) 1bcfa1aa5
- [x] Micah Beeman: fix(controller): Fix getPodByNode, TestGetPodByNode. Fixes #6458 (#6897) 41515d65c
- [x] Alex Collins: fix: do not delete expr tag tmpl values. Fixes #6909 (#6921) 5a7708c2c
- [x] Saravanan Balasubramanian: fix: Parameter with Value and Default (#6887) ef6aad617
- [x] zorulo: fix: Resource requests on init/wait containers. Fixes #6809 (#6879) 4d38404df
- [x] Tianchu Zhao: fix(ui): fixed width button (#6883) cca4792c5
- [ ] Tianchu Zhao: feat(server): archivedWf add namePrefix search. Fixes #6743 (#6801) b54809771
- [x] Hong Wang: fix: upgrade sprig to v3.2.2 (#6876) c962bb189

**Comment by terrytangyuan** [comment]
Please cherry-pick https://github.com/argoproj/argo-workflows/commit/cf78ff6d76b09c4002edbc28048c67335bd1d00f. Thanks!
