### ISSUE TITLE
v3.2.9 Cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#8043]
Planning to release v3.2.9 end of today. Please select your issues which you want to include in this release

- [ ] Todor Todorov: fix: Support for custom HTTP headers. Fixes #7985 (#8004) fe8ac30b0
- [x] Saravanan Balasubramanian: fix: panic on synchronization if workflow has mutex and semaphore (#8025) 9655a8348
- [ ] Shyukri Shyukriev: fix: Fix/client go/releaseoncancel. Fixes  #7613 (#8020) 957330301
- [ ] Alex Collins: fix!: Document `workflowtaskset` breaking change. Fixes #8013 (#8015) c5c3b3134
- [ ] Alex Collins: fix: Reduce agent permissions. Fixes #7986 (#7987) 06d4bf76f
- [ ] Alex Collins: fix: Re-factor `assessNodeStatus`. Fixes #7996 (#7998) 20f7516f9
- [ ] Alex Collins: fix: Generate SDKS (#7989) 7c0e28901
- [ ] Alex Collins: fix: Report container, plugin and HTTP  progress. Fixes #7918 (#7960) d57fd0ff4
- [x] Markus Lippert: fix: Fix broken Windows build (#7933) ad312674a
- [ ] Alex Collins: docs: Update mentors list. Fixes #7882 (#7889) 6aeaebfd8
- [ ] Alex Collins: fix: Fix `rowserrcheck` lint errors (#7924) 5b6bfb6d3
- [ ] Alex Collins: feat: Update new version modal for v3.3. Fixes #7639 (#7707) 11890b4cc
- [ ] Baz Chalk: fix: Add license to python sdk. Fixes #7881 (#7883) 3524615b8
- [ ] Lukasz Stolcman: fix: Increase padding between elements in workflow template creator. Fixes #7309 (#7420) 80e7a27bf
- [ ] Oleg: fix: trim spaces while parse realtime metrics value. Fixes #7819 (#7856) c0c24d24e
- [ ] Ken Kaizu: fix: workflow-node-info long attribute message cannot be wrapped in the ui (#7876) bb8d2858d
- [ ] Niklas Hansson: feat: add container-set retry strategy.  Fixes #7290 (#7377) 808c561f1
- [ ] Tianchu Zhao: fix(cli): fix typo in argo cron error messages (#7875) 31cc8bf98
- [ ] Rohan Kumar: fix: added priorityclass to workflow-controller. Fixes #7733 (#7859) 87cb15591
- [ ] Jin Dong: fix: Fix go-jose dep. Fixes #7814 (#7874) 69c5bc79f
- [ ] Vrukshali Torawane: fix: Add env to argo-server deployment manifest. Fixes #7285 (#7852) 28412ef7c
- [ ] Isitha Subasinghe: feat: remove pod workers. Fixes #4090 (#7837) fce82d572
- [ ] Doğukan Tuna: fix(ui): unauthorized login screen redirection to token creation docs (#7846) 938fde967
- [ ] Dillen Padhiar: fix: submitting Workflow from WorkflowTemplate will set correct serviceAccount and securityContext. Fixes #7726 (#7805) 1113f70fa
- [ ] J.P. Zivalich: fix: Use v1 pod name if no template name or ref. Fixes #7595 and #7749 (#7605) 932466540
- [ ] Saravanan Balasubramanian: fix: Missed workflow should not trigger if Forbidden Concurreny with no StartingDeadlineSeconds (#7746) e9b873ae3
- [ ] Paco Guzmán: fix: artifacts.(*ArtifactServer).GetInputArtifactByUID ensure valid request path (#7730) 70715ecc8
- [ ] Denis Melnik: fix: ContainerSet termination during pending Pod #7635 (#7681) bf3b58b98
- [ ] Tino Schröter: fix: Pod "START TIME"/ "END TIME" tooltip shows time in UTC and local timezone Fixes #7488 (#7694) f6c9a6aa7
- [ ] Yuan Tang: fix: Fix argo lint panic when missing param value in DAG task. Fixes #7701 (#7706) e2e046f6f
- [ ] Yago Riveiro: feat: Add variable substitution on ConfigMapKeySelector. Fixes #7061 (#7542) 72817f2b8
- [ ] Yuan Tang: fix: Handle release candidate versions in Python SDK version. Fixes #7692 (#7693) 753509394
- [ ] Tino Schröter: docs: fix double appearance of how (#7670) ed9b093fc
- [x] Alex Collins: fix: Support terminating with `templateRef`. Fixes #7214 (#7657) 67c278cd1
- [ ] J.P. Zivalich: fix: Match cli display pod names with k8s. Fixes #7646 (#7653) 1159afc3c
- [ ] Alex Collins: fix: Retry with DAG. Fixes #7617 (#7652) 6a97a6161
- [ ] Tom Meadows: fix: insecureSkipVerify needed. Fixes #7632 (#7651) a20150c45
- [ ] Isitha Subasinghe: fix: error when path length != 6 (#7648) 0137e1980
- [ ] jwjs36987: fix: Fix non-standard git username support. Fixes #7593 (#7634) 6f60703db
- [ ] khyer: fix: SSO to handle multiple authorization cookies such as from wildca… (#7607) 0ce9e70ef
- [ ] Alex Collins: fix: Support artifact ref from tmpl in UI. Fixes #7587 (#7591) d2e98d6b4
- [ ] Alex Collins: feat(ui): Show first-time UX. Fixes #7160 (#7170) c6be0fe77
- [ ] Alex Collins: chore: Improve security scanning. Fixes #7599 (#7602) 7ca020191
- [ ] Yuan Tang: fix: Upgrade prismjs to v1.26 to fix security scan. Fixes #7599 (#7601) 2e343eb7f
- [ ] Alex Collins: fix: Support inputs for inline DAG template. Fixes #7432 (#7439) f9fa0e303
- [ ] Peixuan Ding: fix: Fix inconsistent ordering of workflows with the list command. Fixes #7581 (#7594) bc27ada85
- [ ] Peixuan Ding: feat: Support templateRef in LifecycleHook. Fixes #7558 (#7570) af257c178
- [ ] kostas-theo: fix: hanging wait container on save artifact to GCS bucket artifactRepository (#7536) f1fe3bee4
- [x] FengyunPan2: fix: fix nil point about Outputs.ExitCode. Fixes #7458 (#7459) a94b846e6
- [ ] Andy: fix: More informative error message when artefact repository is not configured. Fixes #7372 (#7498) 4b83de9b5
- [ ] cod-r: fix: update old buildkit version in buildkit-template.yaml (#7512) 2ab7dfebe
- [ ] Ken Kaizu: fix: show invalid cron schedule error on cron status ui (#7441) c172d1dce
- [ ] kennytrytek: fix: resolve resourcesDuration (#7299) fbf4751f4
- [x] Yuan (Bob) Gong: fix(controller): fix pod stuck in running when using podSpecPatch and emissary (#7407) 033ed978e
- [ ] Peixuan Ding: fix: Fix supplied global workflow parameters (#7573) ebdde3392
- [ ] Isitha Subasinghe: fix: add priority field to submitopts (#7572) dbb1bcfbd
- [ ] AdamKorcz: fix: Fix type assertion bug (#7556) bc1f304a9
- [ ] leonharetd: docs: fix typo in container-set-template.md (#7545) 15c0035eb
- [ ] AdamKorcz: fix: nil-pointer in util.ApplySubmitOpts (#7529) 970a503c5
- [ ] 大雄: fix: handle source file is empty for script template (#7467) 18821c57f
- [ ] Yuan Tang: fix: Make dev version of the Python SDK PEP440 compatible (#7525) b476c4af5
- [ ] Roel van den Berg: fix: transient errors for s3 artifacts: Fixes #7349 (#7352) 26c1224b0
- [ ] Nicoló Lino: fix: http template doesn't update progress. Fixes #7239 (#7450) 3371e7268
- [ ] Yuan Tang: docs: Add additional args to avoid type checks. Fixes #7293 (#7500) e0f43b8a5
- [ ] Yuan Tang: fix: Global param value incorrectly overridden when loading from configmaps (#7515) 4b006d5f8
- [ ] Dillen Padhiar: fix: only aggregates output from successful nodes (#7517) 0f206d670
- [ ] Michael Crenshaw: docs: fix retryStrategy field name (#7502) f93d00ab4
- [ ] AdamKorcz: fix: out of range in MustUnmarshal (#7485) 318927ed6
- [ ] Niklas Hansson: feat: add workflow.labels and workflow.annotations as JSON string. Fixes: #7289 (#7396) d3ecdf11c
- [ ] Ting Yuan: fix: shutdown workqueues to avoid goroutine leaks (#7493) 4f9e299b7
- [ ] Yuan Tang: docs: Differentiate instructions for installing different components. Fixes #7470 (#7477) ed71304b3
- [ ] Serhat: docs: Fixing the missing -parameter word in workflow-templates docs (#7489) 54e8a05c0
- [ ] Yuan Tang: docs: Fix typo mentees -> mentors (#7454) cda7cd46a
- [ ] Dillen Padhiar: fix: submitting cluster workflow template on namespaced install returns error (#7437) dd77dc993
- [ ] Yuan Tang: fix: Disable SDK release from master branch (#7419) d99796b2f
- [ ] Alex Collins: fix: Correct default emissary bug. Fixes #7224 (#7412) 79d50fc27
- [ ] Dillen Padhiar: fix: added check for initContainer name in workflow template (#7411) 014bac90f
- [ ] Simon Behar: fix: Skip missed executions if CronWorkflow schedule is changed. Fixes #7182 (#7353) 932040848
- [ ] Yuan Tang: chore: Improve error message when configmap is not found. Fixes #7356 (#7371) d3c2f5d62
- [ ] Simon Behar: fix: Propogate errors in task worker and don't return (#7357) 78dd747c6
- [ ] Takumi Sue: fix: argument of PodName function (fixes #7315) (#7316) 8bd7f3971
- [ ] Dominik Deren: fix: improve error message for ListArchivedWorkflows (#7345) 1a3b87bdf
- [ ] Alex Collins: fix: Use and enforce structured logging. Fixes #7243  (#7324) 77d87da3b
- [ ] BOOK: fix: cannot access HTTP template's outputs (#7200) cb8c06369
- [ ] Simon Behar: fix: Use DEFAULT_REQUEUE_TIME for Agent. Fixes #7269 (#7296) e0d5abcff
- [ ] Alex Collins: fix(ui): Fix events error. Fixes #7320 (#7321) 242360a4f
- [ ] Yuan Tang: fix: Validate the type of configmap before loading parameters. Fixes #7312 (#7314) cf78ff6d7
- [ ] Saravanan Balasubramanian: fix: Handle the panic in operate function (#7262) 08254f547
- [ ] Takumi Sue: fix: pod name shown in log when pod deletion (#7301) 88cbea332
- [ ] Simon Behar: fix: Use default value for empty env vars (#7297) 6c47c91e2
- [ ] Yuan Tang: docs: Fix workflow name in suspend outputs example (#7268) e67e94c02
- [ ] Alex Collins: fix: Fix `argo auth token`. Fixes #7175 (#7186) e0455772a
- [ ] Benny Cornelissen: fix: improve feedback when submitting a workflow from the CLI w/o a serviceaccount specified (#7246) 0ea855479
- [ ] Alex Collins: fix: refactor/fix pod GC. Fixes #7159 (#7176) 1d715a05c
- [ ] Nityananda Gohain: feat: add CreatorUsername label when user is signed in via SSO. Fixes… (#7109) 09987a6dd
- [ ] Rob Herley: fix: add gh ecdsa and ed25519 to known hosts (#7226) f34715475
- [ ] Guillaume Fillon: fix: Fix ANSI color sequences escaping (#7211) eb9a42897
- [ ] Michael Weibel: fix: Do not patch empty progress. fixes #7184 (#7204) 1453edca7
- [ ] Mathew Wicks: fix: ci sleep command syntax for macOS 12 (#7203) 34e5b5477
- [ ] kennytrytek: fix: allow wf templates without parameter values (Fixes #6044) (#7124) 17fb9d813
- [ ] kennytrytek: fix(test): Make TestMonitorProgress Faster (#7185) 225a5a33a
- [ ] Alex Collins: fix(ui): Correctly show zero-state when CRDs not installed. Fixes #7001 (#7169) 0482964d9
- [ ] Valér Orlovský: fix: Relative submodules in git artifacts. Fixes #7141 (#7162) f9e554d26
- [ ] Simon Behar: fix: Reorder CI checks so required checks run first (#7142) 22af73650
- [ ] Simon Behar: fix: Return error when YAML submission is invalid (#7135) bd3be1152
- [ ] Simon Behar: fix: Respect template.HTTP.timeoutSeconds (#7136) 209ff9d9b
- [ ] Tianchu Zhao: fix(controller): default volume/mount to emissary (#7125) 02165aaeb
- [ ] Kyle Hanks: fix: typo in node-field-selector.md (#7116) 3d597269e
- [ ] Saravanan Balasubramanian: fix: Daemon step in running state, but dependents don't start (#7107) ca87f2906
- [ ] ybyang: feat: Add workflow logs  selector support. Fixes #6910 (#7067) 5eab921eb
- [ ] J.P. Zivalich: fix: Add pod name format annotation. Fixes #6962 and #6989 (#6982) 1e8715954
- [ ] Alex Collins: build: prevent bad commit messages, fix broken builds (#7086) 0fb104481
- [ ] Jonathan: fix: Format issue on WorkflowEventBinding parameters. Fixes #7042 (#7087) c5de76b6a
- [ ] Simon Behar: fix: Ensure HTTP reconciliation occurs for onExit nodes (#7084) 64fce4a82
- [ ] Simon Behar: fix: Ensure HTTP templates have children assigned (#7082) d6a62c3e2
- [ ] Alex Collins: ci: fix SDK publishing 91671cdd1
- [ ] Alex Collins: fix(ui): Correct HTTP connection in pipeline view (#7077) 46767b86b
- [ ] Ziv Levi: fix: add outputs.parameters scope to script/containerSet templates. Fixes #6439 (#7045) 201ba5525
- [ ] Tianchu Zhao: fix: Unit test TestNewOperation order of pipeline execution maybe different to order of submit (#7069) 31bf57b64
- [ ] Tianchu Zhao: docs(cli): fix cron delete flag description (#7058) 18c953df6
- [ ] Saravanan Balasubramanian: fix: Precedence of ContainerRuntimeExecutor and ContainerRuntimeExecutors (#7056) 4734cbc44
- [ ] Saravanan Balasubramanian: fix: Memozie for Step and DAG level (#7028) 65ff89ac8
- [ ] Ziv Levi: fix: Support RFC3339 in creationTimeStamp. Fixes #6906 (#7044) 0baa4a203
- [ ] Tianchu Zhao: feat(ui): add label/state filter to cronworkflow. Fixes #7034 (#7035) 25e1939e2
- [ ] William Van Hevelingen: docs: Add contributor meeting information and fix slack channel (#7031) d3442472e
- [ ] Alex Collins: fix: Minor corrections to Swagger/JSON schema (#7027) ba472e131
- [ ] Alex Collins: docs: Fix docs build. Fixes #7023 (#7024) 93c301dff
- [ ] Tianchu Zhao: fix(controller): use correct pod.name in retry/podspecpatch scenario. Fixes #7007 (#7008) 3f0a531aa
- [ ] Tianchu Zhao: fix(ui): labels in report/archive should be sorted (#7009) 7f5262338
- [ ] smile-luobin: fix(controller): fix bugs in processing retry node output parameters. Fixes #6948 (#6956) 50813daaf
- [ ] J.P. Zivalich: fix: Restore default pod name version to v1 (#6998) 86ddda592
- [ ] Tianchu Zhao: fix(artifact)!: default https to any URL missing a scheme. Fixes #6973 (#6985) 0446f521d
- [ ] Zadkiel: fix(typo): correct typo in event-dispatch error log (#6688) cfdebf64e
- [ ] NextNiclas: fix: OAuth2 callback with self-signed Root CA. Fixes #6793 (#6978) 2a15853ec
- [ ] NextNiclas: fix: Allow self-signed Root CA for SSO. Fixes #6793 (#6961) 72356abad
- [ ] Miroslav Tomasik: fix: response on canceled workflow action (#6859) (#6967) c705294c9
- [ ] William Van Hevelingen: docs: Fix typo in pr template (#6965) b6369dcb0
- [ ] SalvadorC: fix: Unreachable code in util/tls/tls.go. Fixes  #6950 (#6960) cf9a6cdd0
- [ ] Arthur Sudre: fix: multi-steps workflow (#6957) 6e1f2505a
- [ ] Peter Evers: fix(docs): fix data transformation example (#6901) 452433989
- [ ] Bob Haddleton: fix(executor): add test for non-root user creating a script (#6905) 73d60108b
- [ ] Iven: fix: Skip empty withParam tasks. Fixes #6834 (#6912) 79d03a920
- [ ] Tianchu Zhao: feat(executor): default executor to emissary. Fixes #6785 (#6882) b0d1f6583
- [ ] J.P. Zivalich: fix(ui): Change pod names to new format. Fixes #6865 (#6925) 67fe87ba9
- [ ] Saravanan Balasubramanian: fix: BASE_HREF ignore (#6926) 1bcfa1aa5
- [ ] Micah Beeman: fix(controller): Fix getPodByNode, TestGetPodByNode. Fixes #6458 (#6897) 41515d65c
- [ ] Yuan Tang: docs: Fix demonstration of using existing ConfigMap in memoization cache (#6920) 9efc9e8fc
- [ ] Alex Collins: fix: do not delete expr tag tmpl values. Fixes #6909 (#6921) 5a7708c2c
- [ ] Tianchu Zhao: feat(ui): resume on selected node. Fixes #5763 (#6885) c5b1533d3
- [x] Saravanan Balasubramanian: fix: Parameter with Value and Default (#6887) ef6aad617
- [ ] zorulo: fix: Resource requests on init/wait containers. Fixes #6809 (#6879) 4d38404df
- [ ] Tianchu Zhao: fix(ui): fixed width button (#6883) cca4792c5
- [ ] Hong Wang: fix: upgrade sprig to v3.2.2 (#6876) c962bb189

**Comment by alexec** [comment]
@sarabala1979 can I request

- only show fixes in list, not chore/feat
- I think some of these fixes are already in v3.2?

**Comment by sarabala1979** [comment]
done.  issues have `fix` subject that's why it is included. I will do a manual check next time.
I got PRs from last hash in v3.2 to master HEAD.

**Comment by alexec** [comment]
Can I leave it with you to review the list and include any bug fixes you think we need?

**Comment by sarabala1979** [comment]
sure
