### ISSUE TITLE
v3.3.1 Cherry-pick

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#8183]
- [x] Saravanan Balasubramanian: fix: workflow.duration' is not available as a real time metric (#8181) fbb43b242
- [x] Alex Collins: fix: Authentication for plugins. Fixes #8144 (#8147) 0e707cdf6
- [x] Alex Collins: fix: Correctly order emissary combined output. Fixes #8159 (#8175) e7008eada
- [x] Alex Collins: fix: Add instance ID to `workflowtaskresults` (#8150) 9101c4939
- [x] Ming Yu Shi: fix: add /etc/mime.types mapping table (#8171) 715f6ced6
- [x] William Van Hevelingen: fix: Limit workflows to 128KB and return a friendly error message (#8169) 6d6e08aa8
- [x] Alex Collins: fix: Remove need for `get pods` from Emissary (#8133) af26ff7ed
- [x] Saravanan Balasubramanian: fix: Fix the TestStopBehavior flackiness (#8096) 4d4890454
- [x] Vignesh: fix: pod deleted due to delayed cleanup. Fixes #8022 (#8061) 6855f4c51
- [x] Felix Seidel: fix(plugins): UX improvements (#8122) 972a4e989
- [x] Wu Jayway: fix(executor): Retry kubectl on internal transient error (#8092) 765333dc9
- [x] Rohan Kumar: feat: add TLS config option to HTTP template. Fixes #7390 (#7929) 057c3346f

**Comment by sarabala1979** [comment]
@alexec  can you help me to cherry pick below commit?
Alex Collins: fix: Authentication for plugins. Fixes https://github.com/argoproj/argo-workflows/issues/8144 (https://github.com/argoproj/argo-workflows/pull/8147) https://github.com/argoproj/argo-workflows/commit/0e707cdf69f891c7c7483e2244f5ea930d31b1c5
