### ISSUE TITLE
artifact repo failed to load: fatal: 'dev' could be both a local file and a tracking branch.

### ISSUE THREAD

**Issue by jackivanov** [argoproj/argo-workflows#8282]
## Checklist

 

* [ ] Double-checked my configuration.
* [ ] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

Git artifact input
A file in the repo matches the brach name (ie: folder dev in branch dev)
Argo workflows can't checkout the artifact

```
Error (exit code 1): artifact repo failed to load: fatal: 'dev' could be both a local file and a tracking branch.
```

Version 3.2.4

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
    - name: git
      inputs:
        artifacts:
          - name: repo
            path: /repo
            git:
              repo: ssh://git@server/project/repo.git
              revision: dev
              depth: 1
              insecureIgnoreHostKey: true
              sshPrivateKeySecret:
                name: xxx
                key: xxx
      container:
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.
