### ISSUE TITLE
Cherry pick v3.3.2

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#8401]
- [x] Saravanan Balasubramanian: fix: Daemon step updated 'pod delete' while pod is running (#8399) f467cc555
- [ ] Rohan Kumar: fix: prevent backoff when retryStrategy.limit has been reached. Fixes #7588 (#8090) a648ccdcf
- [x] Alex Collins: fix: Add readiness check to controller. Fixes #8283 (#8285) 283f6b58f
- [x] Tristan Colgate-McFarlane: fix: Absolute submodules in git artifacts. Fixes #8377 (#8381) b09b9bdfb
- [ ] Snyk bot: fix: upgrade react-moment from 1.0.0 to 1.1.1 (#8389) d47081fb4
- [ ] Snyk bot: fix: upgrade react-datepicker from 2.14.1 to 2.16.0 (#8388) 010e359e4
- [ ] Snyk bot: fix: upgrade prop-types from 15.7.2 to 15.8.1 (#8387) 0c9d88b44
- [x] Alex Collins: fix: Back-off UI retries. Fixes #5697 (#8333) 54fa39c89
- [x] Rohan Kumar: fix: replace `podName` with `nodeId` in `_.primary.swagger.json` (#8385) 637d14c88
- [x] Rohan Kumar: fix: removed error from artifact server 401 response. Fixes #8382 (#8383) 95323f87d
- [ ] Snyk bot: fix: upgrade js-yaml from 3.13.1 to 3.14.1 (#8374) 2d91646aa
- [ ] Snyk bot: fix: upgrade cron-parser from 2.16.3 to 2.18.0 (#8373) 54eaed060
- [x] Saravanan Balasubramanian: fix: Updating complated node status e97b0e66b
- [x] Alex Collins: fix: Add auth for SDKs. Fixes #8230 (#8367) 627597b56
- [ ] Manik Sidana: fix: Erratum in docs. Fixes #8342 (#8359) e9de085d6
- [ ] Snyk bot: fix: upgrade react-chartjs-2 from 2.10.0 to 2.11.2 (#8357) a3d1d07e1
- [ ] Snyk bot: fix: upgrade history from 4.7.2 to 4.10.1 (#8356) b199cb947
- [ ] Snyk bot: fix: upgrade multiple dependencies with Snyk (#8355) e40521556
- [ ] Snyk bot: fix: upgrade com.google.code.gson:gson from 2.8.9 to 2.9.0 (#8354) 8c893bd13
- [ ] Rohan Kumar: feat: add message column to `kubectl get wf` and `argo list`. Fixes #8307 (#8353) ee3765643
- [ ] Marc Abramowitz: fix: examples/README.md: overriten => overridden (#8351) ae3881525
- [x] Alex Collins: fix: Fix response type for artifact service OpenAPI and SDKs. Fixes #7781 (#8332) 242d53596
- [ ] Snyk bot: fix: upgrade io.swagger:swagger-annotations from 1.6.2 to 1.6.5 (#8335) ab21eed52
- [ ] Snyk bot: fix: upgrade react-monaco-editor from 0.36.0 to 0.47.0 (#8339) f708528fb
- [ ] Snyk bot: fix: upgrade cronstrue from 1.109.0 to 1.125.0 (#8338) 3c35bd2f5
- [ ] Snyk bot: fix: upgrade com.squareup.okhttp3:logging-interceptor from 4.9.1 to 4.9.3 (#8336) 7ee17ddb7
- [ ] Alex Collins: fix: Remove path traversal CWE-23 (#8331) aa9ff17d5
- [ ] Snyk bot: fix: ui/package.json & ui/yarn.lock to reduce vulnerabilities (#8328) 14a9a1dc5
- [ ] Snyk bot: fix: sdks/java/pom.xml to reduce vulnerabilities (#8327) 58052c2b7
- [ ] Alex Collins: feat: Remove binaries from argoexec image. Fixes #7486 (#8292) 153540fdd
- [ ] kennytrytek: feat: Always Show Workflow Parameters (#7809) af8077423
- [ ] Alex Collins: feat: Remove the PNS executor. Fixes #7804 (#8296) 62e0a8ce4
- [ ] Cash Williams: fix: update docker version to address CVE-2022-24921 (#8312) 0cdd2b40a
- [ ] Yuan Tang: fix: Default value is ignored when loading params from configmap. Fixes #8262 (#8271) 9c901456a
- [x] Dillen Padhiar: fix: reduce number of workflows displayed in UI by default. Fixes #8297 (#8303) 9ab0e959a
- [x] Dillen Padhiar: fix: fix: git artifact will be checked out even if local file matches name of tracking branch (#8287) 13bc01362
- [ ] Alex Collins: feat: Fail on invalid config. (#8295) 65dc0882c
- [x] Alex Collins: fix: `taskresults` owned by pod rather than workflow. (#8284) 5ac0e314d
- [ ] Alex Collins: fix: Snyk security recommendations (Golang). Fixes #8288 996655f4f
- [ ] Alex Collins: fix: Snyk security recommendations (Node). Fixes #8288 221d99827
- [ ] Soumya Ghosh Dastidar: fix: install.yaml missing crb subject ns (#8280) 954a3ee7e
- [x] Takumi Sue: fix: improve error message when the controller is set `templateReferencing: Secure` (#8277) b198b334d
- [ ] Dillen Padhiar: feat: add resubmit and retry buttons for archived workflows. Fixes #7908 and #7911 (#8272) 5598b8c7f
- [x] Wu Jayway: fix: patch workflow status to workflow (#8265) 78f01f2b9
- [ ] Shubham Nazare: feat: Add a link in the UI for WorkflowTemplate. Fixes #4760 (#8208) f48998c07
- [ ] Dillen Padhiar: feat: add archive retry command to argo CLI. Fixes #7907 (#8229) c1f72b662
- [x] Alex Collins: fix: Update argo-server manifests to have read-only root file-system (#8210) 7a07805b1
- [x] Saravanan Balasubramanian: fix: Panic in Workflow Retry (#8243) 0d4b4dc34
- [x] Saravanan Balasubramanian: fix: Hook with wftemplateRef (#8242) 61f0decd8
- [ ] Takumi Sue: fix: grep pattern (#8238) e232340cc
- [x] Aatman: fix: submodule cloning via git. Fixes #7469 (#8225) 1d373c41a
- [x] Michael Weibel: fix: do not panic when termination-log is not writeable (#8221) 6ee1b03f9
- [ ] Dillen Padhiar: feat: add archive resubmit command to argo CLI. Fixes #7910 (#8166) 8c77e89fc
- [x] Alex Collins: fix: Support `--parameters-file` where ARGO_SERVER specified. Fixes #8160 (#8213) d8aa46731
- [ ] Alex Collins: feat: Add support to auto-mount service account tokens for plugins. (#8176) d33d391a4
- [ ] Rohan Kumar: fix: removed deprecated k8sapi executor. Fixes #7802 (#8205) 8a1fbb86e
- [x] ybyang: fix:  requeue not delete the considererd Task flag (#8194) 12cd8bcaa
- [x] Alex Collins: fix: Use `latest` image tag when version is `untagged`. Fixes #8188 (#8191) e2b288318
- [x] Wu Jayway: fix: task worker requeue wrong task. Fixes #8139 (#8186) 6d6d23d81
- [ ] Rohan Kumar: feat: add TLS config option to HTTP template. Fixes #7390 (#7929) 76ff748d4
- [x] Alex Collins: fix: Authentication for plugins. Fixes #8144 (#8147) ad7d9058e
- [ ] Rohan Kumar: feat: add TLS config option to HTTP template. Fixes #7390 (#7929) 5b14e15c2
- [ ] Saravanan Balasubramanian: fix: workflow.duration' is not available as a real time metric (#8181) ea36c337d
- [x] Alex Collins: fix: Correctly order emissary combined output. Fixes #8159 (#8175) d10a7310c
- [x] Alex Collins: fix: Add instance ID to `workflowtaskresults` (#8150) 442096bf2
- [x] Ming Yu Shi: fix: add /etc/mime.types mapping table (#8171) 2b87f860d
- [x] William Van Hevelingen: fix: Limit workflows to 128KB and return a friendly error message (#8169) 26471c8ee
- [x] Alex Collins: fix: Remove need for `get pods` from Emissary (#8133) dfca6f1e5
- [ ] Saravanan Balasubramanian: fix: Fix the TestStopBehavior flackiness (#8096) 049d3d11f
- [x] Vignesh: fix: pod deleted due to delayed cleanup. Fixes #8022 (#8061) 0cec27390
- [x] Alex Collins: fix: Update `workflowtaskresult` code have own reconciliation loop. (#8135) 41fd07aa4
- [ ] Stephanie Palis: fix: pkg/errors is no longer maintained (#7440) 051c7b8d2
- [x] Saravanan Balasubramanian: fix: workflow.duration' is not available as a real time metric (#8181) fbb43b242
- [x] Alex Collins: fix: Authentication for plugins. Fixes #8144 (#8147) 0e707cdf6
- [ ] Dillen Padhiar: feat: add retry API for archived workflows. Fixes #7906 (#7988) d4b1afe6f
- [x] Alex Collins: fix: Correctly order emissary combined output. Fixes #8159 (#8175) e7008eada
- [x] Alex Collins: fix: Add instance ID to `workflowtaskresults` (#8150) 9101c4939
- [ ] Alex Collins: feat: Use pinned executor version. (#8165) 2b5e4a1d2
- [x] Ming Yu Shi: fix: add /etc/mime.types mapping table (#8171) 715f6ced6
- [x] William Van Hevelingen: fix: Limit workflows to 128KB and return a friendly error message (#8169) 6d6e08aa8
- [ ] Rohan Kumar: feat: add TLS config option to HTTP template. Fixes #7390 (#7929) 057c3346f
- [ ] tatsuya-ogawa: feat: add mysql options (#8157) 5efc9fc99
- [x] Alex Collins: fix: Remove need for `get pods` from Emissary (#8133) af26ff7ed
- [ ] Alex Collins: feat: Change pod clean-up to use informer. (#8136) 537dd3be6
- [ ] Dillen Padhiar: feat: add resubmit API for archived workflows. Fixes #7909 (#8079) 437b37647

**Comment by sarabala1979** [comment]
@alexec Can you select your issues which should go into v3.3?

**Comment by alexec** [comment]
I think some of these fixes are already in v3.3. I've checked as requested.

**Comment by kulinskyvs** [comment]
Hello,

Is there any estimated date for the "3.3.2" release?

Thank you!

**Comment by tooptoop4** [comment]
please include https://github.com/argoproj/argo-workflows/pull/8397

**Comment by alexec** [comment]
I've cherry-picked a0148c1b3 to fix #8257.

**Comment by alexec** [comment]
```
=== RUN   TestRunAsNonRootSuite
[321](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:321)
time="2022-04-19T12:22:37Z" level=info msg="config map" name=workflow-controller-configmap
[322](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:322)
=== RUN   TestRunAsNonRootSuite/TestRunAsNonRootWithOutputParams
[323](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:323)
Submitting workflow  runasnonroot-output-params-
[324](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:324)
Waiting 1m0s for workflow metadata.name=runasnonroot-output-params-5dqpz
[325](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:325)
 ? runasnonroot-output-params-5dqpz Workflow 0s      
[326](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:326)

[327](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:327)
 ● runasnonroot-output-params-5dqpz   Workflow 0s      
[328](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:328)
 └ ◷ runasnonroot-output-params-5dqpz Pod      0s      
[329](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:329)

[330](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:330)
 ● runasnonroot-output-params-5dqpz   Workflow 0s      
[331](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:331)
 └ ● runasnonroot-output-params-5dqpz Pod      0s      
[332](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:332)

[333](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:333)
 ● runasnonroot-output-params-5dqpz   Workflow 0s      
[334](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:334)
 └ ● runasnonroot-output-params-5dqpz Pod      0s      
[335](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:335)

[336](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:336)
 ⚠ runasnonroot-output-params-5dqpz   Workflow 4s      Error (exit code 1): failed to chroot to main filesystem: operation not permitted
[337](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:337)
 └ ⚠ runasnonroot-output-params-5dqpz Pod      2s      Error (exit code 1): failed to chroot to main filesystem: operation not permitted
[338](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:338)

[339](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:339)
    run_as_not_root_test.go:33: condition never and cannot be met because the workflow is done
[340](https://github.com/argoproj/argo-workflows/runs/6077659329?check_suite_focus=true#step:14:340)
=== FAIL: RunAsNonRootSuite/TestRunAsNonRootWithOutputParams
```

**Comment by alexec** [comment]
3d606939d - PASS

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/issues/3500

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/compare/release-3.3

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/actions/runs/2190437810

**Comment by berlinsaint** [comment]
please include 8176
