### ISSUE TITLE
Cherry pick v3.3.6

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#8854]
- [x] 859ebe99f fix: Terminate, rather than delete, deadlined pods. Fixes #8545 (#8620)
- [x] 70f70209d fix: Handle omitted nodes in DAG enhanced depends logic. Fixes #8654 (#8672)
- [ ] 16fef4e54 fix: enable `ARGO_REMOVE_PVC_PROTECTION_FINALIZER` by default. Fixes #8592 (#8661)
- [x] 64a2b28a5 fix: close http body. Fixes #8622 (#8624)
- [x] c3ae56565 fix: Do not log container not found (#8509)
- [ ] 8c0a957c3 fix: Fix bug in entrypoint lookup (#8453)
- [ ] 4471b59a5 fix: open minio dashboard on different port in quick-start (#8407)
- [ ] aa9ff17d5 fix: Remove path traversal CWE-23 (#8331)
- [ ] 14a9a1dc5 fix: ui/package.json & ui/yarn.lock to reduce vulnerabilities (#8328)
- [ ] 58052c2b7 fix: sdks/java/pom.xml to reduce vulnerabilities (#8327)
- [ ] e232340cc fix: grep pattern (#8238)
- [ ] 8a1fbb86e fix: removed deprecated k8sapi executor. Fixes #7802 (#8205)
- [x] 051c7b8d2 fix: pkg/errors is no longer maintained (#7440)
- [x] [feat: remove size limit of 128kb for workflow templates.](https://github.com/argoproj/argo-workflows/commit/bc4a80a8d63f869a7a607861374e0c206873f250)
