### ISSUE TITLE
Cherry-pick  3.3.7

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo-workflows#9012]
- [ ] 2e3177617 fix: add nil check for retryStrategy.Limit in deadline check. Fixes #8990 (#8991)
- [ ] a1535fa44 fix: Workflow Duration metric shouldn't increase after workflow complete (#8989)
- [ ] e0a1afa91 fix: sync cluster Workflow Template Informer before it's used (#8961)
- [ ] 6c244f3cb fix: long code blocks overflow in ui. Fixes #8916 (#8947)
- [ ] e31ffcd33 fix: Correct kill command. Fixes #8687 (#8908)
- [ ] 416fce705 fix: Fork sub-process. Fixes #8454 (#8906)
- [ ] 750c4e1f6 fix: Only signal running containers, ignore failures. (#8909)
- [ ] ede1a39e7 fix: workflowMetadata needs to be loaded into globalParams in both ArgoServer and Controller (#8907)
- [ ] 7dacb5bca fix: Fixed Swagger error. Fixes #8830 (#8886)
- [ ] bc0100346 fix: Change to distroless. Fixes #8805 (#8806)
- [ ] fbb8246cd fix: set NODE_OPTIONS to no-experimental-fetch to prevent yarn start error (#8802)
- [ ] 39fbdb2a5 fix: fix a command in the quick-start page (#8782)
- [ ] 961f731b7 fix: Omitted task result should also be valid (#8776)
- [ ] f6d84640f fix: Skip TestExitHookWithExpression() completely (#8761)
- [ ] 178bbbc31 fix: Temporarily fix CI build. Fixes #8757. (#8758)
- [ ] 354dee866 fix: Exit lifecycle hook should respect expression. Fixes #8742 (#8744)
- [ ] aa366db34 fix: remove list and watch on secrets. Fixes #8534 (#8555)
- [ ] 342abcd6d fix: mkdocs uses 4space indent for nested list (#8740)
- [ ] 515e0763a fix: Simplify return logic in executeTmplLifeCycleHook (#8736)
- [ ] b8f511309 fix: Template in Lifecycle hook should be optional (#8735)
- [ ] b3bf327a0 fix: Fix the resursive example to call the coinflip template (#8696)
- [ ] 9ddae875f fix: Fixed podName in killing daemon pods. Fixes #8692 (#8708)
- [ ] 72d3f32e5 fix: update go-color path/version (#8707)
- [ ] 92b3ef27a fix: upgrade moment from 2.29.2 to 2.29.3 (#8679)
- [ ] 859ebe99f fix: Terminate, rather than delete, deadlined pods. Fixes #8545 (#8620)
- [ ] 3fdf30d9f fix: Enhance artifact visualization. Fixes #8619 (#8655)
- [ ] 16fef4e54 fix: enable `ARGO_REMOVE_PVC_PROTECTION_FINALIZER` by default. Fixes #8592 (#8661)
- [ ] ed351ff08 fix: ArtifactGC moved from Template to Artifact. Fixes #8556. (#8581)
- [ ] 974031570 fix: Polish artifact visualisation. Fixes #7743 (#8552)
- [ ] 98dd898be fix: Correct CSP. Fixes #8560 (#8579)
- [ ] 5b8638fcb fix: modified `SearchArtifact` to return `ArtifactSearchResults`. Fixes #8543 (#8557)
- [ ] ecd91b1c4 fix: added json tag to ArtifactGCStrategies (#8523)
- [ ] f223bb8a3 fix: ArtifactGCOnWorkflowDeletion typo quick fix (#8519)
- [ ] 8c0a957c3 fix: Fix bug in entrypoint lookup (#8453)
- [ ] 4471b59a5 fix: open minio dashboard on different port in quick-start (#8407)
- [ ] d47081fb4 fix: upgrade react-moment from 1.0.0 to 1.1.1 (#8389)
- [ ] 010e359e4 fix: upgrade react-datepicker from 2.14.1 to 2.16.0 (#8388)
- [ ] 0c9d88b44 fix: upgrade prop-types from 15.7.2 to 15.8.1 (#8387)
- [ ] 2d91646aa fix: upgrade js-yaml from 3.13.1 to 3.14.1 (#8374)
- [ ] 54eaed060 fix: upgrade cron-parser from 2.16.3 to 2.18.0 (#8373)
- [ ] e9de085d6 fix: Erratum in docs. Fixes #8342 (#8359)
- [ ] a3d1d07e1 fix: upgrade react-chartjs-2 from 2.10.0 to 2.11.2 (#8357)
- [ ] b199cb947 fix: upgrade history from 4.7.2 to 4.10.1 (#8356)
- [ ] e40521556 fix: upgrade multiple dependencies with Snyk (#8355)
- [ ] 8c893bd13 fix: upgrade com.google.code.gson:gson from 2.8.9 to 2.9.0 (#8354)
- [ ] ae3881525 fix: examples/README.md: overriten => overridden (#8351)
- [ ] ab21eed52 fix: upgrade io.swagger:swagger-annotations from 1.6.2 to 1.6.5 (#8335)
- [ ] f708528fb fix: upgrade react-monaco-editor from 0.36.0 to 0.47.0 (#8339)
- [ ] 3c35bd2f5 fix: upgrade cronstrue from 1.109.0 to 1.125.0 (#8338)
- [ ] 7ee17ddb7 fix: upgrade com.squareup.okhttp3:logging-interceptor from 4.9.1 to 4.9.3 (#8336)
- [ ] aa9ff17d5 fix: Remove path traversal CWE-23 (#8331)
- [ ] 14a9a1dc5 fix: ui/package.json & ui/yarn.lock to reduce vulnerabilities (#8328)
- [ ] 58052c2b7 fix: sdks/java/pom.xml to reduce vulnerabilities (#8327)
- [ ] e232340cc fix: grep pattern (#8238)
- [ ] 8a1fbb86e fix: removed deprecated k8sapi executor. Fixes #7802 (#8205)
